### PR TITLE
Create o365-spheres-of-support.md

### PR DESCRIPTION
**Pull request by rsnick**
Converted table heavy .xlsx document provided by John Kowalik/Product team to markdown formatting - attempted to preserve formatting from the original document as best as possible. Additionally, added metadata/brief prerequisite section for consistency with other support.rackspace.com articles, as well as cleaning up broken and mis-routed links. Document outlines our spheres/scope of support for Office 365 products and features (both for 'Fanatical Support' and 'Rackspace Application Services').

### CODE REVIEW

**Comment by robb-romans** [comment]
@viridaria is investigating and will respond with an update. Thank you.

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2289 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-58e74a8cb/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2290 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3d8ef6b8d/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2292 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c03880111/how-to/). valid for 14 days

**Pull request merged**
