### PR TITLE
Community Article - CentOS - Nginx Virtual Hosts: INFODEV-3364

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-4af8171b1b/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8f5bc03ec6/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b6615f74fd/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e5f75dc513/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On  it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested change here: 
[create-centos-nginx-virtual-hosts_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2808772/create-centos-nginx-virtual-hosts_cyrEdits.docx)

Note that I forgot to turn on track changes and the suggestions are just highlighted in yellow in the file.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-28f6a369ab/how-to/).

**Pull request merged**
