### PR TITLE
add new article from amber melita and two associated images

### PR DESCRIPTION
**Pull request by stephamon**
New article on renaming Rackspace Email mailboxes

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-fe68dc394d/how-to/)

**Comment by kmsholcomb** [comment]
Hi @stephamon. I'm trying something new and uploading the Word and PDF edits to Google Drive. The Google doc (Word doc) is at https://docs.google.com/a/gapps.rackspace.com/document/d/18U5HgMBHIHgt8QWp0jqHs3Nfqfxc5t89ISFDPolTFB4/edit?usp=sharing, and the PDF copy is at https://drive.google.com/a/gapps.rackspace.com/file/d/0ByQG6CoQb-smckZHeHo3VXctSFk/view?usp=sharing. Let me know if you have any problems accessing or seeing them.

My main suggestion is to move the information at the beginning out of a note and into a "Before you begin" section. Even though that info does not apply to everyone, because data loss is possible, it should be emphasized more. I also suggest that we might add another step or two to the end of the procedure, just for those users who have to do something after they click **Save**. Please let me know if you have any questions. Thanks!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-05cf30b0db/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-681419e2b5/how-to/)

**Pull request merged**
