### PR TITLE
Rax how-to objectrocket

### PR DESCRIPTION
**Pull request by tanberry**
I'm relearning git, so if there's anything fishy about this PR, please feel free to reject and I'll try again! @stephamon :-)

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 486 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ea90ead3e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 487 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d85cc7269/how-to/). valid for 14 days

**Comment by tanberry** [comment]
Thanks @stephamon ! Is it ok for me to leave that branch there for another day or two, until I finish the second round of edits? Then I will delete the branch.

**Comment by stephamon** [comment]
@tanberry of course! It's your branch :)

**Pull request merged**
