### PR TITLE
Fix code blocks at the end of Backup article

### PR DESCRIPTION
**Pull request by DonNateR**
Code blocks not formatting correctly.

Not related to an issue

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-fe6dac3bd5/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-dd1f654fcc/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dcf029b065/how-to/).

**Comment by stephamon** [comment]
👍

**Pull request merged**
