### PR TITLE
Community Article - Mount Partition and Chroot into Primary Filesyste…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…m from Rescue Mode: INFODEV-3241

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a6c01c02f1/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0e4641991f/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7336a3a17d/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b5beeb874f/how-to/)

**Comment by RackerKate** [comment]
Article shows up as 1 large para. Replaced by https://github.com/rackerlabs/rackspace-how-to/pull/3054.

**Pull request closed without merging**
