### PR TITLE
Community Article - Closing Out Your Rackspace Account

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b8be327caf/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-87d3c03419/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-d0a2217526/how-to/)

**Comment by WilliamLoy** [comment]
@cyrichardson a short one for you :)

**Comment by cyrichardson** [comment]
@WilliamLoy On it.

**Comment by cyrichardson** [comment]
@WilliamLoy Suggestions here: 
[close-your-rackspace-account_cyrEduts.docx](https://github.com/rackerlabs/rackspace-how-to/files/2869576/close-your-rackspace-account_cyrEduts.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-060dbf271c/how-to/)

**Pull request merged**
