### PR TITLE
edited Gluster article

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1047 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f45230f78/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1048 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-af8f0fdae/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@stephamon or @cyrichardson this is ready for edits.

**Comment by rackernexus** [comment]
Build 1050 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f43246599/how-to/). valid for 14 days

**Pull request merged**
