### PR TITLE
Audit firewall-manager-v2-access-list-theory-and-best-practices: INFODEV-1280

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-580edf8f46/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate - on it.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[firewall-manager-v2-access-list-theory-and-best-practices_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1830379/firewall-manager-v2-access-list-theory-and-best-practices_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1a66c0ca14/how-to/).

**Pull request merged**
