### PR TITLE
update instructions for accessing control panel

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 3907

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by stephamon** [comment]
Hey @cyrichardson can you review please?

**Comment by cyrichardson** [comment]
@stephamon  On it!

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e114fbd834/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c4c3618efe/how-to/)

**Pull request merged**
