### PR TITLE
Create sql-server-database-recovery-models

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1709 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8fdd572e2/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1710 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8fdd572e2/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1711 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9b9181462/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1712 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fd457c59f/how-to/). valid for 14 days

**Comment by catlook** [comment]
sql-server-database-recovery-models

**Comment by catlook** [comment]
waiting for Shaun's feedback

**Pull request merged**
