### PR TITLE
Merge login intel-dedicated article with overview article: INFODEV-2590

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-ea0d480a98/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1d17c45aa2/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate  Just a couple of suggestions: 
[getting-started-with-rackspace-intelligence-for-dedicated-accounts_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2538692/getting-started-with-rackspace-intelligence-for-dedicated-accounts_cyrEdits.docx). 

The changes in "Log in to Rackspace Intelligence for dedicated accounts" look good to me.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-003133cb7b/how-to/)

**Pull request merged**
