### PR TITLE
Change all directory paths to code blocks

### PR DESCRIPTION
**Pull request by DonNateR**
-Fix issue #1253

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3ff936f1b7/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5b06dcf240/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0f39f9a326/how-to/)

**Comment by catlook** [comment]
👍

**Pull request merged**
