### PR TITLE
Update to Aaron's upgrade addition

### PR DESCRIPTION
**Pull request by DonNateR**
Part of PR #1553. Had to change PR's because of some GitHub configuration issues.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-805d0e5ce2/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits are in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. Thanks!

[Upgrading to Exchange 2016_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/551647/Upgrading.to.Exchange.2016_editsKH.pdf)
[Upgrading to Exchange 2016_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/551646/Upgrading.to.Exchange.2016_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3038e8d841/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ff5d728f3c/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4ac5ace1a2/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7a5805767e/how-to/). :bow:

**Comment by stephamon** [comment]
👍

**Pull request merged**
