### PR TITLE
Correct exchange forward typo

### PR DESCRIPTION
**Pull request by WilliamLoy**
small typo fix

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b31b09d046/how-to/)

**Comment by stephamon** [comment]
👍

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d8b436cac8/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b85f6127ac/how-to/).

**Pull request merged**
