### PR TITLE
Add schema optimization script

### PR DESCRIPTION
**Pull request by cyrichardson**
I made the text editing of the file step 1. Is that OK?
Or should I duplicate the article exactly in the script or rewrite this article to show substeps for creating the file, @stephamon?

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-30ab4264d4/how-to/)

**Comment by cyrichardson** [comment]
@stephamon Please review and advise. Thanks!

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0e09d7f2f2/how-to/)

**Comment by stephamon** [comment]
Hey @cyrichardson sorry that I didn't see your first ping! For some reason, I didn't get a notification for it. I think the way you've done it looks great!

**Comment by cyrichardson** [comment]
Thanks, @stephamon!

**Pull request merged**
