### PR TITLE
Added missing Cloud Metrics roles

### PR DESCRIPTION
**Pull request by inflatador**
https://developer.rackspace.com/docs/metrics/v2/

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by catlook** [comment]
still waiting to confirm we're good to merge!

**Pull request merged**
