### PR TITLE
Update create-a-dkim-txt-record.md

### PR DESCRIPTION
**Pull request by CarlDRacker**
*NOTE:  This method differs from the way DKIM is set up for Rackspace Hosted Email and Exchange customers. If you are a Rackspace Email, Hosted Exchange or Office 365 customer, please contact the Rackspace Cloud Office Team for help with configuring the proper DKIM, DMARC and SPF records.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b62ff254c2/how-to/)

**Comment by CarlDRacker** [comment]
We've had Cloud Office customer contact referencing this article and this has caused problems for them when they have found this guide and tried to implement by it. Thanks.

**Comment by DonNateR** [comment]
@CarlDRacker: Thank you for your contribution! We will be adding this to our next sprint.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6201185400/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Suggested edits are attached. Please let me know if you have any questions. Thanks!

[Create a DKIM TXT record type_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/809054/Create.a.DKIM.TXT.record.type_editsKH.pdf)
[Create a DKIM TXT record type_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/809053/Create.a.DKIM.TXT.record.type_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-5e6e822e25/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-8043a280c4/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a37fd4873b/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6010b20a2c/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-027b51de96/how-to/)

**Comment by nimbinatus** [comment]
+1

**Pull request merged**
