### PR TITLE
Community Article - Network Config for eth0 Changed to DHCP After Upg…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…rading RHEL/CentOS

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e4fc10e056/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1201ed927e/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-689f881660/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6d566804de/how-to/)

**Comment by cyrichardson** [comment]
@erikmwilson Here are some suggestions for this one: 
[network-configuration-for-eth0-changed-to-dhcp-after-upgrading-rhel-centos_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2877559/network-configuration-for-eth0-changed-to-dhcp-after-upgrading-rhel-centos_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4a10dc121e/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f42890ff98/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-166a133042/how-to/).

**Pull request merged**
