### PR TITLE
Add community article about Ansible: INFODEV-3283

### PR DESCRIPTION
**Pull request by RackerKate**
Replaces #3127 .

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-488af59b49/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-678d5067d0/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate Just a few suggestions: 
[install-ansible-playbook-for-cloud-monitoring_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2789334/install-ansible-playbook-for-cloud-monitoring_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-90a22f0e51/how-to/).

**Pull request merged**
