### PR TITLE
Fix formatting on Building Cloud Orchestration templates article

### PR DESCRIPTION
**Pull request by aaronmehar**
Incorporating some internal feedback from this article.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d5c66f03f4/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5244f75039/how-to/)

**Comment by DonNateR** [comment]
@aaronmehar: Merging. Out of curiosity, where did you find out how to fix the vertical line character?

**Comment by aaronmehar** [comment]
Hey @DonNateR - I know how to escape characters in other languages and its ACSII code, but am not familar with Nexus, or escaping in Markdown, so I sent PR #1429 so nexus control render a build environment to see which method worked. They all worked.

**Pull request merged**
