### PR TITLE
BCP - combine-invoices-for-rackspace-managed-and-cloud-accounts

### PR DESCRIPTION
**Pull request by catlook**
placeholder PR

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c984badf78/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8ab9be4a52/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3118d583d4/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-845abb95d0/how-to/)

**Comment by cyrichardson** [comment]
@catlook Suggestions in 
[combine-invoices-for-rackspace-managed-and-cloud-accounts_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1721780/combine-invoices-for-rackspace-managed-and-cloud-accounts_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c0fbf77392/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-075194bf42/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
