### PR TITLE
New linux sos article#1841

### LINKED ISSUE #1841: Dedicated: New SOS article
I'd like to start the process to get this article published in the dedicated how-to section:

https://github.com/mralexjuarez/rackspace-how-to/blob/master/content/dedicated-hosting/linux-spheres-of-support.md

As part of the publishing process, I'd also like to remove the article linked below and instead redirect visitors to the new article above which it is designed to supersede:

https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/cloud-servers-with-managed-operations-support-for-linux.md

The end goal of this operation is to have one single 'spheres of support' document on the how-to site that applies to both Dedicated & Managed Operations cloud customers.

In addition to the content changes above, I was advised by legal to include a disclaimer, like to what is found at the end of this document (page 5):

http://www.associatedsalesgroup.com/pdf/RS-Fanatical-Support-for-365-Spheres-of-Support.pdf

Is it possible to have a disclaimer page that the article links out to like the current usage/license terms, or is something that would need to be inline? I'd prefer a link if possible, as that would make it easy for Windows or other groups publishing SOS type content can all link to the same, consistent disclaimer verbiage.

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1841 

adding new article for Linux SOS for Dedicated and Managed Ops
retiring old Linux SOS article
updating links to point at new article

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e1837cb91d/how-to/). :bow:

**Comment by stephamon** [comment]
Here's the redirect: https://github.com/rackerlabs/nexus-control/pull/693

**Comment by stephamon** [comment]
@kmsholcomb can you add this to your editing queue as well, please?

**Comment by kmsholcomb** [comment]
Hi @stephamon. My edits are in the attached Word doc and PDF copy of it. I'm not sure if you can make all the changes I suggest (like getting rid of the repetitive "Fanatical Support® for Linux" wording that starts each section); there might be some legal-ish requirements there. But make the wording simpler wherever you can. 

[Linux Spheres of Support for Dedicated and Managed Operations_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/822637/Linux.Spheres.of.Support.for.Dedicated.and.Managed.Operations_editsKH.pdf)
[Linux Spheres of Support for Dedicated and Managed Operations_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/822638/Linux.Spheres.of.Support.for.Dedicated.and.Managed.Operations_editsKH.docx)

Speaking of simple, I noticed that everything that is listed is supported (that is, all the table cells say Yes). If that is the case, then tables aren't really necessary. I mocked up a file that deletes the tables, shows the supported things in lists, and revises the intros. I know that making this change will make this article look different from the current Windows support article, and it might cause problems if we decide to list something that is not completely supported, but I wanted to throw it out there as a simpler alternative.  

[Linux Spheres of Support for Dedicated and Managed Operations_mockupKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/822639/Linux.Spheres.of.Support.for.Dedicated.and.Managed.Operations_mockupKH.docx)

Let me know if you have any questions. Thanks!

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-368185052b/how-to/)

**Pull request merged**
