### PR TITLE
H2 article audit - 11 of 20.

### PR DESCRIPTION
**Pull request by catlook**
Closes issue # 1081

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bfa63cc40e/how-to/)

**Comment by catlook** [comment]
@kmsholcomb quick...edit this before someone changes it again!!! ack.

**Comment by meker12** [comment]
so this is odd:   When I click the Strider build job, I see this: 
Cloud-Sites-image-updates-160617-1

but this PR is from branch: catlook:ccl-issue-1081

**Comment by catlook** [comment]
opps...i was waiting on Kelly edits...so i'll need to remerge this

**Comment by catlook** [comment]
well..apparently i can do that, so i'll make a new PR.

**Pull request closed without merging**
