### PR TITLE
Audit article: INFODEV-3078

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cd6bc5ace1/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of nits/suggestions here: 
[back-up-data-with-cloud-files_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2741190/back-up-data-with-cloud-files_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2f734e8b49/how-to/)

**Pull request merged**
