### PR TITLE
Jp pr

### PR DESCRIPTION
**Pull request by stephamon**
Decided not to add the images because they were screenshots of nav bar icons. Moved the article to the "general" folder. Did some edits.

### CODE REVIEW

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1586 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ca8f5c9b6/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1591 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fb588037f/how-to/). valid for 14 days

**Pull request merged**
