### PR TITLE
Create viewing-system-users-in-linux

### PR DESCRIPTION
**Pull request by csilva235**
New article for viewing users on a Linux server.

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1951 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-48275a175/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1953 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-48275a175/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1954 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7856f214e/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1955 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7856f214e/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1957 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fbad64985/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready :)

**Comment by cyrichardson** [comment]
On it in a bit, @WilliamLoy.

**Pull request merged**
