### PR TITLE
Add community article on fresh branch: INFODEV-3178

### PR DESCRIPTION
**Pull request by RackerKate**
…ge paragrah. Duplicates https://github.com/rackerlabs/rackspace-how-to/pull/3018.

### CODE REVIEW

**Comment by RackerKate** [comment]
Create article on a fresh branch to try to break up one large paragraph.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a9d4e3859a/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just 2 trademark additions: 
[set-up-two-factor-authentication-by-using-google-authenticator_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2770200/set-up-two-factor-authentication-by-using-google-authenticator_cyrEdits.docx)

**Pull request merged**
