### PR TITLE
full audit

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@cyrichardson got this one ready for edits

**Comment by cyrichardson** [comment]
On it, @WilliamLoy

**Comment by rackernexus** [comment]
Build 694 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b7ead9dd1/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 695 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ed0ea08ce/how-to/). valid for 14 days

**Pull request merged**
