### PR TITLE
Cloud sites image pruning 160621 2

### PR DESCRIPTION
**Pull request by kylelaffoon**
Remove images and clean up verbiage for Manage Cloud Sites Email DNS Records and Migrate a Cloud Site from MSSQL2005 to MSSQL2008 articles.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1d3ba58bb5/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bce8dc238c/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-fdcbcda61f/how-to/). :bow:

**Comment by cyrichardson** [comment]
LGTM. Merging.

**Pull request merged**
