### PR TITLE
Updates to branch Hdansou upgrade xentools

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes PR #1006

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c7ce2424b3/how-to/)

**Comment by DonNateR** [comment]
Needs a quick tech review before merging.

**Comment by DonNateR** [comment]
Luke Repko will be testing the code changes before we merge these changes. Should know the answer by next week.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8b5fa35803/how-to/)

**Comment by hdansou** [comment]
@DonNateR There is a formatting issue on the article where a mutiple line code block turned into a single. It is the code block between the following lines "Your output output similar to the following:" and "Upgrade to XenServer Tools 6.5 on the new non-production server"

**Comment by DonNateR** [comment]
@hdansou: The issue should be fixed now!

**Pull request merged**
