### PR TITLE
New article: Create an object group

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-26dbcaf7f5/how-to/). :bow:

**Comment by DonNateR** [comment]
We should consider renaming this to "Add an object group" since that's the most commonly used search term.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d271c5a9d5/how-to/).

**Comment by cyrichardson** [comment]
@DonNateR Suggested changes here: 
[create-an-object-group-with-firewall-manager-v2_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2190275/create-an-object-group-with-firewall-manager-v2_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d7478df7ac/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-114880a8c1/how-to/)

**Pull request merged**
