### PR TITLE
Add SME notes for Linux article

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes issue #1432

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7ad8745cd7/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-836ff259bd/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR: I edited the article, and my markup is in the attached docs. Apart from copy edits to the text, I also suggested adding some headings to better describe the different steps. Let me know if you have any questions. Thanks!
 
[Check running services on Linux_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/520013/Check.running.services.on.Linux_editsKH.pdf)
[Check running services on Linux_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/520014/Check.running.services.on.Linux_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-26647c1b55/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-82abf0e321/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b1f9b96b22/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-fb8f5fb3eb/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0fbf9c094e/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1a28e97601/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-55ef5ae183/how-to/). :bow:

**Comment by catlook** [comment]
LGTM

**Pull request merged**
