### PR TITLE
Fix developer links in monitoring API

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1764

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f8b5fbde69/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Finally! This FAQ was in rough shape! It was all out of order, had lots of bad links, and had a strange mixture of marketing and product Q&A. I tried to address all that in my edits.

The **Rackspace Monitoring FAQ_editsKH** files (Word and PDF) contains my edits of the content, and provides some suggestions for moving or reordering the content. But then I decided to take a stab at doing the reordering myself. The **revised order headings** file shows the new section headings I would create and the order in which I would put the Q&A pairs under them. The **revised order with edits** files shows what the article would look like with the new order and the edited text (minus some things I asked questions about and wasn't sure how to change). If you decide to do the rearranging I suggest, then hopefully this mockup will help.

Anyway, please let me know if you have any questions. 

[Rackspace Monitoring FAQ_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/715364/Rackspace.Monitoring.FAQ_editsKH.pdf)
[Rackspace Monitoring FAQ_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/715363/Rackspace.Monitoring.FAQ_editsKH.docx)
[revised order headings.docx](https://github.com/rackerlabs/rackspace-how-to/files/715362/revised.order.headings.docx)
[revised order with edits.docx](https://github.com/rackerlabs/rackspace-how-to/files/715365/revised.order.with.edits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5af6609db9/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e336f41f54/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-974256877e/how-to/).

**Comment by stephamon** [comment]
👍

**Pull request merged**
