### PR TITLE
How Does Cloud Billing Work?

### PR DESCRIPTION
**Pull request by BadCrumpany**
Working on migrating useful articles from the community before it is shut down.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f798b4f404/how-to/)

**Comment by RackerKate** [comment]
@BadCrumpany I'd like to fold this content into the existing Cloud Billing FAQ at https://support.rackspace.com/how-to/rackspace-billing-faq/. Does that sound OK to you?

**Comment by RackerKate** [comment]
Replaced by #3149

**Pull request closed without merging**
