### PR TITLE
Pr 1610 - merge on 11/17

### PR DESCRIPTION
**Pull request by stephamon**
Adding images to #1610 

@kmsholcomb Can you add this to your list for editing?

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-54bb90c047/how-to/)

**Comment by kmsholcomb** [comment]
Will do, @stephamon.

**Comment by kmsholcomb** [comment]
Hi @stephamon. My suggested edits are in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. Thanks!

[Getting Started With Cloud Sites_How to add new mailboxes_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/586665/Getting.Started.With.Cloud.Sites_How.to.add.new.mailboxes_editsKH.pdf)
[Getting Started With Cloud Sites_How to add new mailboxes_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/586664/Getting.Started.With.Cloud.Sites_How.to.add.new.mailboxes_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-debc404852/how-to/)

**Pull request merged**
