### PR TITLE
Add Fedora 24

### PR DESCRIPTION
**Pull request by oldarmyc**
Fedora 24 hit EOL and adding it to hidden list

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-40dbf375bb/how-to/). :bow:

**Comment by DonNateR** [comment]
@oldarmyc: Thank you for your contribution! Do you know of any other instances in our documentation where Fedora 24 is mentioned?

**Comment by oldarmyc** [comment]
Not that I know, but have not looked through all of it.

**Comment by DonNateR** [comment]
I'll look at our documentation for mentions of Fedora 24 during our next Sprint.

**Pull request merged**
