### PR TITLE
Update set-up-mysql-master-slave-replication.md

### PR DESCRIPTION
**Pull request by chrisinmtown**
In MySQL 8.0 I had to create the replication user before I could grant it permissions.  The server did not accept the "identified by" clause on the grant line.  I propose this change, please consider it, thanks.

### CODE REVIEW

**Comment by chrisinmtown** [comment]
Thank you @catlook. This guide to mysql replication still has many problems, I only fixed the most egregious one.  Further on github repo I see that the note "DEPRECATED. Use https://github.com/rackerlabs/support-how-to" so I guess this guide is dead, and probably I should just abandon this PR. What do you think?

**Comment by catlook** [comment]
@chrisinmtown This repo is deprecated (not the How-to itself).  We're migrating to the new repo, support-how-to, on Thursday.  I'd like to publish this article in the current, deprecated repo before we complete the migration.  Whom should I get to validate the rest of the article?

**Comment by catlook** [comment]
@chrisinmtown Ok, I'm going to publish this with our updates and open a ticket to do a full audit.  Thanks for helping us keep our content up-to-date!

**Comment by chrisinmtown** [comment]
I recommend you take a careful look at step 8 where it says to edit the /etc/my.cnf file and add entries master-host, master-user, master-password and master-connect-retry.  Mysql version 8 rejects all those configuration keys. Perhaps they were accepted in other versions, I cannot say.

**Comment by catlook** [comment]
Thanks, Chris!  We'll audit this article!!

**Pull request merged**
