### PR TITLE
Review of Managed Ops Pricing article

### LINKED ISSUE #1800: Update or remove managed cloud service level pricing article
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/managed-cloud-service-level-pricing.md

Needs to be updated or removed; we need to reach out to Nicole in REACH for more information.

### PR DESCRIPTION
**Pull request by nimbinatus**
Fixes #1800

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3ef5a5cc59/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-88fed025ea/how-to/). :bow:

**Comment by nimbinatus** [comment]
@kmsholcomb, this one is short, but I could use another set of eyes because I'm not really sure it jives with how-to as a whole. Can you add it to your editing queue? Thanks!

**Comment by kmsholcomb** [comment]
Hi @nimbinatus. My copy edits are attached. I suggested creating two small sections to get rid of the pesky single heading, but you could just as easily delete the headings in such a short article, as long as the infrastructure and support content is presented separately. Anyway, when I see this type of article, I always feel like it _should_ be information that is presented with the other pricing information on the main Rackspace website. It sounds like the reason we created it at all was to fill a gap, though, and if the gap still exists, we should keep it. Perhaps, though, we could consider putting the information in the [Managed Cloud Service Levels FAQ](https://support.rackspace.com/how-to/managed-cloud-service-levels-faq/) instead (if we feel like it really doesn't warrant its own article, now that all the pricing content is gone)? Well,  I'll leave that decision to the team.

[Managed Cloud Service Level pricing_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/750986/Managed.Cloud.Service.Level.pricing_editsKH.pdf)
[Managed Cloud Service Level pricing_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/750985/Managed.Cloud.Service.Level.pricing_editsKH.docx)

**Comment by nimbinatus** [comment]
@kmsholcomb, I agree. I don't really see the gap any longer, but I'll send it out to the group to see if people agree. If we keep it, it definitely could go into the main FAQ instead of being a separate entity, though.

**Comment by nimbinatus** [comment]
After discussion, the article will be rolled into the main FAQ instead.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-eb67886f09/how-to/)

**Pull request merged**
