### PR TITLE
Add community article. Replaces #3043: INFODEV-3241

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by RackerKate** [comment]
Replaces https://github.com/rackerlabs/rackspace-how-to/pull/3043.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d259b90c5a/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[mount-a-partition-and-chroot-into-your-primary-file-system-from-rescue-mode_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2773373/mount-a-partition-and-chroot-into-your-primary-file-system-from-rescue-mode_cyrEdits.docx)

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[mount-a-partition-and-chroot-into-your-primary-file-system-from-rescue-mode_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2773379/mount-a-partition-and-chroot-into-your-primary-file-system-from-rescue-mode_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0e61d31f53/how-to/). :bow:

**Pull request merged**
