### PR TITLE
include SME changes

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 794 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ef52b4ec4/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
@stephamon Would you mind reviewing this for me since Catherine is out for a few?

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
@cyrichardson Would you also mind reviewing this one?

**Comment by cyrichardson** [comment]
On it, @Sterling463.

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 814 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4e17ebc2b/how-to/). valid for 14 days

**Pull request merged**
