### PR TITLE
BCP-update-overview-role-based-access-control-rbac: INFODEV-911

### PR DESCRIPTION
**Pull request by RackerKate**
Initial commit to create PR. PLACEHOLDER ONLY. Please do not merge.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9c12260a02/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-bb120b9552/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3c8e21e415/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4cb65fed3a/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-ac86b41cb7/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-acce9e2af1/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-2d48931e04/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6d66e6a7a0/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@kate On my list for tomorrow.

**Comment by cyrichardson** [comment]
Just a few suggestons: 
[overview-role-based-access-control-rbac_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1744510/overview-role-based-access-control-rbac_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4e2489ae94/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cafca51a92/how-to/)

**Pull request merged**
