### PR TITLE
Wl renamed email android

### PR DESCRIPTION
**Pull request by stephamon**
takes over #2222

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-1a378a438c/how-to/). :bow:

**Comment by stephamon** [comment]
Hey @kmsholcomb I applied your feedback to the iPhone article to this one, but it should probably get a look by itself.

**Comment by kmsholcomb** [comment]
Will do!

**Comment by kmsholcomb** [comment]
Hi @stephamon. Just a few nits. Let me know if you have any questions. Thanks!

[Configure a renamed email address on Android mobile phone_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1293642/Configure.a.renamed.email.address.on.Android.mobile.phone_editsKH.docx)
[Configure a renamed email address on Android mobile phone_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1293643/Configure.a.renamed.email.address.on.Android.mobile.phone_editsKH.pdf)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a0227cac9c/how-to/).

**Pull request merged**
