### PR TITLE
Incorporate update for reverting from rescue mode

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by kylelaffoon** [comment]
Add reversion steps to end of article. 
- Fixes #756

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-1091eabbb7/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-03c0636d35/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-73c7777f82/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-6f6fb4b9fa/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b5b4a36a97/how-to/)

**Pull request merged**
