### PR TITLE
More clear around resizing

### PR DESCRIPTION
**Pull request by inflatador**
Resize information, including BFV

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6cae73bf99/how-to/)

**Comment by RackerKate** [comment]
@inflatador , could you take a look at my edits and verify that everything looks OK? Thanks!

**Comment by inflatador** [comment]
Looks great, thanks @RackerKate  !

**Comment by RackerKate** [comment]
@stephamon Please review.

**Comment by stephamon** [comment]
Will do @RackerKate!

**Comment by stephamon** [comment]
LGTM!

**Pull request merged**
