### PR TITLE
Servers content edit 2

### PR DESCRIPTION
**Pull request by stephamon**
Part of #705

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2739b4daf3/how-to/)

**Comment by stephamon** [comment]
@kmsholcomb can you take a look at the rsync article in the PR? I've made some pretty big changes myself, but it could probably use a second pair of eyes.

**Comment by kmsholcomb** [comment]
Will do, although I might not get to it today. If you want to merge the PR, you could just create a separate issue and assign me to it.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3dddbf659e/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1685efa5e4/how-to/)

**Comment by kmsholcomb** [comment]
Hi @stephamon. I will edit this today!

**Comment by stephamon** [comment]
Thanks @kmsholcomb! I'll probably update that file with a separate PR

**Comment by kmsholcomb** [comment]
Hi @stephamon. Great changes! I had just a few extra edits. See the attached file. Thanks!

[Back up your files with rsync_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/291771/Back.up.your.files.with.rsync_editsKH.pdf)
[Back up your files with rsync_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/291770/Back.up.your.files.with.rsync_editsKH.docx)

**Pull request merged**
