### PR TITLE
Create resetting-cloud-server-network-with-pitchfork

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1714 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3d20860ed/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1715 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3d20860ed/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1716 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d5777b3bd/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
On it in just a bit, @catlook!

**Pull request merged**
