### PR TITLE
Updated 365 articles with COFFEE instructions

### PR DESCRIPTION
**Pull request by fm**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 264 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e8ecc0499/how-to/). valid for 14 days

**Comment by fm** [comment]
Noticed the **Enable Email Archiving for Office 365** link on the main Archiving page
https://support-revs.staging.deconst.org/build-e8ecc0499/how-to/rackspace-email-archiving/

 points to `/how-to/add-rackspace-office-365-archiving/` instead of `/how-to/enable-email-archiving-for-office-365/`

**Comment by fm** [comment]
build me

**Comment by rackernexus** [comment]
Build 265 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5a35762d0/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 266 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4dd4c7a34/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 267 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4dd4c7a34/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 268 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8d22e9786/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 269 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0662f82f2/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 270 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c6861be14/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 271 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-54fdbbe85/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 272 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f5154876b/how-to/). valid for 14 days

**Pull request merged**
