### PR TITLE
updated the recommended monitoring zones

### PR DESCRIPTION
**Pull request by wolfdancer**
Based on the recent latency analysis, we have updated the recommended monitoring zones

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-81ad170da7/how-to/).

**Comment by nimbinatus** [comment]
Thanks for your contribution, @wolfdancer! We will pull this into our next sprint.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Just a few copy edits. Let me know if you have any questions. Thanks! 

[Rackspace Monitoring checks and alarms_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/879902/Rackspace.Monitoring.checks.and.alarms_editsKH.pdf)
[Rackspace Monitoring checks and alarms_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/879901/Rackspace.Monitoring.checks.and.alarms_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d938e12250/how-to/).

**Comment by catlook** [comment]
LGTM

**Pull request merged**
