### PR TITLE
delete cloud sites content and assets and remove logo from howto land…

### LINKED ISSUE #1910: Cloud Sites documentation
This issue is detailed internally.
Week of April 10.

### PR DESCRIPTION
**Pull request by stephamon**
…ing page

fixes #1910

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4aa027db69/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-eba2904741/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-248be8f24d/how-to/)

**Comment by nimbinatus** [comment]
+1, LGTM

**Pull request merged**
