### PR TITLE
Update checking-linux-file-permissions-with-ls.md

### PR DESCRIPTION
**Pull request by mbarren13**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-33e851a108/how-to/)

**Comment by catlook** [comment]
@mbarren13  - I don't understand why you added a "to" at the end of line 180.  Is this a mistake?  If not, can we talk?

**Comment by catlook** [comment]
Ah, I think I know what you're saying.  You're suggesting that we change "The `user` permissions apply to the owner of the file, so in this case, the user 'root' has read, write, and execute permissions for this directory." to "The `user` permissions apply to owner of the file, so in this case, the user 'root' has read, write, and execute permissions to this directory." Is that right?  

If so, our editor confirms that "for" is correct, in this case.  You would read or write to a directory, but you have permissions for it.  I am going to tweak your PR and merge it, however, to add "the" before "owner" in that sentence.  Thanks for the contribution!

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-87be8edef0/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b3c14d0196/how-to/). :bow:

**Pull request merged**
