### PR TITLE
added screen shots

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-133ed14f3b/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-965653956a/how-to/)

**Comment by cyrichardson** [comment]
Suggestions here: 
[view-administrator-activity-in-the-cloud-office-control-panel_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1771546/view-administrator-activity-in-the-cloud-office-control-panel_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4a7a99c811/how-to/)

**Pull request merged**
