### PR TITLE
Streamline object-group intro article

### PR DESCRIPTION
**Pull request by DonNateR**
4 more article PR's incoming

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7d1e779e68/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f682a3a3e2/how-to/)

**Comment by cyrichardson** [comment]
@DonNateR Suggested changes here: 
[firewall-manager-v2-object-groups_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2190124/firewall-manager-v2-object-groups_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cceb99c403/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-732141b6f4/how-to/)

**Pull request merged**
