### PR TITLE
Community Article - Site-to-Site IPsec VPN Connection between Vyatta …

### PR DESCRIPTION
**Pull request by BadCrumpany**
…and Fortigate: INFODEV-3545

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3105b681bb/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-f64b51eda6/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-edd57fc4ac/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e749661160/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1bdb3c8d4e/how-to/).

**Comment by RackerKate** [comment]
Needs final SME review.

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Just a few suggestions here: 
[create-a-site-to-site-ipsec-vpn-connection-between-vyatta-and-fortigate_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2882115/create-a-site-to-site-ipsec-vpn-connection-between-vyatta-and-fortigate_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-08bafe49c1/how-to/)

**Pull request merged**
