### PR TITLE
fixed the link to the enum support article

### PR DESCRIPTION
**Pull request by wolfdancer**
Fixed the link after [Use enum support]

### CODE REVIEW

**Comment by DonNateR** [comment]
@wolfdancer: Would you like us to go ahead and merge?

**Comment by wolfdancer** [comment]
@DonNateR : I am still learning the process.  So it is ok for me to push the merge button now?  

For future reference, after submitting PR and making changes, do I wait for an additional comment as the next step of merging?

In comparison, on some projects, another member on the project will give +1 or  :+1:.  Is there such a signal on this project?

**Comment by DonNateR** [comment]
@wolfdancer: The How-to team has to review all PR's before they are merged.  Whenever you are ready for the PR to be reviewed, just make a comment on the PR and we'll take a look.

This could change in the future but this is how we're doing it for now. Does that work for you?

**Comment by wolfdancer** [comment]
@DonNateR Thanks for explanation.  I think I read too much into your comment earlier.  Yes please go ahead and merge this in.  Thanks.

**Pull request closed without merging**
