### PR TITLE
[WIP] Full Audit, ref issue #1666

### LINKED ISSUE #1666: Full audit: linux patching for cloud servers managed operations service level
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/linux-patching-for-cloud-servers-managed-operations-service-level.md

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

### PR DESCRIPTION
**Pull request by nimbinatus**
proofing run before SME review.

Fixes #1666

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a011a0997c/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-87b28fbb58/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-2f8fce4ac7/how-to/)

**Comment by nimbinatus** [comment]
got a +1 from Ryan (SME). @kmsholcomb, can you add this one to your editing queue?

**Comment by kmsholcomb** [comment]
Hi, @nimbinatus. I'm always disappointed when an article is short (less to edit), but I always find something to say! :) The copy edits are minor, but I did have some questions about context and clarity. Let me know if you have any questions or feedback. Thanks!

[Linux patching for Cloud Servers with the Managed Operations service level_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/702962/Linux.patching.for.Cloud.Servers.with.the.Managed.Operations.service.level_editsKH.pdf)
[Linux patching for Cloud Servers with the Managed Operations service level_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/702963/Linux.patching.for.Cloud.Servers.with.the.Managed.Operations.service.level_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-24a334fa2b/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4f3c55977a/how-to/)

**Comment by nimbinatus** [comment]
@kmsholcomb, is this better? (Here's the drilled-down staging link: https://staging.developer.rackspace.com/support.rackspace.com/build-4f3c55977a/how-to/linux-patching-for-cloud-servers-managed-operations-service-level/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-51fdf3d32c/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
