### PR TITLE
replace reference to JungleDisk with dedicated

### PR DESCRIPTION
**Pull request by brett-johnson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 432 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-90d4aded9/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 434 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-081a9ce91/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 435 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-081a9ce91/how-to/). valid for 14 days

**Comment by catlook** [comment]
I made a few minor tweaks.  Thanks for the submission and updates, Brett!  Next time, could you make a branch instead of pushing to master?  That would be great :)

**Comment by rackernexus** [comment]
Build 441 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-403814f28/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 442 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-dd0cb8d9f/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 443 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9a2991c4d/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 444 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9a2991c4d/how-to/). valid for 14 days

**Pull request merged**
