### PR TITLE
Audit cloud-databases/exporting-data-from-mysql: INFODEV-1364

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7cbb176f92/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate  Suggested changes here: 
[exporting-data-from-mysql_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1925294/exporting-data-from-mysql_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-74cd9d8ddc/how-to/)

**Pull request merged**
