### PR TITLE
INFODEV-450 TriCore: Convert and add article for OBIEE 12c Data Blending, Mashup, and XSA

### PR DESCRIPTION
**Pull request by cyrichardson**
cache

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-536bea2a9b/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a80ed8e375/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e664471f96/how-to/).

**Comment by cyrichardson** [comment]
@kmsholcomb I was wrong! If you have time, I do have another how-to article I'd like you to take a look and provide your comments. This is another one of the TriCore docs converted to a How-To article. The original file is in https://jira.rax.io/browse/INFODEV-450.

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. Meager edits are attached. Please let me know if you have any questions. 

[Oracle Business Intelligence 12c new release features_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1342055/Oracle.Business.Intelligence.12c.new.release.features_editsKH.docx)
[Oracle Business Intelligence 12c new release features_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1342056/Oracle.Business.Intelligence.12c.new.release.features_editsKH.pdf)

**Comment by cyrichardson** [comment]
Thanks a ton, @kmsholcomb!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b4c8c60ca6/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-de0b2e65f7/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-387d9e2986/how-to/). :bow:

**Pull request merged**
