### PR TITLE
retired article

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
Build me

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 880 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-dc859edec/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 883 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-dc859edec/how-to/). valid for 14 days

**Pull request merged**
