### PR TITLE
make requested changes

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 2088 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-389d259bf/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 2106 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-bc2d04e34/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 2107 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-bc2d04e34/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 2108 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-af664ba6f/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 2109 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-af664ba6f/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 2110 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e1126aaa4/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2112 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1144c68ed/how-to/). valid for 14 days

**Comment by catlook** [comment]
ok @Sterling463, review the edits and see if you agree!

**Pull request merged**
