### PR TITLE
Editorial changes

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 1821 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7fa714699/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 1822 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7fa714699/how-to/). valid for 14 days

**Pull request merged**
