### PR TITLE
Add setup-apache2-webserver-on-two-instances-with-shared-ip back to repo

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-96739a81cd/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f9b086d55f/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ab3fc5ee1b/how-to/).

**Comment by catlook** [comment]
closing this...got handled in separate PR

**Pull request closed without merging**
