### PR TITLE
Update sharing-images-in-the-cloud-control-panel.md

### PR DESCRIPTION
**Pull request by joesavak**
need better direction on how to handle ORD

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e206dd7534/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a861edc578/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-1f145c8e36/how-to/)

**Comment by DonNateR** [comment]
Merging after making some edits.

**Pull request merged**
