### PR TITLE
RPC glossary update

### LINKED ISSUE #1739: Update OpenStack glossary of terms
Update OpenStack glossary of terms article (https://support.rackspace.com/how-to/openstack-glossary-of-terms/)  with the latest definitions from this page: https://github.com/openstack/openstack-manuals/blob/master/doc/common/glossary.rst .

### PR DESCRIPTION
**Pull request by nimbinatus**
working on the update

Fixes #1739

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-34212384a9/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9fcb0d915d/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e4c0c43cbd/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7459567253/how-to/). :bow:

**Comment by nimbinatus** [comment]
Note: Had to redo the git history to move the correct file to retired

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-22325fe920/how-to/)

**Pull request merged**
