### PR TITLE
Community Article - Disable TLS1.0 for Cloud Load Balancers: INFODEV-3353

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3ade9c1160/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6bc38b2eac/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5f4e0a0df3/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate Some suggested changes here: 
[disable-tls1-for-cloud-load-balancers_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2805110/disable-tls1-for-cloud-load-balancers_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ebceda2905/how-to/)

**Pull request merged**
