### PR TITLE
Update image sizes - first try

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 167 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-84f201e79/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 168 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6b2404c37/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 169 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e03998240/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 170 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9b04e4741/how-to/). valid for 14 days

**Comment by inflatador** [comment]
+1 , looks good to me

**Pull request merged**
