### PR TITLE
adds 2 articles to retired directory

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1157 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6e48de1a6/how-to/). valid for 14 days

**Comment by stephamon** [comment]
I always remove the `product` line also. I'm not sure if it'll not show up on the list if you leave it, but better safe than sorry!

**Comment by rackernexus** [comment]
Build 1158 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-be617d330/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1159 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-33d09f99d/how-to/). valid for 14 days

**Pull request merged**
