### PR TITLE
Style and broken links fixed

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by viridaria** [comment]
https://jira.rax.io/browse/INFODEV-6163

**Comment by catlook** [comment]
@viridaria review my edits and see if you agree!

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2123 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ec0054d7f/how-to/). valid for 14 days

**Comment by catlook** [comment]
I built it and tested the broken links.  they work now!

**Comment by catlook** [comment]
Is this ready to merge @viridaria ?

**Comment by viridaria** [comment]
@catlook yes, please, merge away. Sorry just now learned how to check messages.

**Pull request merged**
