### PR TITLE
Create migrating-the-cloud-backup-vault.md

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by WilliamLoy** [comment]
test

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
@BadCrumpany would you mind reviewing my changes? I moved quite a bit around and want to make sure it did not mess up the context of the instructions. Thanks

**Comment by rackernexus** [comment]
Build 1631 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f2055f796/how-to/). valid for 14 days

**Comment by BadCrumpany** [comment]
@WilliamLoy looks great to me.  Thanks for the work on it.  Have a great day!

**Pull request merged**
