### PR TITLE
Community Article - Securing Cloud Files CDN URL

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-f4790c7f55/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f1312a3d22/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8d44721d47/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-727ec3b985/how-to/).

**Comment by cyrichardson** [comment]
@catlook Suggestions here: 
[secure-cloud-files-and-cdn-urls_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2886143/secure-cloud-files-and-cdn-urls_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-83d9d06b47/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d4fefb8586/how-to/). :bow:

**Pull request merged**
