### PR TITLE
add alert logic to landing page

### PR DESCRIPTION
**Pull request by stephamon**
add the alert logic service offering to the landing page

### CODE REVIEW

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1698 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-27e67b66e/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1700 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-27e67b66e/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1704 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-27e67b66e/how-to/). valid for 14 days

**Pull request merged**
