### PR TITLE
[Audit] Updates to deploying wordpress with orchestration

### PR DESCRIPTION
**Pull request by RobinJoe**
Updating the How To steps after reviewing the menus and
options available in mycloud.

Addresses Issue rackerlabs/rackspace-how-to/issues/#1575

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-73f313449d/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-45451ec9da/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9fff17111e/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-914ed6431f/how-to/). :bow:

**Comment by DonNateR** [comment]
Merging now.

**Pull request merged**
