### PR TITLE
Upate verbiage as submitted by SME.

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by kylelaffoon** [comment]
@kmsholcomb This file has been completely re-written by the SME and needs an official edit.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon: I'll send edits later today.

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon: I gave article a thorough edit, and you can see my markup, suggestions, and questions in the attached Word doc (or the PDF copy of it). I made some structural recommendations to add more headings (two main and four sub under the second main), to break up the text. I had to move some text around a little make this work, but hopefully it all makes sense (and if it doesn't, I know you'll fix it!). I also had a question about a table that was in Shane's blog post and whether it should be included in the article. Please let me know if you have any questions or feedback. Thanks!

[Rackspace Monitoring Checks and Alarms_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/153241/Rackspace.Monitoring.Checks.and.Alarms_editsKH.pdf)
[Rackspace Monitoring Checks and Alarms_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/153242/Rackspace.Monitoring.Checks.and.Alarms_editsKH.docx)

**Comment by kylelaffoon** [comment]
Thanks @kmsholcomb. Your edits are now applied.

**Pull request merged**
