### PR TITLE
Wl export rse contacts

### PR DESCRIPTION
**Pull request by stephamon**
Takes over #2127

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @kmsholcomb can you edit this one too?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-42275de31d/how-to/).

**Comment by kmsholcomb** [comment]
You bet! I'll start now, finish after lunch.

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits are attached. Please let me know if you have any questions. Thanks!

[Import or export contacts in Rackspace Email_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1139782/Import.or.export.contacts.in.Rackspace.Email_editsKH.pdf)
[Import or export contacts in Rackspace Email_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1139783/Import.or.export.contacts.in.Rackspace.Email_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-45c424f730/how-to/)

**Pull request merged**
