### PR TITLE
Update linked list of DNS records

### PR DESCRIPTION
**Pull request by kylelaffoon**
Remove bold asterisks from level 4 headings and link.

### CODE REVIEW

**Comment by kylelaffoon** [comment]
- Fixes #1048

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3c88af30ca/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f6de8342fb/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-07e4935416/how-to/)

**Pull request merged**
