### PR TITLE
Add exp article: INFODEV-2573

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by RackerKate** [comment]
Replaces #2821.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6a505b8e51/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-2f54363b6f/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson For your review please.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Some suggestions here: 
[manually-enable-auto-updates-on-debian-ubuntu-14.04-and-16.04-public-cloud-servers_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2450996/manually-enable-auto-updates-on-debian-ubuntu-14.04-and-16.04-public-cloud-servers_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0e3dd2cc79/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6f782745b6/how-to/)

**Pull request merged**
