### PR TITLE
Add using-putty-to-access-private-instances.md

### PR DESCRIPTION
**Pull request by gfa**
Hello

Commonly we need to explain customers how to connect to their RDS instances from their workstation/laptops, I thought i could write a how-to and point them to the url :)

feel free to improve it or point what's wrong with it, i see it clear but i wrote it so....

### CODE REVIEW

**Comment by nimbinatus** [comment]
@gfa, thank you for the update! We will pull this into our sprints as soon as possible :)

**Comment by DonNateR** [comment]
Moving to Milestone 27 since this is a FAWS article.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-71a4c83c15/how-to/)

**Comment by gfa** [comment]
@DonNateR I dont know when Milestone 27 is, but i'd be great to have it published in some form. 
Every new customer we onboard has to pass through this

**Comment by DonNateR** [comment]
@gfa: I'm getting a couple of RPC devs in castle to help me build out this article a little more and make it more Rackspace specific. Milestone 27 means that the article has been added to our current Sprint, though I hope to have published by the end of the week. Is that ok for you?

**Comment by DonNateR** [comment]
@gfa: Also note that we won't have a FAWS section of How-To until March 7th. If you need this published before that date, let me know?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-947cb4cf93/how-to/)

**Comment by DonNateR** [comment]
@gfa: Do you have a timeline for when you need this published?

**Comment by gfa** [comment]
Hello @DonNateR 

no hard timelines, just would be useful to have.

**Comment by DonNateR** [comment]
@gfa: Are your instructions similar to what's documented here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html

**Comment by DonNateR** [comment]
@gfa: I apologize for not getting back to you sooner. After consulting with some members of the FAWS dev team, I've decided that this article isn't specific enough to Rackspace to warrant publication. If you wish to discuss this further or want to devise a way to get this information into another more FAWS specific article, email me at nate.archer@rackspace.com.

**Comment by DonNateR** [comment]
Moved to PR #1974

**Pull request closed without merging**
