### PR TITLE
updates to cbu linux deb

### PR DESCRIPTION
**Pull request by catlook**
originally from brett-johnson.  Pulled into this PR with my changes so it could be in a branch instead of direct to master.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-11d4e6608c/how-to/)

**Comment by cyrichardson** [comment]
@catlook Suggestions here: 
[install-or-update-the-cloud-backup-agent-on-linux_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1732930/install-or-update-the-cloud-backup-agent-on-linux_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7a3a4e8533/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c8f781f3b0/how-to/)

**Pull request merged**
