### PR TITLE
Add new PR for comm article (stuck after build based on an image) tha…

### PR DESCRIPTION
**Pull request by RackerKate**
…t includes the image to replace #3072.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-271306a1af/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[resolve-errors-after-building-a-server-from-a-saved-image_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2881039/resolve-errors-after-building-a-server-from-a-saved-image_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2fc891cc52/how-to/).

**Pull request merged**
