### PR TITLE
Audit using-swift-signal-resources-to-determine-status-for-cloud-orchestration-user-data-scripts.md: INFODEV-1270

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a5b9abb752/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-076aefe809/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-076aefe809/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson For your review please.

**Comment by cyrichardson** [comment]
@RackerKate, on it!

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[using-swift-signal-resources-to-determine-status-for-cloud-orchestration-user-data-scripts_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1965041/using-swift-signal-resources-to-determine-status-for-cloud-orchestration-user-data-scripts_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-de139e4cff/how-to/).

**Pull request merged**
