### PR TITLE
Audit firewall-manager-v2-port-groups: INFODEV-1279

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-06b084f839/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review. SME said it looks good - no changes.

**Comment by cyrichardson** [comment]
Thanks, @RackerKate. On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here 
[firewall-manager-v2-port-groups_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1830168/firewall-manager-v2-port-groups_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-00b960a2ce/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d038cfef3d/how-to/).

**Pull request merged**
