### PR TITLE
Removing outdated content - adding current RPC-V definitions

### PR DESCRIPTION
**Pull request by asettle**
We don't want any incorrect information about RPC-V to be published. This does not have to be merged today, but it would be better to publish this than outdated content.

I've got a meeting setup with the product manager for RPC-V, Dusten, to go through and collate a new document.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-312e384a0b/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-ae210d2ebd/how-to/). :bow:

**Comment by catlook** [comment]
Let me know when you're ready for a merge!

**Comment by catlook** [comment]
Per Alex, this blocked until 2/19

**Pull request closed without merging**
