### PR TITLE
Create Upgrading Apache 2.2 to 2.4 in RHEL 6/7 & CentOS 6/7

### PR DESCRIPTION
**Pull request by BadCrumpany**
Helping migrate articles from the community site to the support area

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-bef13dfb90/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d7c8022e0d/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b5212aef03/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-57d33707e7/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-24da96215f/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f11a467fdc/how-to/)

**Comment by RackerKate** [comment]
Replaced by https://github.com/rackerlabs/rackspace-how-to/pull/3053.

**Pull request closed without merging**
