### PR TITLE
Modify permalink

### PR DESCRIPTION
**Pull request by kylelaffoon**
from: differences-between-rackspace-intelligence-for-cloud-accounts-and-dedicated-accounts/
to: differences-between-rackspace-intelligence-for-cloud-account-and-dedicated-account/

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6be9c6c6eb/how-to/)

**Comment by kylelaffoon** [comment]
- Fixes #985

**Comment by ReneeRendon** [comment]
@kyle is changing the permalink to see if that change breaks anything with the article or the links pointing to the article. 

Where are the links coming from that point to this article?

**Comment by kylelaffoon** [comment]
Linked from https://support.rackspace.com/how-to/rackspace-intelligence/.

**Pull request merged**
