### PR TITLE
Audit cloud-images-faq: INFODEV-1286

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-04679a5633/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Yet another for your review.

**Comment by cyrichardson** [comment]
Will pick this one  up after the other one in the queue, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[cloud-images-faq_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1895690/cloud-images-faq_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-796338e90a/how-to/)

**Comment by cyrichardson** [comment]
In the queue, @RackerKate! (The day before a sprint closes is always a busy one!)

**Pull request merged**
