### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by csilva235**
Just a minor fix to formatting on the document,  The code block did not properly format under the line:

If you haven't configured any rules yet, the output looks similar to the following example:

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

### CODE REVIEW

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1919 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-aa080180d/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1921 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-aa080180d/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1922 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e3bd8e963/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1927 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e3bd8e963/how-to/). valid for 14 days

**Pull request merged**
