### PR TITLE
create granting-sudo-access-in-rhel-and-centos

### PR DESCRIPTION
**Pull request by csilva235**
Article for how to grant sudo/admin access in RHEL based distros. 

Article to be referenced in placeholder section of #3659

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1667 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-15a3c4026/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1672 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-94d92bead/how-to/). valid for 14 days

**Comment by catlook** [comment]
@csilva235 good?  https://support-revs.staging.deconst.org/build-94d92bead/how-to/grant-sudo-access-in-rhel-and-centos/

**Comment by csilva235** [comment]
@catlook  Sorry for the delay. Looks good to me! 

Thanks!

**Pull request merged**
