### PR TITLE
Install ssl cert

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-76f7cf715d/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-51c06f64c5/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1b3581df4b/how-to/)

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[install-an-ssl-certificate_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2507273/install-an-ssl-certificate_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7d12516e8f/how-to/)

**Pull request merged**
