### PR TITLE
full audit create server image

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 1652

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at this article? It might be fine. There weren't any SME changes to make.

**Comment by cyrichardson** [comment]
OK. Will do. Thanks, @stephamon!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-440fda026a/how-to/).

**Comment by cyrichardson** [comment]
Just formatting nits here, @stephamon:
[Create an image of a server and restore a server from a saved image_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2078108/Create.an.image.of.a.server.and.restore.a.server.from.a.saved.image_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-01e6c08324/how-to/).

**Pull request merged**
