### PR TITLE
Audit article post-migration-considerations-when-migrating-from-amazo…

### PR DESCRIPTION
**Pull request by RackerKate**
…n-web-services: INFODEV-2689

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-422aa7eb8a/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4954979fce/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson For your review please.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just 1 one suggestion: 
[post-migration-considerations-when-migrating-from-amazon-web-services_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2554799/post-migration-considerations-when-migrating-from-amazon-web-services_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-890ed860dc/how-to/)

**Pull request merged**
