### PR TITLE
Add tiered config article.

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #960 

-Needs review from @kmsholcomb

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6e1a1cb8af/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @DonNateR. I'll review it today.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. The attached PDf has my suggested edits. Please let me know if you have any questions. Thanks!

[Tiered configuration using load balancers_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/280365/Tiered.configuration.using.load.balancers_editsKH.pdf)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9bdbcaa36f/how-to/)

**Comment by stephamon** [comment]
Did we figure out how to get **svg** files to display? I guess we'll find out...

**Pull request merged**
