### PR TITLE
Migrations rse to hex

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-5893b9d1cb/how-to/)

**Comment by stephamon** [comment]
@kmsholcomb can you edit this please?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d877a8be74/how-to/)

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits are attached. Please let me know if you have any questions. Thanks!

[Rackspace Email to Microsoft Exchange migration_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1177467/Rackspace.Email.to.Microsoft.Exchange.migration_editsKH.pdf)
[Rackspace Email to Microsoft Exchange migration_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1177468/Rackspace.Email.to.Microsoft.Exchange.migration_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8fc073e313/how-to/)

**Pull request merged**
