### PR TITLE
full audit cloud backup best practices

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 2745

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at this article please?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-2772036be8/how-to/)

**Comment by cyrichardson** [comment]
Sure! On it, @stephamon.

**Comment by cyrichardson** [comment]
@stephamon Some suggestions here: 
[best-practices-for-cloud-backup_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2687693/best-practices-for-cloud-backup_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-dd35657d9c/how-to/)

**Pull request merged**
