### PR TITLE
New Article: Firewall manager v2 access-list theory and best practices

### PR DESCRIPTION
**Pull request by trevorbecker**
adding this to my PR list. 5th article of the week.
I am half complete with this. Needed to see the staging rendering so I am saving this now.
Will need editor review sometime tomorrow once i complete

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-5e831f92a3/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-af807f6886/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a22638edec/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3991bdf586/how-to/)

**Comment by stephamon** [comment]
@kmsholcomb Can you take a look at this one today? Sorry for the short notice!

**Comment by kmsholcomb** [comment]
Sure. I'll hop on it now.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9481c05677/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-024340ea6c/how-to/).

**Comment by kmsholcomb** [comment]
Edits are attached, Word and PDF copy. Please let me know if you have any questions. Thanks!

[Firewall Manager v2 access list theory and best practices_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/872863/Firewall.Manager.v2.access.list.theory.and.best.practices_editsKH.pdf)
[Firewall Manager v2 access list theory and best practices_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/872864/Firewall.Manager.v2.access.list.theory.and.best.practices_editsKH.docx)

**Comment by trevorbecker** [comment]
Hi, 
 
A very important topic was lost in translation of the review. Im in training so cant comment much on git. Can you please help?
 
I need the bold below updated please:
 
•         “Globally open (defining source of any over a port) only ports that are considered a generally accepted best practice. Examples of these ports **that should NOT be opened globally** are 22 - SSH, 1433 - Microsoft SQL, 3306 - MySQL, and 3389 - RDP.  ”

**Comment by kmsholcomb** [comment]
Ah. Sorry about that, Trevor. The numerous negatives in the sentence threw me off, and I misread the second sentence. I'll make sure Stephanie sees this!

**Comment by trevorbecker** [comment]
Thank you! I understand!

**Comment by stephamon** [comment]
Moved to #1941

**Pull request closed without merging**
