### PR TITLE
Full audit for CBS permission matrix

### LINKED ISSUE #1685: Full Audit: Permissions matrix for Cloud Block Storage
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-block-storage/permissions-matrix-for-cloud-block-storage.md

- [ ] SME review
- [x] Update formatting
- [ ] Editor review

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1685 

update formatting and match API method language to API reference guide

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-145d55ddb9/how-to/).

**Comment by stephamon** [comment]
Finally got the OK from Melissa, so the content is still up-to-date here.

**Comment by catlook** [comment]
👍

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b28b042b3a/how-to/). :bow:

**Pull request merged**
