### PR TITLE
Full audit of article on modifying your hosts file: INFODEV-1955

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-236b5ac532/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-807514f272/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ace75298c4/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate 1st thing on Monday.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[modify-your-hosts-file_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2324246/modify-your-hosts-file_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e7e04dfeb3/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5a8fbbd8fd/how-to/)

**Pull request merged**
