### PR TITLE
Initial edits to SSL articles.

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5b7ff2016d/how-to/).

**Comment by cyrichardson** [comment]
@catlook here are suggested changes for the 1st one: 
[installing-an-ssl-certificate-on-apache_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2229456/installing-an-ssl-certificate-on-apache_cyrEdits.docx)

**Comment by cyrichardson** [comment]
@catlook Second one here: 
[update-an-existing-ssl-certificate_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2229493/update-an-existing-ssl-certificate_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c0c3f509b8/how-to/)

**Pull request merged**
