### PR TITLE
[WIP] Full audit, issue #1665

### LINKED ISSUE #1665: Full audit: managed cloud service levels FAQ
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/managed-cloud-service-levels-faq.md
- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

### PR DESCRIPTION
**Pull request by nimbinatus**
proofing before SME review.

Fixes #1665.

Note: Article seems out of date and talking about "announcements" that have no reference.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-43cd0f413b/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-aa456dd176/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-126be2c04e/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-65d4e8481a/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3ecdc0963b/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9d6f3f6970/how-to/)

**Comment by nimbinatus** [comment]
@kmsholcomb , can you add this to your editing queue? Thanks!

**Comment by kmsholcomb** [comment]
Will look at it first thing in the AM, @nimbinatus.

**Comment by nimbinatus** [comment]
@kmsholcomb, sorry, can you hold off on editing this one? We're reviewing whether it's worth having on our site in this form. Thanks!

**Comment by nimbinatus** [comment]
@kmsholcomb, can you add this one to your editing queue? It should be ready now :) Thanks!

**Comment by kmsholcomb** [comment]
Will do, @nimbinatus.

**Comment by kmsholcomb** [comment]
Hi, @nimbinatus. My edits are in the attached docs. Please let me know if you have any questions, or can answer any of mine! :)

[Managed Public Cloud service levels FAQ_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/781192/Managed.Public.Cloud.service.levels.FAQ_editsKH.pdf)
[Managed Public Cloud service levels FAQ_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/781191/Managed.Public.Cloud.service.levels.FAQ_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d96ecb8e62/how-to/)

**Comment by nimbinatus** [comment]
Closing PR and reopening to fix some things with the rebase

**Pull request closed without merging**
