### PR TITLE
Create windows-guide-to-resource-monitoring

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 1759 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0ded65bfe/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1772 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0896ea6fb/how-to/). valid for 14 days

**Pull request merged**
