### PR TITLE
migrate install ssl certificates on windows server article as per req…

### LINKED ISSUE #604: Missing Article: installing-ssl-certificates-on-windows-server-2008r2-and-2012
Will it be possible to republish the article from http://www.rackspace.com/knowledge_center/article/installing-ssl-certificates-on-windows-server-2008r2-and-2012?

### PR DESCRIPTION
**Pull request by stephamon**
…uest

Fixes #604 

This may need an SME's eyes to make sure all the steps are still correct and up-to-date.

### CODE REVIEW

**Comment by DonNateR** [comment]
LGTM. Don't think this needs a SME. A Kelly Holcomb pass through will probably clean up the language a little bit.

**Comment by stephamon** [comment]
Awesome, thanks! @kmsholcomb can you add this one to your list as well?

**Comment by kmsholcomb** [comment]
Sure @stephamon! Thanks for keeping me busy today! :)

**Comment by kmsholcomb** [comment]
Hi @stephamon: It looked pretty clean to me, but I did have some copy edits. See the attached Word doc (or PDF copy). Let me know if you have any questions. Thanks!

[Install SSL certificates on Windows Server 2008 R2 and 2012 servers_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/169861/Install.SSL.certificates.on.Windows.Server.2008.R2.and.2012.servers_editsKH.pdf)
[Install SSL certificates on Windows Server 2008 R2 and 2012 servers_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/169862/Install.SSL.certificates.on.Windows.Server.2008.R2.and.2012.servers_editsKH.docx)

**Pull request merged**
