### PR TITLE
New Article: Firewall manager v2 object-groups

### PR DESCRIPTION
**Pull request by DonNateR**
From PR #1923.

- Incorporated Kelly's edits

- Add images for final preview and merge

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-fb67034bf7/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3a64243bd4/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-03200a83cb/how-to/).

**Comment by stephamon** [comment]
👍

**Comment by stephamon** [comment]
@DonNateR I didn't notice this yesterday, but can you change `type` in the metadata from product to article?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-733af25f54/how-to/)

**Pull request merged**
