### PR TITLE
Audit Migrate a net app from AWS: InfoDev 2393

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9b99085c4e/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review. This one should be quick.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5d3b82d780/how-to/).

**Pull request merged**
