### PR TITLE
Create floating-ip-faq

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by kylelaffoon** [comment]
- Fixes #872 
Discuss with Jorge miramontes on May 1st.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6911aedad0/how-to/).

**Comment by kmsholcomb** [comment]
Hi @kylelaffoon. The attached Word doc (and PDF copy of it) contains my suggested edits. Please let me know if you have any questions. Thanks!

[Floating IP address FAQ_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/286973/Floating.IP.address.FAQ_editsKH.pdf)
[Floating IP address FAQ_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/286972/Floating.IP.address.FAQ_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-71a38c7406/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0fa2503b64/how-to/)

**Pull request merged**
