### PR TITLE
Create windows-low-memory-diagnostics

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1765 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fd3dff286/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1766 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fd3dff286/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1767 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a06efdcc4/how-to/). valid for 14 days

**Pull request merged**
