### PR TITLE
updated experience instructions

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 335 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0129dd6d8/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 344 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0129dd6d8/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
looks good!

**Comment by rackernexus** [comment]
Build 349 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-10cb595af/how-to/). valid for 14 days

**Pull request merged**
