### PR TITLE
add initial alert logic content

### PR DESCRIPTION
**Pull request by stephamon**
new content for RMS alert logic service offering

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1342 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b92cdc065/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1344 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e549f0923/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1504 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ce29973ba/how-to/). valid for 14 days

**Comment by stephamon** [comment]
moved to #3618

**Pull request closed without merging**
