### PR TITLE
Audit rackspace-standard-and-non-standard-images.md: INFODEV-1283

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ace45fc171/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-712e89cad3/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Last one of this group for your review. Thanks!

**Comment by cyrichardson** [comment]
Thanks, @RackerKate! In the review queue!

**Comment by cyrichardson** [comment]
@RackerKate No suggested changes for this one. I also checked the links via staging - no broken links.

**Pull request merged**
