### PR TITLE
Unmount

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1038 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-304c0475f/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
@cyrichardson what Vale files are referring to?

**Comment by cyrichardson** [comment]
In addition to the how-to file, I see 4 more files in the Files changes area:
_assest/vale/.vale.ini
_assets/vale/styles/rackspacestyles/chadstyle.yml
_assets/vale/styles/rackspacestyles/exchange.yml
_assets/vale/styles/rackspacestyles/teststyle.yml
I figure these must be coming from Vale processing??? But I'm not sure.

**Comment by Sterling463** [comment]
I think I may have accidentally added them and those changes were me removing from those files. Vale shouldn't be creating files anywhere else.

**Comment by cyrichardson** [comment]
Ah... got it. Thanks for letting me know!

**Comment by catlook** [comment]
@Sterling463 is this ready to go now?

**Pull request merged**
