### PR TITLE
Add swiftly link to article.

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 825 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-54ecd1653/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 833 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b70cea10b/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 837 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-95415617c/how-to/). valid for 14 days

**Pull request merged**
