### PR TITLE
full audit revisions

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b4b74f265f/how-to/)

**Comment by WilliamLoy** [comment]
@cyrichardson please review changes :)

**Comment by cyrichardson** [comment]
@WilliamLoy Suggested changes here: 
[set-up-rackspace-email-forwarding_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2742739/set-up-rackspace-email-forwarding_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-89b04233f1/how-to/)

**Pull request merged**
