### PR TITLE
Add community article on reboots: INFODEV-3256

### PR DESCRIPTION
**Pull request by RackerKate**
Replaces #3048

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a6961df889/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just a few suggestions: 
[ensure-servers-reboot-successfully_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2780371/ensure-servers-reboot-successfully_cyrEdits.docx)

**Pull request merged**
