### PR TITLE
New article: Upgrade to Rackspace Email Plus

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by nimbinatus** [comment]
FYI: The staging system is still down.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3e9ec646c1/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Would it be possible to get a current preview (Strider is fixed now, right)?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6d7c4b4953/how-to/). :bow:

**Comment by DonNateR** [comment]
@kmsholcomb: You should have the preview now.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits attached. Please let me know if you have any questions. Thanks!

[Upgrade to Rackspace Email Plus_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1163536/Upgrade.to.Rackspace.Email.Plus_editsKH.docx)
[Upgrade to Rackspace Email Plus_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1163537/Upgrade.to.Rackspace.Email.Plus_editsKH.pdf)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6f8d27895a/how-to/).

**Comment by stephamon** [comment]
👍

**Pull request merged**
