### PR TITLE
changed title and edits

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a521455eb0/how-to/). :bow:

**Comment by WilliamLoy** [comment]
@cyrichardson  got one ready for ya :)

**Comment by cyrichardson** [comment]
@WilliamLoy On it.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a85cbff925/how-to/). :bow:

**Comment by cyrichardson** [comment]
@WilliamLoy Editorial changes applied - see this commit for changes: https://github.com/rackerlabs/rackspace-how-to/pull/3242/commits/5df1a15893d924e73775f255ae16455ac066bf75

**Comment by WilliamLoy** [comment]
Looks good

**Pull request merged**
