### PR TITLE
Community Cloud Imaging

### PR DESCRIPTION
**Pull request by catlook**
Jira INFODEV-3152

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2ec479dd56/how-to/)

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[understanding-the-cloud-imaging-process_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2777488/understanding-the-cloud-imaging-process_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-371c9a5895/how-to/). :bow:

**Pull request merged**
