### PR TITLE
Create cloud-office-mfa-app-guide.md

### PR DESCRIPTION
**Pull request by rsnick**
New article outlining the setup process for mobile and desktop authentication applications when logging into cp.rackspace.com

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 2206 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-60150f7cd/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@catlook ready for edits :)

**Comment by WilliamLoy** [comment]
@catlook if ya get a chance to take a look at this one I'd appreciate it. Thanks!

**Comment by catlook** [comment]
GOOD GRIEF!!!!  Sorry to keep you waiting, I never saw the notify

**Comment by catlook** [comment]
@WilliamLoy Please review my edits and see if you agree.  Again, sorry for the delay.

**Pull request merged**
