### PR TITLE
INFODEV-1589

### PR DESCRIPTION
**Pull request by WilliamLoy**
Article has been reviewed by SME. Ready for editor review @cyrichardson :)

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by cyrichardson** [comment]
@WilliamLoy On it.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3e8b68e06f/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a1b3642dd4/how-to/)

**Pull request merged**
