### PR TITLE
IAD DC migration

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bb5bc9c6af/how-to/).

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[iad2-data-center-migration-customer-faq_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2416813/iad2-data-center-migration-customer-faq_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7b281cea9f/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d01b040d3f/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-02b6e9aa6e/how-to/)

**Pull request merged**
