### PR TITLE
[MVP] Rackspace Migration Manager - add all.md file

### LINKED ISSUE #1868: [MVP] Rackspace Migration Manager: Add all.md file
FAWS tab on How-To landing page will not to live until release currently scheduled on 3/7

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #1868 

This PR replace PR #1869 - moved from FAWS folder to rackspace-migration-manager folder

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-93bbad5184/how-to/).

**Comment by cyrichardson** [comment]
Moving to blocked status until product launch.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e1e9a9a873/how-to/)

**Comment by cyrichardson** [comment]
Ready for MVP launch

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424

**Pull request closed without merging**
