### PR TITLE
change account owner

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-10e01372fc/how-to/).

**Comment by cyrichardson** [comment]
@catlook Suggestions here: 
[change-account-owner_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/3009322/change-account-owner_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-eb540662bc/how-to/)

**Pull request merged**
