### PR TITLE
initial full audit changes

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-53e82790a3/how-to/)

**Comment by Indrapal2512** [comment]
+1 Looks good to me.

**Comment by Indrapal2512** [comment]
+1 Looks good to me.

**Comment by catlook** [comment]
Thanks!!

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[rackspace-cloud-backup-backup-actions_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2166763/rackspace-cloud-backup-backup-actions_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-d368509a38/how-to/)

**Pull request merged**
