### PR TITLE
Delete a user from the Customer Portal

### PR DESCRIPTION
**Pull request by chri2547**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-30490e0274/how-to/). :bow:

**Comment by cyrichardson** [comment]
@chri2547 Suggested changes here: 
[delete-users_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2325453/delete-users_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-07061542ba/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-225fc1879d/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-907444484b/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-47e2b4a34b/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-47e2b4a34b/how-to/). :bow:

**Pull request merged**
