### PR TITLE
new kernel updated

### PR DESCRIPTION
**Pull request by RSroblee**
updated Public site with updated CS kernels.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1379 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-16701acfe/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1383 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6741f4746/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1384 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-877a7d050/how-to/). valid for 14 days

**Comment by RSroblee** [comment]
Let it rip.  Thanks.
Rob

**Pull request merged**
