### PR TITLE
Made updates to several "general" how-to articles

### PR DESCRIPTION
**Pull request by kmsholcomb**
As part of https://github.com/rackerlabs/rackspace-how-to/issues/705, I've copy edited 18 articles (two are in different categories, but are related). I also deleted five images. In addition, I had the following questions/suggestions about two of the articles:

- I think we can delete https://support.rackspace.com/how-to/cloud-hosting-faq/. The first Q&A is duplicated in https://support.rackspace.com/how-to/what-is-an-soa-record/ (which I edited as part of this PR), and the second is not particularly relevant to customers.

- https://support.rackspace.com/how-to/comparison-of-dedicated-and-cloud-hosting/: The Backups info is basically the same for Managed Operations and Infrastructure. I'm sure that there is some difference, though. I would recommend revising each description to ensure it is accurate.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-48c88e6dd4/how-to/)

**Comment by kmsholcomb** [comment]
FYI, I tried to fix the table in https://support.rackspace.com/how-to/permissions-matrix-for-cloud-load-balancers/, but I don't think it worked.

**Comment by DonNateR** [comment]
@kmsholcomb: We can delete the Cloud Hosting FAQ and keep the other article.

**Comment by kmsholcomb** [comment]
Sounds good.

**Comment by kmsholcomb** [comment]
I goofed and added another commit to this branch. I'll start updating again in another branch so that this PR can get merged.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-95d4b98c17/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d3f880342e/how-to/).

**Comment by DonNateR** [comment]
@kmsholcomb: Working on fixing the table. Feel free to keep updating this PR if you would like.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-507766ffa4/how-to/)

**Comment by DonNateR** [comment]
@kmsholcomb: I am going to go ahead and merge this PR.

**Pull request merged**
