### PR TITLE
Update managing-cloud-databases-ha-groups-in-the-cloud-control-panel.md

### PR DESCRIPTION
**Pull request by kylelaffoon**
Delete unneeded images and modify text accordingly.

### CODE REVIEW

**Comment by kylelaffoon** [comment]
- Relates to #705

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3eeb1791f2/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-de2fc19c28/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-db60554e32/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-f043b8a93b/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3a3043cf34/how-to/)

**Pull request merged**
