### PR TITLE
Update steps and add new example for group-group mapping: INFODEV-3146

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-558009b1e8/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9806f71bc5/how-to/)

**Comment by jlundy** [comment]
We might add another comment on new lines 422-424 to also say if you need access to the api to do this, contact your AM.  Most customers don't have access to the api.

**Comment by jlundy** [comment]
One thing to note Kate, is that while we are removing all these roles things for now, we will be able to add this back in in the future which should allow us to make this doc work for both cloud and dedicated federation once dedicated permissions are moved into Identity.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1bebb0d560/how-to/)

**Comment by BryanSD** [comment]
👍

Mostly was just looking for the mapping to groups instead of roles, I think this is pretty clear.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a3548ad3ad/how-to/)

**Pull request merged**
