### PR TITLE
[WIP] How to build HEAT Orchestration Templates

### PR DESCRIPTION
**Pull request by aaronmehar**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-5f49f0304a/how-to/). :bow:

**Comment by aaronmehar** [comment]
Hey All.

There are some formatting issues in preview, like code blocks.. they appear OK in Github preview and a few markdown preview engines I used.. is this something I need to correct for Nexus, or would this be OK in production?

**Comment by DonNateR** [comment]
@aaronmehar: I'm going to look over the formatting and make sure that everything will be compatible with Nexus.

**Comment by aaronmehar** [comment]
thanks @DonNateR

**Comment by DonNateR** [comment]
@aaronmehar: Did you wish to have this article published on October 9th?

**Comment by aaronmehar** [comment]
sounds good to me @DonNateR gives enough in case I need to make any edits/corrections

**Comment by DonNateR** [comment]
@aaronmehar: The reason I ask is because you put October 9th as the `created-date` in the metadata for the article. Would we be able to publish the article as soon as the next couple of weeks, or is this article timed with a specific release?

**Comment by aaronmehar** [comment]
Ah.. I think this date confusion between US and UK again :) that was August 10th when I started it.. But regardless, there is not set date for this article, nothing to time it with.. I am flexible and happy with any date.

**Pull request merged**
