### PR TITLE
Create deleting-downloaded-windows-updates

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1856 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7a88da908/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1858 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fedd16552/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1860 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ea8ba5b87/how-to/). valid for 14 days

**Pull request merged**
