### PR TITLE
Add community article. Replaces #3034.

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2e54150692/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4b8c7d43ea/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[add-a-cloud-network-interface-to-a-cloud-server_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2779554/add-a-cloud-network-interface-to-a-cloud-server_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b475b4a9f0/how-to/)

**Pull request merged**
