### PR TITLE
Add disclaimer for flavor types

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a4b6fc6069/how-to/)

**Comment by cyrichardson** [comment]
@BadCrumpany Please review my editorial changes and provide any feedback that you have. Thanks!

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5e38728517/how-to/)

**Comment by BadCrumpany** [comment]
Looks great, thanks!

**Pull request merged**
