### PR TITLE
[WIP] Adding a tab for dedicated hosting

### PR DESCRIPTION
**Pull request by kenperkins**
Do not merge.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cdc5d02f2b/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e2cbca2400/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-50add294f8/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-98ff72dddd/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a44d998a55/how-to/)

**Comment by kenperkins** [comment]
@stephamon merge at your leisure.

**Comment by stephamon** [comment]
Content is up, merging for the button.

**Pull request merged**
