### PR TITLE
Wl renamed email mac11

### PR DESCRIPTION
**Pull request by stephamon**
takes over #2217

### CODE REVIEW

**Comment by stephamon** [comment]
Hi @kmsholcomb can you edit this one as well? Thanks!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5e4a0f7230/how-to/).

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits are attached. Thanks!

[Configure a renamed email address on Outlook for Mac_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1300479/Configure.a.renamed.email.address.on.Outlook.for.Mac_editsKH.docx)
[Configure a renamed email address on Outlook for Mac_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1300480/Configure.a.renamed.email.address.on.Outlook.for.Mac_editsKH.pdf)

**Comment by kmsholcomb** [comment]
Hi @stephamon. Final edits are attached (I attached them a minute ago and then caught something I missed). Thanks!

[Configure a renamed email address on Outlook for Mac_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1300492/Configure.a.renamed.email.address.on.Outlook.for.Mac_editsKH.pdf)
[Configure a renamed email address on Outlook for Mac_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1300493/Configure.a.renamed.email.address.on.Outlook.for.Mac_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cd87d546a4/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-18c86a3049/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-97a54c3bb3/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-42ce9a2e34/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d464b45aa2/how-to/).

**Pull request merged**
