### PR TITLE
[WIP] Full audit, ref: issue #1660

### LINKED ISSUE #1660: Full audit: RPC spheres of support
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rpc-openstack/rackspace-private-cloud-spheres-of-support.md

- [ ] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

### PR DESCRIPTION
**Pull request by nimbinatus**
fixing typos and HTML before sending to SME. See #1660 for issue details.

Fixes #1660

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-afc049d1ea/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c6aad0fc70/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f87fcf90f6/how-to/)

**Comment by nimbinatus** [comment]
ref rackerlabs/nexus-control#648

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4413b80b10/how-to/)

**Pull request merged**
