### PR TITLE
Update link to community post

### PR DESCRIPTION
**Pull request by cyrichardson**
about outbound security groups.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-910ca8dc8f/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-17c5de002b/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c598fd9e49/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c598fd9e49/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0af952eccb/how-to/)

**Comment by dapriest** [comment]
The added info into the FAQ looks perfect this should help customers understand without having to do too many clicks from page to page.

**Pull request merged**
