### PR TITLE
Initial full audit updates

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by catlook** [comment]
@Indrapal2512 Could you check this one for me, too?  I'm very grateul!!

**Comment by cyrichardson** [comment]
@catloook Note - the first link in the article gives me a 404- Install the Cloud Backup agent on Linux

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ef2222a4ed/how-to/)

**Comment by catlook** [comment]
the link works in production - it's valid.  might be a staging thing....

**Pull request merged**
