### PR TITLE
Sitecore: New article: Clear Sitecore cache 

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f680a23997/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-debfb2fee3/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c2558729fb/how-to/).

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits are attached. Please let me know if you have any questions. Thanks!

[Clear your Sitecore caches_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1056087/Clear.your.Sitecore.caches_editsKH.pdf)
[Clear your Sitecore caches_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1056088/Clear.your.Sitecore.caches_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7690eaedf6/how-to/)

**Pull request merged**
