### PR TITLE
Create migrate-a-cloud-server-to-a-new-physical-host

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2284 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-caa9f55e2/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2286 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-caa9f55e2/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 2287 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c281df8b2/how-to/). valid for 14 days

**Comment by catlook** [comment]
author approved.

**Pull request merged**
