### PR TITLE
Create how-to-run-chkdsk-in-windows

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1643 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-308d6a521/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1644 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-308d6a521/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1645 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-961d33aa1/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1646 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-961d33aa1/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1647 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-961d33aa1/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1648 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e817b0340/how-to/). valid for 14 days

**Pull request merged**
