### PR TITLE
Audit mysql connect: infodev-2557

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9bb5054e50/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e89aad1340/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review. You reviewed this the other day for a Jellyfish edit, but this is the full audit. Thanks.

**Comment by cyrichardson** [comment]
On it @RackerKate.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f19ae1d10e/how-to/)

**Pull request merged**
