### PR TITLE
Add comm article about firewalls: INFODEV-3288

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by RackerKate** [comment]
Replaces #3129 due to build issue.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[introduction-to-firewalls_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2793219/introduction-to-firewalls_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-6a3cdfacb8/how-to/)

**Pull request merged**
