### PR TITLE
Add SOS expansion content

### PR DESCRIPTION
**Pull request by hdansou**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2152 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-023ea2ce2/how-to/). valid for 14 days

**Comment by catlook** [comment]
Honsou approved by email on 7/20.  Delay publish until 8/11.

**Comment by hdansou** [comment]
@catlook We have made some ammendment. Please review the format before merging. Thank you.

**Pull request merged**
