### PR TITLE
Create create-sudo-user-in-centos

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1809 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-dcde3cd0b/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1810 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-dcde3cd0b/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1811 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-66414fa2b/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1812 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-66414fa2b/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1813 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6cf99cd19/how-to/). valid for 14 days

**Pull request merged**
