### PR TITLE
Community Article - 3-2-1 Backup Rule for the Cloud: INFODEV-3426

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c3941063ce/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-fad387df8b/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a841191874/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[3-2-1-backup-rule-for-the-cloud_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2822779/3-2-1-backup-rule-for-the-cloud_cyrEdits.docx)

**Comment by WilliamLoy** [comment]
Looks good to me.

**Pull request merged**
