### PR TITLE
Updated wildcard info

### PR DESCRIPTION
**Pull request by hikarutilmitt**
Updates the article to correct mention the status of installing Wildcard certificates in Cloud Sites, as there was conflicting information and steps were missing to ensure proper installation.

Examples will be added soon.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-dd37016aa4/how-to/)

**Comment by DonNateR** [comment]
@hikarutilmitt: Would you like me to merge your changes or wait until you have added examples?

**Comment by hikarutilmitt** [comment]
I'm working on the examples right now, actually. We can wait until then. Thanks.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9c454d7787/how-to/)

**Comment by hikarutilmitt** [comment]
It should be good to go, now. Last edits that should need to be made have been.

**Comment by DonNateR** [comment]
Opened a new PR #1013  with grammar updates. Will merge once the build is ready.

**Pull request closed without merging**
