### PR TITLE
Community Article - Installing and Configuring vsFTPD

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5820230d95/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e3119ca3f8/how-to/)

**Comment by stephamon** [comment]
@cyrichardson will you take a look at this please? I suspect there are a few more places where it could use some more information!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e3119ca3f8/how-to/).

**Comment by cyrichardson** [comment]
On it, @stephamon.

**Comment by cyrichardson** [comment]
@stephamon Suggestions here: 
[installing-and-configuring-vsftpd_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2928564/installing-and-configuring-vsftpd_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-cc718b7a21/how-to/)

**Pull request merged**
