### PR TITLE
Create managing-packages-in-rhel-based-distributions

### PR DESCRIPTION
**Pull request by csilva235**
New document that covers package management with yum in RHEL distros.

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1930 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b61598b87/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1933 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9f645fc56/how-to/). valid for 14 days

**Comment by catlook** [comment]
manage-packages-in-rhel-based-distributions

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1937 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c80144d88/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1939 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f0f713ba6/how-to/). valid for 14 days

**Pull request merged**
