### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kylelaffoon**
Add TOC for Issue #1302

### CODE REVIEW

**Comment by ReneeRendon** [comment]
@kylelaffoon 
In the "view" mode, these anchors do not work. I don't know if it is because of the mode or because it may need to look more like the following.

- [Create a fork of this repository](#Create-a-fork-of-this-repository)

**Comment by ReneeRendon** [comment]
Two of the anchors do not work. 
- Writing Guidelines 
- Creating and changing...

**Comment by kylelaffoon** [comment]
@ReneeRendon Thanks. I corrected those items.

**Comment by kylelaffoon** [comment]
@ReneeRendon Did this need additional changes? Or can it be merged?

**Pull request merged**
