### PR TITLE
Create using-windows-performance-analyzer-to-troubleshoot-performance…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…-issues

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2131 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-150c7872b/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2133 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-499a4e852/how-to/). valid for 14 days

**Comment by catlook** [comment]
Shaun approved.

**Pull request merged**
