### PR TITLE
remove extra bar from table row

### PR DESCRIPTION
**Pull request by stephamon**
A couple of the tables had an extra bar in one of the cells, causing some problems when published. Also adding an extra blank line to force more separation between tables.

### CODE REVIEW

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1664 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5299d4b1d/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1666 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b105be0c3/how-to/). valid for 14 days

**Pull request merged**
