### PR TITLE
Minor grammar and formatting fixes

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9e8122e43e/how-to/)

**Comment by DonNateR** [comment]
@cyrichardson: do you know if anyone on the vmWare dev team has review this article recently?

**Comment by cyrichardson** [comment]
I don't know that they have. I was reviewing it to become familiar with the service and just notices some typos and such. I know that the vmware team has a list of to do's, including rebranding. I would expect them to look through all of the existing docs in the course of that. @DonNateR

**Comment by DonNateR** [comment]
@cyrichardson: Good to know. I'll go ahead and merge.

**Pull request merged**
