### PR TITLE
INFODEV-2965 Full Audit

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ee0ca6cf40/how-to/).

**Comment by cyrichardson** [comment]
@WilliamLoy On it now.

**Comment by cyrichardson** [comment]
@WilliamLoy Suggested changes here: 
[imap-and-pop-mail-protocol-comparison_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2764508/imap-and-pop-mail-protocol-comparison_cyrEdits.docx)

Please let me know if you any questions.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5ed44f77ac/how-to/)

**Pull request merged**
