### PR TITLE
Create what-caused-windows-server-shutdown

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1760 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ac680d889/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1761 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ac680d889/how-to/). valid for 14 days

**Pull request merged**
