### PR TITLE
Update modify-your-hosts-file.md

### PR DESCRIPTION
**Pull request by joeashcraft**
Instructions are still valid for latest MacOS 10.12

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a1a0888500/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9445ce006e/how-to/). :bow:

**Comment by joeashcraft** [comment]
[this](https://staging.developer.rackspace.com/support.rackspace.com/build-9445ce006e/how-to/modify-your-hosts-file) preview looks good!

**Comment by nimbinatus** [comment]
Thanks for the update, @joeashcraft! LGTM, +1

**Comment by nimbinatus** [comment]
Fixes #1912

**Pull request merged**
