### PR TITLE
New article: Modify an object group

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e3ec6044ff/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-efa3374a8f/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-efa3374a8f/how-to/).

**Comment by cyrichardson** [comment]
@DonNateR Just a couple of suggested changes int 
[modify-an-object-group-with-firewall-manager-v2_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2190679/modify-an-object-group-with-firewall-manager-v2_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-352b05845f/how-to/)

**Pull request merged**
