### PR TITLE
move to servers folder, add link to nginx documentation on installing…

### LINKED ISSUE #1277: On boarding doc suggestion - How-To apply SSL cert to NGINX
Relates to #1264 
SME: Yesenia Ceja
Request list: https://one.rackspace.com/pages/editpage.action?pageId=174901302

Need article on How to apply SSL cert to NGINX.

### PR DESCRIPTION
**Pull request by stephamon**
… ssl certs

Fixes #1277 

The instructions on installing a SSL certificate vary depending on from where you got the certificate, so I've included a note with a link to NGINX's documentation on the subject.

Also, the file was located in the Cloud Files folder rather than Servers, so I've moved it.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d7e077878d/how-to/)

**Comment by kylelaffoon** [comment]
@stephamon The nginx steps look good. Thanks for solving this mystery.
The numbering is off for the earlier step "1. After you have logged in to the primary server, modify /home/parse/ecosystem.json with your..."
Indent the additional information paragraph to get this to continue as "2. After you have logged in to the primary server, modify /home/parse/ecosystem.json with your.."

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7d77170a61/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-508100fbdf/how-to/)

**Comment by kylelaffoon** [comment]
Looks perfect.

**Pull request merged**
