### PR TITLE
Updated WSUS Endpoint for Windows cloud servers

### PR DESCRIPTION
**Pull request by hdansou**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
Build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 843 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-93fe06aaa/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 896 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-93fe06aaa/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Looks good to me.  @hdansou sorry for the delay. There have been problems with the publishing platform but things are stable now. Publishing to production now.

**Pull request merged**
