### PR TITLE
Community Article - What Sort of Things Does Rackspace Do In The Cloud?

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5ac42fa599/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-83c9a51cfe/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-efac50f287/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e719afc849/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review. I will add a better link if possible when marketing gets back to me.

**Comment by cyrichardson** [comment]
@RackerKate OK. On it!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1a74e1f61d/how-to/).

**Pull request merged**
