### PR TITLE
FAWS: New article: Access a private RDS instance with Putty

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes issue #1880  

Content taken from PR #1861

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4f5d1e83c5/how-to/)

**Comment by DonNateR** [comment]
@gfa: Here's the edits to your article that we discussed a could of weeks ago. I also have a few questions to make sure the article is accurate as possible?

- Where in the FAWS control panel can users find the hostname of their RDS instance?

- What Source Port should a user use if they are no using a MySQL appliance?

**Comment by gfa** [comment]
Hello
sorry @DonNateR  i was in garden leave. 

regarding your questions

- there is no way to find out the RDS hostname from the FAWS control panel, we do provide that information to customers in the handover ticket

- the source port should be the port of the application the user wants to access, 3306 for MySQL, 11211 for memcached, 6379 for redis, etc

one thing, is not a MySQL *appliance* that you run on your workstation but an **application**

**Comment by DonNateR** [comment]
Waiting for a review from the AWS team. Not sure whether to move this to blocked or not.

**Comment by DonNateR** [comment]
Directed to hold off on this until we've determined a content strategy for FAWS.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ae1cfa8079/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-038ca6908a/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e1cc1ad6f1/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e1cc1ad6f1/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-48452d8753/how-to/)

**Pull request merged**
