### PR TITLE
Audit adding mgd ops: INFODEV-2395

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3aff186ac9/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
This is next in today's queue for me.

**Comment by cyrichardson** [comment]
@RackerKate Just a few suggestions: 
[adding-a-managed-operations-service-level-to-your-cloud-account_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2372004/adding-a-managed-operations-service-level-to-your-cloud-account_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3a4ac43f74/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-01604e310e/how-to/)

**Pull request merged**
