### PR TITLE
Create dns-basics

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1845 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9532cda2d/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1849 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8dae5441b/how-to/). valid for 14 days

**Pull request merged**
