### PR TITLE
Create storage-notification.md

### PR DESCRIPTION
**Pull request by hikarutilmitt**

### CODE REVIEW

**Comment by nimbinatus** [comment]
Opened PR on the patch-17 branch, hikarutilmitt/rackspace-how-to#5

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5b321134bc/how-to/)

**Comment by nimbinatus** [comment]
Opened a second PR on the patch-17 branch, hikarutilmitt/rackspace-how-to#13

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d7cee4ebc1/how-to/)

**Pull request merged**
