### PR TITLE
Sitecore: New article: Add a CDN to Sitecore

### PR DESCRIPTION
**Pull request by DonNateR**
Need additional content before the article can be reviewed.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-da6796b984/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-21291f86e0/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dac6750089/how-to/)

**Comment by DonNateR** [comment]
Waiting on SME to write missing section of this article.

**Pull request closed without merging**
