### PR TITLE
Retire Cloud Big Data articles

### PR DESCRIPTION
**Pull request by catlook**
partially closes issue #1976 (rest will be nexus)

Deleted CBD content and assists dir
removed from index.md
removed from products csv

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-685db2fb48/how-to/)

**Comment by stephamon** [comment]
@catlook since BD is going away forever, should we go ahead and delete the image file for it as well?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3e3863376e/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e4d1708d0b/how-to/). :bow:

**Comment by stephamon** [comment]
👍

**Pull request merged**
