### PR TITLE
Add article to troubleshoot error provided-host-name-not-valid

### PR DESCRIPTION
**Pull request by cyrichardson**
Requested by Shaun Crumpler

### CODE REVIEW

**Comment by cyrichardson** [comment]
@BadCrumpany Do you like to review in the PR in GitHub, or would you prefer that I send the drafted article for your review another way. Thanks!

**Comment by cyrichardson** [comment]
@BadCrumpany Is the category in the file correct? Is this article for cloud-servers? If not, just let me know where you it to reside on support.rackspace.com. Thanks!

**Comment by rackernexus** [comment]
Build 679 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d2db7537e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 680 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3fcb3b4d6/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 789 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b510e3532/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@BadCrumpany Here's the staging link for this one - Please let me know if this one is ready to go: https://support-revs.staging.deconst.org/build-b510e3532/how-to/troubleshooting-provided-host-name-not-valid/

**Comment by BadCrumpany** [comment]
Hi @cyrichardson!  I spoke to a few Linux Admins and the consensus was that most did not know if this was correct or not.  I finally spoke to one that knew about it but thinks that it needs to be prefaced with something along the lines of "Make sure that you understand your environment as this may not be suitable for all setups and/or configurations".  But, he said that it does make sense and would work under many circumstances.  I would likely also add that it is always recommended that the customer have a backup before making any types of changes to the system so that they have the ability to revert if needed.  Hope this helps!

**Comment by cyrichardson** [comment]
@BadCrumpany Thank you! I'll make the changes and send this back for your review.

Is cloud servers the right place for this article on support.rackspace.com?

**Comment by cyrichardson** [comment]
@BadCrumpany Thank you! I've made the changes suggested for your review.
Is cloud servers the right place for this article on support.rackspace.com?

Here is the text I added at the end of the introduction:

**Warning:** Before you use these troubleshooting instructions, make sure that you understand your environment as these troubleshooting steps might not be suitable for all setups or configurations. Also, we recommend that you make a backup before making any changes to your system so that you have the ability to revert changes if needed.

**Comment by cyrichardson** [comment]
@BadCrumpany Please let me know when you review this and if this PR is ready to be merged. Thanks so much!

**Comment by BadCrumpany** [comment]
@cyrichardson The warning looks great!

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 862 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2adc8681c/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
Staging link: https://support-revs.staging.deconst.org/build-2adc8681c/how-to/troubleshooting-provided-host-name-not-valid/

**Comment by cyrichardson** [comment]
@BadCrumpany Link to published article: https://support.rackspace.com/how-to/troubleshooting-provided-host-name-not-valid/

**Pull request merged**
