### PR TITLE
Disable apache

### PR DESCRIPTION
**Pull request by Sterling463**
https://jira.rax.io/browse/INFODEV-4762?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 665 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-988f89597/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
Will do, @Sterling463.

**Comment by cyrichardson** [comment]
:merged: @Sterling463

**Comment by rackernexus** [comment]
Build 684 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-49377c825/how-to/). valid for 14 days

**Pull request merged**
