### PR TITLE
Audit identifying-rackspace-standard-images.md: INFODEV-1287

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-72a9e6bcc2/how-to/)

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0c3dae6f6c/how-to/)

**Comment by cyrichardson** [comment]
Suggestions here, @RackerKate: 
[identifying-rackspace-standard-images_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1891514/identifying-rackspace-standard-images_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f33801c0d7/how-to/)

**Pull request merged**
