### PR TITLE
New article Cloud Office Primary Contact change

### PR DESCRIPTION
**Pull request by WilliamLoy**
Howdy @stephamon! Would you mind editing when you have a chance please?

Thanks!

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 374 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0544b5bb5/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@stephamon this one is ready for editing the you have a moment :)

**Comment by rackernexus** [comment]
Build 375 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d1db7b7bc/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 376 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6edc9af03/how-to/). valid for 14 days

**Pull request merged**
