### PR TITLE
Rackspace Email storage maintenance and best practices

### PR DESCRIPTION
**Pull request by WilliamLoy**
I have also sent an email with these Screen Captures

rsestoragewebmailsc1
rsestoragecpsc1
rsestoragenotificationssc1

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9da317c410/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8ecc06e009/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-bb2e83c1ec/how-to/). :bow:

**Comment by stephamon** [comment]
merged with #2135

**Pull request closed without merging**
