### PR TITLE
Add Jellyfish link and add audit date from last week's audit by Shaun: InfoDev-2521

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-179294020e/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson A small one for your review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-44d8378b76/how-to/). :bow:

**Pull request merged**
