### PR TITLE
Audit article: INFODEV-2594

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6c257ba527/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[rackspace-metrics-overview_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2479436/rackspace-metrics-overview_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2527265566/how-to/).

**Pull request merged**
