### PR TITLE
Update rescue-mode-on-windows-servers.md

### PR DESCRIPTION
**Pull request by kylelaffoon**
Apply Kelly's edits.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-d31acefaf1/how-to/)

**Comment by stephamon** [comment]
Hey @kylelaffoon make sure that any sub paragraphs or images in lists are indented 2 spaces. Otherwise it'll reset your lists.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a73884bf27/how-to/)

**Comment by stephamon** [comment]
:+1:

**Pull request merged**
