### PR TITLE
community cyberduck

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7a3fdc798c/how-to/)

**Comment by cyrichardson** [comment]
@catlook Suggestions here: 
[configure-rackspace-cloud-files-with-cyberduck_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2876608/configure-rackspace-cloud-files-with-cyberduck_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9078807783/how-to/)

**Pull request merged**
