### PR TITLE
Add article about migrating from MariaDB or Percona back to MySQL: INFODEV-3134

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c7fc5a8c39/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
[migrate-a-cloud-databases-instance-from-mariadb-or-percona-to-mysql_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2756434/migrate-a-cloud-databases-instance-from-mariadb-or-percona-to-mysql_cyrEdits.docx)
Just a couple of nits, @RackerKate:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3258873a40/how-to/)

**Pull request merged**
