### PR TITLE
Create Configuring Apache for SSL Termination on a Cloud Load Balancer

### PR DESCRIPTION
**Pull request by BadCrumpany**
Migrating community articles to support.rackspace.com

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-56eaf8a130/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e6cb9b6ae1/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0f2006c267/how-to/)

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just 1 nit here: 
[configure-apache-for-ssl-termination-on-a-cloud-load-balancer_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2770887/configure-apache-for-ssl-termination-on-a-cloud-load-balancer_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a1f66cf85a/how-to/)

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Pull request merged**
