### PR TITLE
Add tricore intro to mongodb article: INFODEV-1176

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7658092442/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-fc4af15e30/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Yet another for your review.

**Comment by cyrichardson** [comment]
@RackerKate Only one comment here: 
[introduction-to-mongodb_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1939546/introduction-to-mongodb_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-630645a397/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b76a632665/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8083210a2c/how-to/).

**Pull request merged**
