### PR TITLE
Fix CLB matrix table formatting

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes issue #1504

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4b07493bff/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-64011b8819/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-193e6a667c/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9e850932be/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7015bd50c1/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5f38979f96/how-to/).

**Comment by ReneeRendon** [comment]
Looks good. Thank you, @DonNateR

**Comment by ReneeRendon** [comment]
Fixes issue #1504

**Pull request merged**
