### PR TITLE
Create company-directory.md

### PR DESCRIPTION
**Pull request by hikarutilmitt**

### CODE REVIEW

**Comment by nimbinatus** [comment]
Opened PR on the patch-16 branch, hikarutilmitt/rackspace-how-to#6

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6528312e90/how-to/).

**Comment by nimbinatus** [comment]
Opened second PR on the patch-16 branch, hikarutilmitt/rackspace-how-to#12

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c2e76deeac/how-to/).

**Pull request merged**
