### PR TITLE
Remove portion from box

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1230 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-015c2b2e8/how-to/). valid for 14 days

**Comment by catlook** [comment]
let me fix your bulleted list.  need to add a blank line i think

**Comment by rackernexus** [comment]
Build 1233 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-dbcd4dea1/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1234 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9fcf4ea78/how-to/). valid for 14 days

**Comment by catlook** [comment]
think that got it!

**Pull request merged**
