### PR TITLE
Create safelist domain o365

### PR DESCRIPTION
**Pull request by wstubbs12**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1778 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ea49911bc/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1780 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8dfb1fb43/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1782 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8701791f9/how-to/). valid for 14 days

**Pull request merged**
