### PR TITLE
first edits

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-fe427a274f/how-to/).

**Comment by WilliamLoy** [comment]
@cyrichardson Ready for your review :)

**Comment by cyrichardson** [comment]
@WilliamLoy On it.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f5d73e5c88/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-49a02f58d5/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ebacdef7aa/how-to/)

**Comment by cyrichardson** [comment]
@WilliamLoy Please review, make any changes you think are needed, and merge. 

Most of the editorial changes are in this commit, https://github.com/rackerlabs/rackspace-how-to/pull/3245/commits/d41230ca66065c2fcd3f1fe2b93a7062f48d9632, although I did 2 additional commits with just small nits.

**Pull request merged**
