### PR TITLE
new article

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready :)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-95358f9668/how-to/).

**Comment by cyrichardson** [comment]
@WilliamLoy On it.

**Comment by cyrichardson** [comment]
@WilliamLoy Please review the editorial changes to see if you agree with them.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7944521e96/how-to/). :bow:

**Pull request merged**
