### PR TITLE
Audit create-linux-swap-file: INFODEV-1592

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a1053853f9/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-eb318584d5/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[create-a-linux-swap-file_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2630644/create-a-linux-swap-file_cyrEdits.docx)

**Pull request merged**
