### PR TITLE
Add community conversion article/experiment: INFODEV-2492

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7f1b3d5592/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-011e686b79/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d35f796410/how-to/). :bow:

**Comment by cyrichardson** [comment]
On it, @RackerKate!

**Comment by cyrichardson** [comment]
@RackerKate Only 1 nit but I'd already started the docx file: 
[build-a-new-cloud-server-with-automatic-updates-enabled_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2484564/build-a-new-cloud-server-with-automatic-updates-enabled_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-265844eb7c/how-to/).

**Pull request merged**
