### PR TITLE
Create set-date-time-timezone-on-server

### PR DESCRIPTION
**Pull request by csilva235**
Article on how to set the time/date on Linux server.

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1685 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1c0245813/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1686 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1c0245813/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1687 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fdb25ed43/how-to/). valid for 14 days

**Pull request merged**
