### PR TITLE
minor edits

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ebbbb0fb05/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d593702380/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-79ad2e5177/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-de5e761ae4/how-to/).

**Comment by cyrichardson** [comment]
@catlook Suggestions highlighted in this file: 
[remove-vpn-user-myrackspace-portal_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1794257/remove-vpn-user-myrackspace-portal_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-69faf33940/how-to/)

**Pull request merged**
