### PR TITLE
INFODEV-448 TriCore: Convert and add article for SQL Server tips

### PR DESCRIPTION
**Pull request by cyrichardson**
and tricks from ebook provided by marketing

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ef592b2a10/how-to/).

**Comment by cyrichardson** [comment]
Hi, @kmsholcomb! This may be my last editing request for you while you are here :-). This is a conversion of a TriCore doc. The original ebook is attached in https://jira.rax.io/browse/INFODEV-448. I would like to get your review of my take on the conversion, without the use of screen shots - along with your always helpful review comments. Thanks!

**Comment by kmsholcomb** [comment]
I'll review it today, Catherine.

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. I edited the text like I would any How-To article, deleting what seemed to be extraneous (although you had already done most of that work)! I think what you did was great; I had only a few suggestions. Let me know if you have any questions. Thanks!

[SQL Server tips and tricks_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1330524/SQL.Server.tips.and.tricks_editsKH.docx)
[SQL Server tips and tricks_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1330525/SQL.Server.tips.and.tricks_editsKH.pdf)

**Comment by cyrichardson** [comment]
@kmsholcomb Thanks a ton for doing this and the quick turnaround!

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1817ba54d0/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ad148df5ae/how-to/)

**Comment by cyrichardson** [comment]
Approved to publish by TriCore marketing staff on 10/18

**Comment by stephamon** [comment]
👍

**Pull request merged**
