### PR TITLE
Full Audit: SSH remote host identification

### PR DESCRIPTION
**Pull request by DonNateR**
INFODEV 1828

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b6b2ddb7d3/how-to/)

**Comment by cyrichardson** [comment]
@DonNateR Suggested changes here: 
[SSH - REMOTE HOST IDENTIFICATION HAS CHANGED_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2106613/SSH.-.REMOTE.HOST.IDENTIFICATION.HAS.CHANGED_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6f6526105c/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-abc576353a/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b5818ae7f4/how-to/). :bow:

**Pull request merged**
