### PR TITLE
Formatting issues

### PR DESCRIPTION
**Pull request by DonNateR**
!!!STOP!!!

Before you create a pull request, ensure that you are submitting your changes on a BRANCH instead of a fork. You can review how to make a branch in the contribution guidelines for this repository at https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md. 

Use the following bullet list to describe the changes that you made to the content. Use present tense. For example, if you added a question about image backups to the Cloud Images FAQ, you would say, "Add question about image backups to FAQ."

- Fix numbered list.

- Comment: This article could use Kelly Holcomb's eye. Whoever reviews this PR can make the call.

- 

DO NOT MERGE YOUR OWN PULL REQUEST.

### CODE REVIEW

**Comment by stephamon** [comment]
@DonNateR the format edits look good, but I agree that the article would benefit by a look from @kmsholcomb

**Comment by kmsholcomb** [comment]
I'm on it, @stephamon and @DonNateR! Do you want me to edit the file directly and create a PR from the PR? Or do you want markup in a Word doc?

**Comment by DonNateR** [comment]
@kmsholcomb: Word docs works for me :)

**Comment by kmsholcomb** [comment]
Will do. When I am done, I'll attach it here.

**Comment by kmsholcomb** [comment]
Hi @DonNateR: My edits are in the attached Word doc (and in the attached PDF copy of the Word doc). The article refers to a Vyatta document, and I compared this article to that document and found quite a bit was copied outright from it. Obviously, unless we have an agreement with another company, we try not to use their copyrighted content in our docs. So, I suggest that you talk to the author of the article and decide if you want to wholly revise the content or just refer to the Vyatta document, or some combination of both. I edited the content in question, and perhaps some of those edits will be enough to distinguish the content, but you should check. If you have any questions, please let me know. Thanks!

[Configuring Interface Based Firewall on the Vyatta Network Appliance_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/188619/Configuring.Interface.Based.Firewall.on.the.Vyatta.Network.Appliance_editsKH.pdf)
[Configuring Interface Based Firewall on the Vyatta Network Appliance_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/188620/Configuring.Interface.Based.Firewall.on.the.Vyatta.Network.Appliance_editsKH.docx)

**Pull request merged**
