### PR TITLE
Community Article - Using Firewalld on CentOS 7: INFODEV-3470

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8e95c43330/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6be746f026/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-223abaf684/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f667b87748/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Some suggestions here: 
[use-firewalld-on-centos-7_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2852556/use-firewalld-on-centos-7_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-67937414ae/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3d334d2800/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-47eadfafc7/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a6e82e0c77/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of suggestions: 
[use-firewalld-on-centos-7_cyrEdits2.docx](https://github.com/rackerlabs/rackspace-how-to/files/2906317/use-firewalld-on-centos-7_cyrEdits2.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-00a2d60108/how-to/)

**Comment by WilliamLoy** [comment]
LGTM

**Pull request merged**
