### PR TITLE
[Audit] RPC powered by MS Edits

### PR DESCRIPTION
**Pull request by RobinJoe**
* Adding remaining edits to the Requirements chapter, and to
  the FAQ chapter.

Closes issue /rackspace-how-to/issues/#1527

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e0018b0592/how-to/)

**Comment by DonNateR** [comment]
@RobinJoe: Is this ready to merge?

**Comment by RobinJoe** [comment]
@DonNateR It is near-ready to merge, the registered trademark syntax (&reg;) in the FAQ just needs repair, and then it should be ready - ready to merge by close of business November 2.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e126f1c169/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-001e1dc043/how-to/)

**Comment by RobinJoe** [comment]
Ready to merge!

**Pull request merged**
