### PR TITLE
vulnerability fixes rubygems dependencies

### PR DESCRIPTION
**Pull request by Rajpratik71**
#### Description
This PR fixes one or more vulnerable packages in the `rubygems` dependencies of this project.
See the [Snyk test report](https://app.snyk.io/org/rajpratik71/test/github/c2e54fea-096e-473a-91ed-7ede7be875d1/master..snyk-fix-n9dw53) for more details.

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - Gemfile
    - Gemfile.lock

##### With an upgrade:
- [SNYK-RUBY-FFI-22037](https://snyk.io/vuln/SNYK-RUBY-FFI-22037)
- [SNYK-RUBY-RACK-72567](https://snyk.io/vuln/SNYK-RUBY-RACK-72567)
- [SNYK-RUBY-SPROCKETS-22032](https://snyk.io/vuln/SNYK-RUBY-SPROCKETS-22032)

You can read more about Snyk's upgrade and patch logic in [Snyk's documentation](https://snyk.io/docs/using-snyk/).

Check the changes in this PR to ensure they won't cause issues with your project.

Stay secure,
The Snyk team

_**Note**: You are seeing this because you or someone else with access to this repository has authorised Snyk to open Fix PRs. To review the settings for this Snyk project please go to the [project settings page](https://app.snyk.io/org/rajpratik71/project/c2e54fea-096e-473a-91ed-7ede7be875d1/settings)._

[//]: # (snyk:metadata:{"type":"user-initiated","packageManager":"rubygems","vulns":["SNYK-RUBY-FFI-22037","SNYK-RUBY-RACK-72567","SNYK-RUBY-SPROCKETS-22032"],"patch":[],"upgrade":["SNYK-RUBY-FFI-22037","SNYK-RUBY-RACK-72567","SNYK-RUBY-SPROCKETS-22032"],"isBreakingChange":false,"env":"prod"})

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by edwardjrp** [comment]
build me

**Comment by Rajpratik71** [comment]
hi any one , have a look on this

**Comment by catlook** [comment]
Is this for an existing how-to article?  Or for one you are proposing?

**Comment by Rajpratik71** [comment]
hi , this PR is not about any how to articles , it is about the fixing vulnerability in the `rubygems` dependencies of this project.

> #### Description
> This PR fixes one or more vulnerable packages in the `rubygems` dependencies of this project.
> See the [Snyk test report](https://app.snyk.io/org/rajpratik71/test/github/c2e54fea-096e-473a-91ed-7ede7be875d1/master..snyk-fix-n9dw53) for more details.
> 
> #### Snyk Project: [Rajpratik71/rackspace-how-to:Gemfile.lock](https://app.snyk.io/org/rajpratik71/project/c2e54fea-096e-473a-91ed-7ede7be875d1)
> #### Snyk Organization: [Rajpratik71](https://app.snyk.io/org/rajpratik71)
> #### Changes included in this PR
> * Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
>   
>   * Gemfile
>   * Gemfile.lock
> 
> #### Vulnerabilities that will be fixed
> ##### With an upgrade:
> * [SNYK-RUBY-FFI-22037](https://snyk.io/vuln/SNYK-RUBY-FFI-22037)
> * [SNYK-RUBY-RACK-72567](https://snyk.io/vuln/SNYK-RUBY-RACK-72567)
> * [SNYK-RUBY-SPROCKETS-22032](https://snyk.io/vuln/SNYK-RUBY-SPROCKETS-22032)
> 
> You can read more about Snyk's upgrade and patch logic in [Snyk's documentation](https://snyk.io/docs/using-snyk/).
> 
> Check the changes in this PR to ensure they won't cause issues with your project.
> 
> Stay secure,
> The Snyk team
> 
> _**Note**: You are seeing this because you or someone else with access to this repository has authorised Snyk to open Fix PRs. To review the settings for this Snyk project please go to the [project settings page](https://app.snyk.io/org/rajpratik71/project/c2e54fea-096e-473a-91ed-7ede7be875d1/settings)._

**Comment by catlook** [comment]
Svetlana is researching this PR.

**Comment by nimbinatus** [comment]
Hi there! We never authorized Snyk to open any fix PRs in this repo. Someone may have used the tool once in a manual scan, but we are not interested at this time in using Snyk for any automated scanning. Thank you for your interest.

**Pull request closed without merging**
