### PR TITLE
Updated for H2 audit

### PR DESCRIPTION
**Pull request by catlook**
closes Issue #1079

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-eaf4f836ee/how-to/)

**Comment by catlook** [comment]
@kmsholcomb would you work your magic, please?

**Comment by kmsholcomb** [comment]
Hey @catlook. The attached PDf shows my suggested edits. Please let me know if you have any questions. Thanks!

[Check Linux file permissions with the ls command_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/326397/Check.Linux.file.permissions.with.the.ls.command_editsKH.pdf)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d6adf1f0b0/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f12a8dd2fe/how-to/)

**Comment by DonNateR** [comment]
LGTM

**Pull request merged**
