### PR TITLE
Create change-your-rackspace-email-password.md

### PR DESCRIPTION
**Pull request by brianecross**
This article will be linked to from a new "Change Your Password" graphic on the webmail login page at https://apps.rackspace.com

### CODE REVIEW

**Comment by DonNateR** [comment]
Fixes issue #1838

**Comment by brianecross** [comment]
For planning purposes, could you provide an estimate on when this page is likely to go live?

Thanks!

**Comment by DonNateR** [comment]
@brainecross: Was just about to answer your email. When do you need this published by?

**Comment by brianecross** [comment]
Hey thanks @DonNateR, it's really just as soon as possible. Would love to have it early next week. I'm just trying to figure out when to have the webmail team plan their release of the login banner that will link to this.

**Comment by DonNateR** [comment]
@brianecross: I'll make my changes and pass it along to our editor today. I'll sync up with you on email for an ETA once I've spoken with her.

**Comment by DonNateR** [comment]
@brianecross: Can you verify the following article is technically accurate? 

https://support.rackspace.com/how-to/rackspace-email-password-recovery-faq/ 

I think this would be a good place to put the steps you wrote about updating a user's phone number.

**Comment by brianecross** [comment]
https://support.rackspace.com/how-to/rackspace-email-password-recovery-faq/ looks accurate to me. It focuses on the recovery vs. the process of setting up your phone number which is probably where we need more emphasis.

Regarding the other edits, removing the intro/context certainly takes some of the impact out of this article for our intended purposed. I understand this is a "how to" and needs to be able to stand alone, but we're linking to it from a campaign on the webmail login page and trying to get people to understand why they should change it and what type of password to use, not just where to click.

Thanks!

**Comment by kmsholcomb** [comment]
Suggested edits attached, @DonNateR. Thanks!

[Change your Rackspace Email password_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/784263/Change.your.Rackspace.Email.password_editsKH.pdf)
[Change your Rackspace Email password_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/784264/Change.your.Rackspace.Email.password_editsKH.docx)

**Comment by DonNateR** [comment]
@brianecross: I updated the into to add more impact. I can't use the original language because the tone used is more consistent with a blog or community post than a How-To article. With that in mind, I tried to rework the original text to keep it tonally consistent with the rest of our articles.

Let me know what you think.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Just a few more suggestions, attached. 

[Change your Rackspace Email password_revision_KH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/788159/Change.your.Rackspace.Email.password_revision_KH.pdf)
[Change your Rackspace Email password_revision_KH.docx](https://github.com/rackerlabs/rackspace-how-to/files/788158/Change.your.Rackspace.Email.password_revision_KH.docx)

**Comment by DonNateR** [comment]
@brianecross: The article is ready to be merged after you give the thumbs up. I'll merge your images in a separate PR after this one is merged.

**Comment by brianecross** [comment]
@DonNateR Looks good to me. Thank you!

**Pull request merged**
