### PR TITLE
Add additional cyr edits

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b1276150f8/how-to/)

**Comment by cyrichardson** [comment]
Staging link sent to Marc Nourani via Slack for his review.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b1276150f8/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-45b0a5813e/how-to/)

**Pull request merged**
