### PR TITLE
Adding caveats

### PR DESCRIPTION
**Pull request by inflatador**
Don't want customer to get all the way thru the article only to find they can't import ;)

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4f3ca1d237/how-to/)

**Comment by catlook** [comment]
I'll try to squeeze this in this sprint (or do it for sure in the next one!)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f523ba6344/how-to/)

**Comment by cyrichardson** [comment]
@catlook Here are some suggestions: 
[transfer-server-images-between-cloud-regions-with-pitchfork_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1744640/transfer-server-images-between-cloud-regions-with-pitchfork_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-050c7f4fcd/how-to/). :bow:

**Pull request merged**
