### PR TITLE
Streamline Access list intro

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-11ff77c355/how-to/).

**Comment by cyrichardson** [comment]
@DonNateR A few suggestions here: 
[firewall-manager-v2-access-list-rules_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2202797/firewall-manager-v2-access-list-rules_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-305ab93d48/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d6f136bef1/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-8832a25dc2/how-to/)

**Pull request merged**
