### PR TITLE
add spanish version of cloud to cloud migration

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 4570

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 371 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5c58807c6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 373 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3f53edeb3/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 392 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3f53edeb3/how-to/). valid for 14 days

**Pull request merged**
