### PR TITLE
Set up mobile sync#1944

### PR DESCRIPTION
**Pull request by stephamon**
Part of #1944 

Add images to #1951

### CODE REVIEW

**Comment by stephamon** [comment]
@kmsholcomb Can you add this to your editing queue, please?

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits attached. Not much markup, but a few questions. Please let me know if you have any questions. Thanks!

[Set up Mobile Sync_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/913903/Set.up.Mobile.Sync_editsKH.pdf)
[Set up Mobile Sync_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/913904/Set.up.Mobile.Sync_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3a51767de6/how-to/)

**Comment by catlook** [comment]
LGTM

**Pull request merged**
