### PR TITLE
[WIP] create permissions matrix for cloud backup

### LINKED ISSUE #1787: Create a Cloud Backup permissions martix
There is not a published permissions matrix for Cloud Backup in the How-To. Sync up with a SME or use the API Guide to create a How-To permissions matrix.

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1787 

Create permissions matrix for Cloud Backup.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-029402338d/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8ae24288ac/how-to/)

**Comment by stephamon** [comment]
This has gotten a green light from Amit, so @kmsholcomb can you add this one to your list as well? Thanks!

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits attached. I found a few things that I think are questionable in the API content. I'm not sure if you have the bandwidth to deal with those, or whether possible inaccuracies there should be propagated to these matrixes or not. I suppose that is something for the HT team to decide. Anyway, let me know if you have any questions. Thanks!

[Permissions matrix for Cloud Backup_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/720260/Permissions.matrix.for.Cloud.Backup_editsKH.pdf)
[Permissions matrix for Cloud Backup_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/720261/Permissions.matrix.for.Cloud.Backup_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-45ae778181/how-to/)

**Pull request merged**
