### PR TITLE
[WIP] Full Audit on Importing Cloud Databases article

### LINKED ISSUE #1808: Full Audit:  Importing data into cloud databases
Checking this content for accuracy due to an internal bulletin. I have emailed Steve and Matt and will update this issue with their reply.

https://support.rackspace.com/how-to/importing-data-into-cloud-databases/

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x]  Editor check: Incorporate edits from Kelly Holcomb
- [ ]  Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ]  Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

### PR DESCRIPTION
**Pull request by nimbinatus**
Fixes #1808

### CODE REVIEW

**Comment by nimbinatus** [comment]
@kmsholcomb, can you add this one to your editing queue? Thanks!

**Comment by kmsholcomb** [comment]
Hi, @nimbinatus. My edits, comments, and questions are attached. Please let me know if you have any questions. Thanks!

[Import data into Cloud Databases_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/767809/Import.data.into.Cloud.Databases_editsKH.docx)
[Import data into Cloud Databases_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/767808/Import.data.into.Cloud.Databases_editsKH.pdf)

**Comment by nimbinatus** [comment]
@kmsholcomb, I ended up removing the screenshots as I added text to explain the screenshots. I don't think the screenshots are all that useful any longer. I also added a note at the top to check the best practices and limitations. How does it look now?

**Comment by kmsholcomb** [comment]
Yay for taking out screenshots! :) Looks good to me! 👍

**Comment by nimbinatus** [comment]
@DonNateR, when you have a chance, can you pre-check?

**Comment by DonNateR** [comment]
Ready to Merge

**Pull request merged**
