### PR TITLE
Sitecore: New article: Add Sitecore Package 

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ebb40d7165/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-52030267d2/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-592fc3669c/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9de47b35f2/how-to/)

**Comment by DonNateR** [comment]
Ready for editorial review.

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits are attached. I had a couple of questions that needed clarification, but most of the edits are straightforward. If you have any questions, please let me know. Thanks!

[Install a Sitecore package_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1053419/Install.a.Sitecore.package_editsKH.pdf)
[Install a Sitecore package_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1053420/Install.a.Sitecore.package_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-11744fe090/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a7328cc355/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-78d5d4a691/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e64a0758f3/how-to/).

**Comment by stephamon** [comment]
👍

**Pull request merged**
