### PR TITLE
Create troubleshooting-iis-high-resource-usage

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2047 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c190f3619/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2050 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ac22c3e58/how-to/). valid for 14 days

**Pull request merged**
