### PR TITLE
Rackspace pdr

### PR DESCRIPTION
**Pull request by TDillman**
Updated kernel versions and added 18.04 support to RMS agent compatibility page

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @TDillman it looks like you need to rebase your branch with master :)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f0ea3d2025/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-f0ea3d2025/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-50feaee216/how-to/).

**Pull request merged**
