### PR TITLE
infodev-2098: updated supported server versions

### PR DESCRIPTION
**Pull request by chri2547**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c849073d0e/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a20ae06c14/how-to/)

**Comment by cyrichardson** [comment]
On it, @chri2547.

**Comment by cyrichardson** [comment]
@chri2547 Suggested changes here: 
[cloud-servers-with-managed-operations-support-for-windows_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2349051/cloud-servers-with-managed-operations-support-for-windows_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ea2b661a2c/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a1cfe0a526/how-to/). :bow:

**Pull request merged**
