### PR TITLE
INFODEV-3293

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0792979fc6/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7c928d7d17/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c367e38ce5/how-to/).

**Comment by cyrichardson** [comment]
@WilliamLoy Suggested changes here: 
[cisco-asa-firewall-end-of-life-migration-faq_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2797040/cisco-asa-firewall-end-of-life-migration-faq_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0c4a7e0845/how-to/)

**Pull request merged**
