### PR TITLE
wire up bad actor recovery doc to other docs

### PR DESCRIPTION
**Pull request by brett-johnson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 407 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-baf98f547/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 410 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fe0ca3f41/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 411 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-378ca08e0/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 412 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-acbb04a74/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 414 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-125f72376/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 415 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9e4d3108c/how-to/). valid for 14 days

**Comment by brett-johnson** [comment]
@cyrichardson I approve. Thanks so much!

**Comment by cyrichardson** [comment]
Thanks, @brett-johnson. I'm still waiting for 1 more staging publish. Then I will merge the PR and request publishing to production.

**Comment by brett-johnson** [comment]
👍

**Comment by rackernexus** [comment]
Build 416 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f53f75443/how-to/). valid for 14 days

**Pull request merged**
