### PR TITLE
Replace outdated diagrams in ref article

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #521 

- Remove HTML tags

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a950f9c500/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9506e3c4a3/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-67425b4f2d/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested content edits are in the attached Word doc (and PDF copy of it). I don't really have any suggestions for the diagrams. PLease let me know if you have any questions. Thanks!

[Rackspace Open Cloud Reference Architecture_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/293912/Rackspace.Open.Cloud.Reference.Architecture_editsKH.pdf)
[Rackspace Open Cloud Reference Architecture_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/293911/Rackspace.Open.Cloud.Reference.Architecture_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a7ac164375/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-cf85e926d8/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6de9dac271/how-to/)

**Pull request merged**
