### PR TITLE
Revise recover deleted webmail

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a34ed9b84a/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-60a158d61a/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-90604989b0/how-to/). :bow:

**Comment by cyrichardson** [comment]
Suggestions here: 
[recover-deleted-email-in-webmail_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1759468/recover-deleted-email-in-webmail_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7d631e3625/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b4f262df4e/how-to/).

**Pull request merged**
