### PR TITLE
Audit choosing the right database: INFODEV-1366

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7be192f83b/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[choosing-the-right-database-with-rackspace-cloud-databases_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1943806/choosing-the-right-database-with-rackspace-cloud-databases_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d76ac8305a/how-to/).

**Pull request merged**
