### PR TITLE
FWCP v2 consistency fixes

### PR DESCRIPTION
**Pull request by DonNateR**
Perform final audit of Firewall Manager v2 articles.

- Streamline all links

- Fix any typos

- Remove dashes from title names

- Add images to intro article

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e6578cbca3/how-to/).

**Comment by stephamon** [comment]
You do seem to have a failing strider build for some reason @DonNateR

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-71ffe7c475/how-to/). :bow:

**Comment by stephamon** [comment]
Excellent, 👍

**Pull request merged**
