### PR TITLE
Move article into content/general repo.

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by DonNateR** [comment]
@kylelaffoon: Any H1 heading needs to be switched to H3 headings in order to conform to How-To markdown standards.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3b086e85c5/how-to/). :bow:

**Comment by kylelaffoon** [comment]
Thanks @DonNateR. The H1 items are now adjusted.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-af5f42f5e3/how-to/)

**Comment by ReneeRendon** [comment]
This needs to be a .md file.

**Comment by kylelaffoon** [comment]
Thanks @ReneeRendon. Done.

**Comment by kylelaffoon** [comment]
Added single quotes to title metadata.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9bb1c11a91/how-to/).

**Pull request merged**
