### PR TITLE
Community Article - Next Steps After Creating a LAMP Server: INFODEV-3467

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-4afb576a6d/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-489448b04e/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of suggestions here: 
[next-steps-after-creating-a-lamp-server_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2846776/next-steps-after-creating-a-lamp-server_cyrEdits.docx)

**Pull request merged**
