### PR TITLE
Added forking instructions to Contributing.md

### PR DESCRIPTION
**Pull request by DonNateR**
- Add section called "Getting started with GitHub".

- Add forking steps in "Create an article" section.

- Add forking steps to "Edit an article" section.

- Add section about editing a PR.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c193a2b132/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-71d72072fd/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR: Although my suggested edits aren't that extensive, I decided to just post them here rather than edit the file directly because I had some questions. So, I apologize for making more work for you. If you have any questions for me, let me know. Thanks!

[Contributing to the Rackspace How To content repository_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/200363/Contributing.to.the.Rackspace.How.To.content.repository_editsKH.docx)
[Contributing to the Rackspace How To content repository_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/200364/Contributing.to.the.Rackspace.How.To.content.repository_editsKH.pdf)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0af970c3c0/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2531c95d6e/how-to/)

**Pull request merged**
