### PR TITLE
aiops-tier2

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by viridaria** [comment]
First dab at it

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2304 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8ce2475e7/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2308 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8ce2475e7/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2309 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8ce2475e7/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by viridaria** [comment]
build me

**Comment by viridaria** [comment]
build me

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2313 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4863cc011/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2314 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ca5b952dc/how-to/). valid for 14 days

**Comment by mralexjuarez** [comment]
From the AIOPs education side, this all looks good for publishing.

**Pull request merged**
