### PR TITLE
final edits

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by WilliamLoy** [comment]
@cyrichardson Got this one read for ya :)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-94faff0d0d/how-to/). :bow:

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by cyrichardson** [comment]
@WilliamLoy Please review the editorial changes to see if you agree with them.

**Comment by WilliamLoy** [comment]
LGTM!

**Pull request merged**
