### PR TITLE
minor edits

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-dee34da8e8/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8f9aad3320/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-836fb146cc/how-to/).

**Comment by cyrichardson** [comment]
@catlook Minor changes highlighted in this file: 
[add-new-vpn-user-myrackspace-portal_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1794279/add-new-vpn-user-myrackspace-portal_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9e53413e3c/how-to/)

**Pull request merged**
