### PR TITLE
Create checking-port-use-in-linux

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1987 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9c4d2635f/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready for ya :) I couldn't decide how to format the commands within headers but I thought it looked best with "" for H2's and `` for H3's

**Comment by cyrichardson** [comment]
@WilliamLoy  On it!

**Pull request merged**
