### PR TITLE
removed unsupported language from note in mail server section

### PR DESCRIPTION
**Pull request by chri2547**
The SME has signed off on this change.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-21b4d060cf/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-31104084d5/how-to/). :bow:

**Comment by cyrichardson** [comment]
@chri2547 Added a comma before a "which". The rest of the change LGTM.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d4ad8787b3/how-to/).

**Pull request merged**
