### PR TITLE
New article: Sitecore FAQ

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1984

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a0a5a9adb4/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-10e5062688/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-bd805e1497/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-2d8ede48e7/how-to/)

**Comment by DonNateR** [comment]
Blocked until the Sitecore team has given us the remaining answers for the FAQ.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-10414de1cc/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-32e1d28140/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggestions are attached. If you need anything else from me, please let me know. Thanks!

[Sitecore Cloud FAQ_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1089805/Sitecore.Cloud.FAQ_editsKH.pdf)
[Sitecore Cloud FAQ_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1089804/Sitecore.Cloud.FAQ_editsKH.docx)

**Comment by DonNateR** [comment]
No audit date on this one, since we'll be adding more questions in the future.

**Comment by DonNateR** [comment]
Ready to merge.

**Comment by stephamon** [comment]
👍

**Pull request merged**
