### PR TITLE
Metadata changes.

### PR DESCRIPTION
**Pull request by beau-bailey**
Made changes to metadata to represent it as a new article. Place article in undefined section as it covers both rackspace email, exchange and everything in the control panel.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0788b181e7/how-to/). :bow:

**Comment by DonNateR** [comment]
@beau-bailey: How do you like the idea of generic "Cloud Office" content folder? There are a couple of articles that deal with the Cloud Office Control Panel that probably shouldn't be in the Exchange or Sharepoint folders. On the support.rackspace.com/how-to page, this folder would show up just like the "Exchange" and "Sharepoint" folders when you click the "Cloud Office" tab.

Thoughts?

**Comment by DonNateR** [comment]
@beau-bailey: Reason I suggest this is because the "undefined" metadata tag is mostly used for article about billing.

**Comment by ReneeRendon** [comment]
We don't want to use General as a multi-product directory if we can help it. As @DonNateR pointed out, that is or articles that don't have any product. 
Something else to keep in mind is that articles that are in that directory tend to be a bit harder to find online because they don't show up under any category. (I believe)

**Comment by ReneeRendon** [comment]
I don't we should create any new categories/directories until @beau-bailey and @stephamon have mapped out a plan.

**Comment by beau-bailey** [comment]
@DonNateR "Cloud Office" would be an idea. @ReneeRendon Agreed. I am still working on the layout. Sorry for the delay. I am trying to think of different things as they come up, which is why I am asking so many questions. :) I will wait on any further changes around categories until I work with @stephamon to get it all mapped out. Thanks!

**Pull request closed without merging**
