### PR TITLE
Netsec spheres of support

### PR DESCRIPTION
**Pull request by abekele0413**
I updated the disclaimer after running this by legal.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3ce399b789/how-to/)

**Comment by abekele0413** [comment]
The only issue is it is creating a table at the very bottom within the disclaimer and this is only noticed in the preview link:
https://staging.developer.rackspace.com/support.rackspace.com/build-3ce399b789/how-to/netsec-spheres-of-support-for-dedicated-and-managed-ops/
search for text "Rackspace cannot guarantee the accuracy"

Any help is greatly appreciated.

**Comment by catlook** [comment]
i can remove that table

**Comment by cyrichardson** [comment]
@catlook Suggestions here: 
[netsec-spheres-of-support-for-dedicated-and-managed-ops_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2943037/netsec-spheres-of-support-for-dedicated-and-managed-ops_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-300b045783/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7c021d8937/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-2af07cfa0b/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-936465056e/how-to/).

**Pull request merged**
