### PR TITLE
Update SMTP to smtp in Alternate email addresses

### PR DESCRIPTION
**Pull request by aaron-medrano**
#### Alternate email addresses (optional synchronization)
with Exchange OnPrem synchronized, setting the proxy address attribute to a capital SMTP will cause issues. Updated instances of SMTP to lower case smtp instead.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1049 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-aac20fada/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1051 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-87151a2b9/how-to/). valid for 14 days

**Comment by aaron-medrano** [comment]
@WilliamLoy

**Comment by cyrichardson** [comment]
build me

**Comment by cyrichardson** [comment]
Trying to build again to see if a new build will be successful.

**Comment by rackernexus** [comment]
Build 1053 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0df266d47/how-to/). valid for 14 days

**Pull request merged**
