### PR TITLE
Auditing article.

### PR DESCRIPTION
**Pull request by catlook**
Closes Issue #1090

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-1b29504566/how-to/). :bow:

**Comment by catlook** [comment]
@kmsholcomb Can you give this the once over, please?

**Comment by kmsholcomb** [comment]
Hi @catlook. My suggested edits are in the attached PDF (which I created from a Word file that I marked up). Please let me know if you have any questions. Thanks!

[Generate RSA Keys With SSH PuTTYgen_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/321370/Generate.RSA.Keys.With.SSH.PuTTYgen_editsKH.pdf)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9a47377602/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-60ca0ba364/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ffbb044e3e/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
