### PR TITLE
Community Article - ftp vs sftp

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1c95ce77ca/how-to/)

**Comment by RackerKate** [comment]
Might be able to close this because we already have this content in https://support.rackspace.com/how-to/rackspace-cloud-essentials-centos-installing-vsftpd/. Asked SME.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-804e36c81b/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5bc14278ba/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate 2nd in editing queue. On it very shortly.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of nits: 
[overview-of-ftp-and-sftp_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2881639/overview-of-ftp-and-sftp_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8c7dd8a8ed/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d0f89e7599/how-to/). :bow:

**Pull request merged**
