### PR TITLE
Audit RBAC workarounds article: INFODEV-1253

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6c06a2ecf6/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[known-issues-and-suggested-workarounds-role-based-access-control-rbac_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2686475/known-issues-and-suggested-workarounds-role-based-access-control-rbac_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-867fdb5160/how-to/). :bow:

**Pull request merged**
