### PR TITLE
Add comm article: INFODEV-3278. Replaces block at https://github.com/…

### PR DESCRIPTION
**Pull request by RackerKate**
…rackerlabs/rackspace-how-to/pull/3132

### CODE REVIEW

**Comment by RackerKate** [comment]
Replaces #3132.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3866062a1f/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-19a635be37/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0c10d2de52/how-to/)

**Pull request merged**
