### PR TITLE
CBU current corrections

### PR DESCRIPTION
**Pull request by brett-johnson**

### CODE REVIEW

**Comment by brett-johnson** [comment]
Not sure why those 2 png files were marked as modified in this pull request. I didn't touch them and they should not be changed.

**Comment by brett-johnson** [comment]
This pull request is related to JIRAs INFODEV-6394 and CBU-855.

**Review by catlook — APPROVED** [review]
I made some edits directly.

**Comment by catlook** [comment]
making changes in new repo

**Comment by catlook** [comment]
changes merged in support-how-to instead

**Pull request closed without merging**
