### PR TITLE
Create windows-local-group-policy

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1945 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f3f559ff8/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1947 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8c6d00b30/how-to/). valid for 14 days

**Pull request merged**
