### PR TITLE
Fixes #1227 Cloud Backup article Install the agent on Windows

### LINKED ISSUE #1227: Update Cloud Backup article Install the Cloud Backup agent on Windows by using silent installation
From: Brett Johnson <brett.johnson@rackspace.com>
Date: Wednesday, July 13, 2016 at 4:27 PM
To: Catherine Richardson <catherine.richardson@RACKSPACE.COM>
Subject: Install the Cloud Backup agent on Windows by using silent installation

Updates to this page: https://support.rackspace.com/how-to/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation/

#1
In the warning in the 2nd paragraph:
Whenever possible, you should install the Rackspace Cloud Backup agent

should be:
All others should install the Rackspace Cloud Backup agent

#2
The example code under Perform a silent installation:
msiexec /i driveclient-latest.msi /qn /l*v %tmp%\install-driveclient-latest.log APIUSER=myuser APIKEY=abcdef1234567890abcdef1234567890 APIHOSTNAME=<region>.backup.api.rackspacecloud.com DATACENTER=IAD DEBUGHIGH=true

should be:
msiexec /i driveclient-latest.msi /qn /l*v %tmp%\install-driveclient-latest.log APIUSER=<user> APIKEY=<apikey> APIHOSTNAME=<region>.backup.api.rackspacecloud.com DATACENTER=<region>

#3
The bullet point APIHOSTNAME contains a link that is not clickable (Service Access endpoints). This should be clickable.
Also, the text on APIHOSTNAME bullet point:
is optional.

should be:
(required):

#4
The bullet point APIHOSTURL should be deleted.

#5
The link at the bottom of the page for Test Windows installation or update returns to the top of the page, and does not show any test procedures.

### PR DESCRIPTION
**Pull request by cyrichardson**
by using silent installation - changes from SME, Brett Johnson

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b9c08173f9/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-52f478356c/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-72e3f98c37/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-58611f7164/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9923f28e59/how-to/)

**Comment by catlook** [comment]
👍

**Pull request merged**
