### PR TITLE
Community Article - Managing Security Groups and Rules

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-681007c3d2/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-708edc7828/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ed268a46d2/how-to/)

**Comment by WilliamLoy** [comment]
@cyrichardson ready for your review :)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-35248b3242/how-to/)

**Comment by cyrichardson** [comment]
@WilliamLoy Suggested changes here: 
[managing-security-groups-and-rules_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2841349/managing-security-groups-and-rules_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4435e3812d/how-to/).

**Pull request merged**
