### PR TITLE
Community Article - Custom Cloud Monitoring Alerts: INFODEV-3452

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ba5fa58831/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9c926bd6fd/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f191017e89/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-799fa7e295/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f281b25be7/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-ab502d2eb6/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-955b3f9ef0/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[create-a-custom-cloud-monitoring-alert_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2861454/create-a-custom-cloud-monitoring-alert_cyrEdits.docx)

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by cyrichardson** [comment]
Sorry! I hit the wrong button!!! @RackerKate

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-017715d8cb/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson I figured; no worries! :-)

**Pull request merged**
