### PR TITLE
[WIP] Combine PHP mail articles into one

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes issue #1192 

- Combine article https://support.rackspace.com/how-to/test-php-smtp-functionality/ and https://support.rackspace.com/how-to/sending-html-mail-via-php-in-cloud-sites/ into https://support.rackspace.com/how-to/test-php-mail-functionality/.

- Change title and permalink of single article "Test and send mail using PHP"

- Fix code block formatting in "HTML" section

- Add code directives to all bulleted list

- Delete information repeated across all three articles

- Add all combined article titles as H3 headings

- Change H3 headings from combined articles to H4

Article needs technical review from a SME

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-63275b7ffb/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-d812f2c751/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits are in the attached Word (and PDF) file. I didn't have many copy edits, but I think the article might need a more general introduction and more explanation about how the methods of testing are related. Anyway, see my few comments in the attached doc. Please let me know if you have any questions. Thanks!

[Test and send mail using PHP_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/369496/Test.and.send.mail.using.PHP_editsKH.pdf)
[Test and send mail using PHP_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/369495/Test.and.send.mail.using.PHP_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-dd6a9fa6a1/how-to/)

**Comment by catlook** [comment]
👍

**Pull request merged**
