### PR TITLE
Full audit: Configure w3tc for WordPress

### LINKED ISSUE #1578: Full audit: Configure w3 total cache for Wordpress with Cloud Files
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-files/configure-w3-total-cache-for-wordpress-with-rackspace-cloud-files-cdn.md

Each step must be performed in order for an article to be considered audited:

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [ ] Editor check: Incorporate edits from Kelly Holcomb
- [ ] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [ ] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1578 

add updated screenshots and update instructions

### CODE REVIEW

**Comment by stephamon** [comment]
Going to add a section on accelerating WordPress and will retire and redirect the "Accelerate WordPress with Cloud Files and the W3TC plug-in" article

**Comment by stephamon** [comment]
@kmsholcomb can you take a look at this for me? Thanks!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-aea6ec89ff/how-to/). :bow:

**Comment by kmsholcomb** [comment]
I'll get to it this afternoon, @stephamon.

**Comment by kmsholcomb** [comment]
Amend that: I'll get to it first thing in the morning! Sorry for the delay.

**Comment by kmsholcomb** [comment]
Hi @stephamon. My edits are in the attached docs. I also reviewed the article's "sister" article, the one about configuring the plug-in with CDN. The OCD part of me wanted the sections that were similar to be the same! Anyway, they are a bonus edit (and there's not much there). If you have any questions, please let me know. Thanks!

[Configure W3 Total Cache for WordPress with Rackspace Cloud Files_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/797224/Configure.W3.Total.Cache.for.WordPress.with.Rackspace.Cloud.Files_editsKH.pdf)
[Configure W3 Total Cache for WordPress with Rackspace Cloud Files_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/797225/Configure.W3.Total.Cache.for.WordPress.with.Rackspace.Cloud.Files_editsKH.docx)

[Configure W3 Total Cache for WordPress with Rackspace CDN_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/797227/Configure.W3.Total.Cache.for.WordPress.with.Rackspace.CDN_editsKH.pdf)
[Configure W3 Total Cache for WordPress with Rackspace CDN_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/797228/Configure.W3.Total.Cache.for.WordPress.with.Rackspace.CDN_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1c7dfcb25d/how-to/).

**Pull request merged**
