### PR TITLE
update auto scale rbac article

### PR DESCRIPTION
**Pull request by stephamon**
applied editor feedback from servers rbac article, and matching language of API methods to API reference

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-45754ca48d/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0ee4c48a57/how-to/).

**Comment by kmsholcomb** [comment]
Hi, @stephamon. Just a few nitpicky edits and one very nitpicky question!

[Permissions matrix for Rackspace Auto Scale_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/625466/Permissions.matrix.for.Rackspace.Auto.Scale_editsKH.pdf)
[Permissions matrix for Rackspace Auto Scale_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/625467/Permissions.matrix.for.Rackspace.Auto.Scale_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-cf1865bfa0/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-411ca16184/how-to/)

**Pull request merged**
