### PR TITLE
Create granting-sudo-access-in-debian-and-ubuntu

### PR DESCRIPTION
**Pull request by csilva235**
Article for how to grant sudo/admin access in Debian based distros.

Article to be referenced in placeholder section of #3659

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1669 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-832b063cc/how-to/). valid for 14 days

**Comment by catlook** [comment]
@csilva235: how's this?  Good to go?  ("the Ubuntu operating system" phrase is a requirement from legal.  Sorry bout that!)

**Comment by catlook** [comment]
https://support-revs.staging.deconst.org/build-832b063cc/how-to/grant-sudo-access-in-debian-and-the-ubuntu-operating-system/

**Comment by csilva235** [comment]
@catlook Just made a minor change to indicate that this article is for an existing user. 

Other than that, it looks good to go. 

Thanks!

**Pull request merged**
