### PR TITLE
BCP - upgrade-sharepoint-site-storage-cloud-office-control-panel

### PR DESCRIPTION
**Pull request by catlook**
placeholder PR

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e00a7b570b/how-to/)

**Comment by catlook** [comment]
@WilliamLoy has sme approved

**Comment by catlook** [comment]
@cyrichardson edit please

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-74ee5d2ecc/how-to/).

**Comment by cyrichardson** [comment]
One tiny suggestion: 
[upgrade-sharepoint-site-storage-cloud-office-control-panel_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1678703/upgrade-sharepoint-site-storage-cloud-office-control-panel_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-72b8488188/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c6297b06ad/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
