### PR TITLE
Create What_Is_Autodiscover_Record_And_Why_Do_I_Need_It

### PR DESCRIPTION
**Pull request by aaron-medrano**
Looking to create a useful article to help customers understand the uses of Autodiscover with Hosted Exchange.
[Autodiscover Article Images.zip](https://github.com/rackerlabs/rackspace-how-to/files/582147/Autodiscover.Article.Images.zip)

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4db3d3cb6a/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-73772c688e/how-to/)

**Comment by DonNateR** [comment]
@aaron-medrano: Would it be worthwhile to add content from the "autodiscover" section of this article? https://support.rackspace.com/how-to/set-up-dns-records-for-cloud-office-email-and-skype-for-business/#autodiscover-records

**Comment by aaron-medrano** [comment]
@DonNateR I thought about it, and thought maybe it would just be easier to just link to that site. It shows all the other DNS records. Plus I don't have to rewrite what already exists. If you think it would be a better user experience, then I think it would be good to go ahead and include it.

**Comment by DonNateR** [comment]
@aaron-medrano: Sorry for the delay. The article concerns setting up exchange to work with outlook and autodiscover. With that in mind, is this statement from the article I linked to you earlier true, 

"Note: Autodiscover is not compatible with Outlook 2011, Outlook 2016, or Mac Mail when setting up an email account as POP or IMAP."

**Comment by aaron-medrano** [comment]
@nate yeah, that statement is still correct when trying to connect with POP/IMAP connections

**Comment by DonNateR** [comment]
@aaron-medrano: Last question about these two lines: 

"+1. Setup Outlook 2007/2010/2013/2016 for Windows setup using Autodiscovery.
 +2. Setup Outlook 2011/2016 for Mac using Autodiscovery." 

Are you using "Set-up" as a verb, in order for Autodiscover work with outlook? OR is autodiscover a feature?

**Comment by aaron-medrano** [comment]
@DonNateR the first setup is a verb. It can be rewritten to (to make it easier):
"+1. Set-up Outlook 2007/2010/2013/2016 for Windows using Autodiscovery.
+2. Set-up Outlook 2011/2016 for Mac using Autodiscovery."

**Comment by DonNateR** [comment]
Edits moved to PR #1642

**Pull request closed without merging**
