### PR TITLE
Full audit: Managed ops on Linux

### PR DESCRIPTION
**Pull request by DonNateR**
- Part of issue #1613 

- Add Ubuntu 16.04 to Managed Ops list.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b2ed3b2e67/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits are in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. Thanks!

[Cloud Servers with Managed Operations support for Linux_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/604821/Cloud.Servers.with.Managed.Operations.support.for.Linux_editsKH.pdf)
[Cloud Servers with Managed Operations support for Linux_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/604822/Cloud.Servers.with.Managed.Operations.support.for.Linux_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-773a090cc5/how-to/).

**Comment by catlook** [comment]
👍

**Pull request merged**
