### PR TITLE
Community Article - Change Kernel Version Via Rescue Mode on a Linux …

### PR DESCRIPTION
**Pull request by BadCrumpany**
…Cloud Server

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-07cd273b39/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-af8e4e07fe/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-25a8acb1a0/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-93234c2461/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-218c73f524/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just some nits here: 
[change-the-kernel-version-on-a-linux-cloud-server-by-using-rescue-mode_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2797583/change-the-kernel-version-on-a-linux-cloud-server-by-using-rescue-mode_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3f2d70573c/how-to/)

**Pull request merged**
