### PR TITLE
Networking Fundamentals - New and Improved

### PR DESCRIPTION
**Pull request by THE-Alan-Hicks**
Now with 100% more formatting fixes. This should resolve all the code blocks not printing properly, fix the image to display properly, and several other minor fixes.

Additionally, I modified index.md to place this under the Network section. I'm not sure if this really belongs there or if it will format correctly or not, so please feel free to change that or let me know what I should do.

I sort of unilaterally created a new "Fundamentals" heading here. There's three or four other articles in my Fundamentals section on the one-wiki that can be drawn into our public knowledge base. I don't know if these should get their own section or what so I leave handling that up to y'all.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9c5a0eddbd/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-5f5b0e9984/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-403b0e441b/how-to/). :bow:

**Comment by stephamon** [comment]
Hey @THE-Alan-Hicks I've noticed a few more commits trickling in, so let me know when you're ready for this to start our review process, and I'll get going!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-50aabac8b0/how-to/)

**Comment by THE-Alan-Hicks** [comment]
Sorry about that. I added a new file that I meant to exist in a separate branch as that file isn't remotely ready for review. With this latest push this pull request should be ready for review now.

**Comment by stephamon** [comment]
We'll be housing this in the white-paper repo when it's ready, so I'm going to close this PR out.

**Pull request closed without merging**
