### PR TITLE
New article for installing and configuring auter

### PR DESCRIPTION
**Pull request by ruthealee**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5f031465a9/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-100f54c2d2/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1a7f673f0e/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. I've suggested some edits in the attached doc. Please let me know if you have any questions. Thanks!

[Install Auter on CentOS 6_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1247317/Install.Auter.on.CentOS.6_editsKH.docx)
[Install Auter on CentOS 6_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1247318/Install.Auter.on.CentOS.6_editsKH.pdf)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3da1449777/how-to/)

**Comment by stephamon** [comment]
👍

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7b7be44531/how-to/)

**Pull request merged**
