### PR TITLE
Changed details for shared and importing images

### PR DESCRIPTION
**Pull request by mystcb**
I have updated the details regarding importing and sharing images within the Rackspace Cloud. Originally it said that images could not be transferred between accounts, however it is possible to share images between accounts and create a server from that image. 

Additionally amended details regarding importing images, however pointed people looking to do this to the appropriate support page.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6fa0c40ca7/how-to/)

**Comment by DonNateR** [comment]
Need technical review before we can merge.

**Comment by ostackbrian** [comment]
I'd suggest re-phrasing the first point like this:

Cloud Server images cannot be transferred between accounts.  You can, however, share images between accounts in the same region. You can then build a server from the shared image and create an image of this new server, which will effectively provide you with your own copy of the image.

**Comment by ostackbrian** [comment]
I think it would be better to move the two points about ISOs and creating an image from scratch to a separate section, maybe at the bottom of this document.  The reason is that the Compute API has the "image create" action (that is, creating a snapshot), so at Rackspace we usually mean "snapshot" when we're talking about "image creation".  We usually use the term "image import" to talk about using Cloud Images to "bring your own image" into the cloud.  Talking about ISOs and bring-your-own in the same place as snapshots can be a bit confusing.  Technically, however, your content is correct.

I'd also suggest adding a link to the Cloud Images FAQ.  It's got a section on image sharing, and another section on image import and export.

**Pull request closed without merging**
