### PR TITLE
full audit security backdoors and intruders

### PR DESCRIPTION
**Pull request by stephamon**
add lsof clarification

JIRA 2367

### CODE REVIEW

**Comment by stephamon** [comment]
@cyrichardson this one as well, please! Not many changes here :)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7cadcd4bd7/how-to/). :bow:

**Comment by cyrichardson** [comment]
@stephamon Some suggested changes here: 
[check-for-a-security-compromise-back-doors-and-intruders_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2558260/check-for-a-security-compromise-back-doors-and-intruders_cyrEdits.docx)

**Comment by cyrichardson** [comment]
@stephamon Some suggested changes here: 
[check-for-a-security-compromise-back-doors-and-intruders_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2558260/check-for-a-security-compromise-back-doors-and-intruders_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-611a588ebf/how-to/)

**Pull request merged**
