### PR TITLE
Grammatical edits for audit of "Learn RBAC": INFODEV-1081

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-42d5dbd5a6/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review. This is old due to SME delay.

**Comment by cyrichardson** [comment]
(Build weirdness - clicking Details now asking me to log in with OpenShift.)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-85137b0947/how-to/). :bow:

**Pull request merged**
