### PR TITLE
Add a "Properties of SQL & NoSQL databases" page for TriCore: INFODEV-1171

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-132acc8d4c/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0ae8ba9850/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of suggestions here: 
[properties-of-rdbmss-and-nosql-databases_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1939949/properties-of-rdbmss-and-nosql-databases_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5033417025/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-5a61fcc63f/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6d3ab39dcb/how-to/)

**Pull request merged**
