### PR TITLE
Audit article on checking running services on Linux: INFODEV-2401

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8db74baf95/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b633fd0ebb/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Some suggestions here: 
[checking-running-services-on-linux_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2484754/checking-running-services-on-linux_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-8af23da8fa/how-to/). :bow:

**Pull request merged**
