### PR TITLE
Update screenshots for article, per SME.

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-60f8e590a9/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-60f8e590a9/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0952c01671/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-053d7fac9c/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3ef1910fda/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
Thanks, @RackerKate. On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here - 
[faq-for-seamless-sign-on-between-myrackspace-and-the-cloud-control-panel_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1804703/faq-for-seamless-sign-on-between-myrackspace-and-the-cloud-control-panel_cyrEdits.docx)>

Cat said she was having trouble seeing changes so I started adding highlighting to show them. If this is bothersome for you, please let me know. 

Thanks!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9a5ca1e619/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2ac6bd8263/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-152b2d6273/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
