### PR TITLE
Revised Integrate Archvie in Outlook per product

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6b98d2c29e/how-to/). :bow:

**Comment by stephamon** [comment]
redirect https://github.com/rackerlabs/nexus-control/pull/848

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-20649736ff/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-49ce5a8b31/how-to/)

**Pull request merged**
