### PR TITLE
Audit article on best practices for backup: INFODEV-2744

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2a057cd2e8/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[best-practices-for-backing-up-your-data-cloud-block-storage-versus-cloud-backup_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2585958/best-practices-for-backing-up-your-data-cloud-block-storage-versus-cloud-backup_cyrEdits.docx)

**Pull request merged**
