### PR TITLE
BCP - Update info

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d69f49eab7/how-to/).

**Comment by catlook** [comment]
First PR - WOOT!!!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d168c5e9ff/how-to/)

**Comment by RackerKate** [comment]
Need to find a way to remove 2nd file, which requires a separate branch/PR. Attempt at reverting commit failed.

**Comment by RackerKate** [comment]
Will redo with only one file changed.

**Pull request closed without merging**
