### PR TITLE
Get back up to date.

### PR DESCRIPTION
**Pull request by sean-laszakovits**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-50be799d2d/how-to/)

**Comment by sean-laszakovits** [comment]
I JUST WANT TO MERGE THE STUPID RACKERLABS VERSION INTO MY BRANCH BNH FALGAV ;IHDSGKV;UAHSD;KGJVA HSD;LJKGHAWgsdgv;ohi[asdfbh;

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-58dc164350/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ccadebc896/how-to/)

**Pull request merged**
