### PR TITLE
Updated role matrix for cloud feeds

### PR DESCRIPTION
**Pull request by shub6691**

### CODE REVIEW

**Comment by stephamon** [comment]
JIRA 6034

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 2063 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-266754126/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2070 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e2939ff56/how-to/). valid for 14 days

**Pull request merged**
