### PR TITLE
Create change-ssh-port-in-centos-rhel

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@BadCrumpany please review :)

**Comment by catlook** [comment]
build me

**Comment by BadCrumpany** [comment]
@WilliamLoy looks good.  Thanks!

**Comment by rackernexus** [comment]
Build 2051 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d2752f08d/how-to/). valid for 14 days

**Pull request merged**
