### PR TITLE
first edits

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6da505f31b/how-to/)

**Comment by WilliamLoy** [comment]
@cyrichardson I am going for the hat trick today

**Comment by cyrichardson** [comment]
OK, @WilliamLoy. I'm on it.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-81f621a415/how-to/)

**Comment by WilliamLoy** [comment]
Review complete

**Pull request merged**
