### PR TITLE
Fixes #1223 and updates article Cloud Backup Agent Logging Basics

### LINKED ISSUE #1223: Update Cloud Backup article Agent logging basics
From: Brett Johnson <brett.johnson@RACKSPACE.COM>
Date: Tuesday, July 12, 2016 at 6:33 PM
To: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>
Cc: Cloud Backup <CloudBackup@rackspace.com>
Subject: Re: Cloud Backup Agent Logging Basics

These are also part of the current 2.x agent features, so they can be published at any time.

Just FYI, Outlook changed some of the URLs in the XML below to clickable links, but none of the XML configs should have clickable hyper links in them. You probably figured that out already, but I just thought I would say it anyway.

Thanks!

On Jul 12, 2016, at 5:11 PM, Brett Johnson <brett.johnson@RACKSPACE.COM> wrote:

Next page of updates is here:
https://support.rackspace.com/how-to/cloud-backup-agent-logging-basics/

#1
In the first paragraph, this line:
and you can use it for detailed logging when troubleshooting a problem with Rackspace Support.

should be this:
and it can produce detailed logging, to help with troubleshooting a problem with Rackspace Support.

#2
Under Log configuration file, the first paragraph should be:
The log configuration file is named log4cxx.xml and it uses log4j syntax. The default configuration will differ between Windows and Linux only in the target log file path; otherwise, it will look like this example of a Windows configuration file:

#3
The example XML for Log configuration file should be replaced with this:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd"[]>
<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
  <appender name="FILE" class="org.apache.log4j.RollingFileAppender">
    <param name="File" value="C:\ProgramData\Driveclient\log\driveclient.log" />
    <param name="MaxFileSize" value="500MB" />
    <param name="MaxBackupIndex" value="10" />
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern" value="[%d{yyyy-MM-dd HH:mm:ss}{GMT+0}|T%t|%-5p|%c|%C::%M(%L)] %m%n" />
    </layout>
  </appender>
  <appender name="ASYNC" class="org.apache.log4j.AsyncAppender">
    <appender-ref ref="FILE" />
  </appender>
  <root>
    <level value=“INFO" />
    <appender-ref ref="ASYNC" />
  </root>
</log4j:configuration>

#4
The first paragraph under Agent logging operations should be replace with this:
The CBU agent can store valuable troubleshooting information in a series of up to a dozen or so rolling log files. If a problem condition occurs, the logged information can be analyzed to diagnose the problem. To ensure the logs are recording the correct information it may be necessary to modify the configuration file for your agent and set the appropriate level value. (Please see below the section, titled, “Locations of Cloud Backup agent files,” to locate your log4cxx.xml config on Windows or Linux.)

#5
The bullet point:
INFO - Log informational messages that highlight the progress of the application.

should read like this:
INFO - Log informational messages that highlight the progress of the application. This is the default logging level for the CBU agent.

#6
Under Trace-level debugging, this sentence:
If you activate TRACE debugging you increase the risk of losing log information because of the large volume of data written to the logs in this mode.

Should be two sentences:
TRACE logging increases the risk of losing older log information because of the large volume of data written to the logs in this mode, depending on things like what operations are running, how long they run, etc. Under certain conditions, TRACE logging may write hundreds or even in the thousands of lines per second to the logs.

#7
Under Rolling logs, the first paragraph should be:
The default Cloud Backup agent logs are rolling logs, which means they have a maximum size and that a maximum number of logs are stored on a server. This sets a maximum boundary to help prevent logs from filling up the Cache volume (often the system volume) of the server. When logging capacity is reached, the primary log file is rolled over, and a new primary log file is started. As more log files are rolled over to the point that the maximum number of logs is reached, the oldest rolled log is deleted.

Also, under Rolling logs, the sentence:
In the following example log4cxx.xml configuration file, these values are set:

should read:
Below is an example log4cxx.xml configuration file, in which these values are set higher than the default:

Also, under Rolling logs, the example XML config should look like this:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd"[]>
<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
  <appender name="FILE" class="org.apache.log4j.RollingFileAppender">
    <param name="File" value="C:\ProgramData\Driveclient\log\driveclient.log" />
    <param name="MaxFileSize" value=“2000MB" />
    <param name="MaxBackupIndex" value="12" />
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern" value="[%d{yyyy-MM-dd HH:mm:ss}{GMT+0}|T%t|%-5p|%c|%C::%M(%L)] %m%n" />
    </layout>
  </appender>
  <appender name="ASYNC" class="org.apache.log4j.AsyncAppender">
    <appender-ref ref="FILE" />
  </appender>
  <root>
    <level value=“TRACE" />
    <appender-ref ref="ASYNC" />
  </root>
</log4j:configuration>

Also, under Rolling logs, the bullet point:
MaxFileSize: Unlimited (500 MB recommended)

should be:
MaxFileSize: “unlimited” (limited only by the size of the free space on the volume where the cache files reside)

And finally, under Rolling logs, after the MaxFileSize bullet, we need these two notes:
NOTE: MaxFileSize is the maximum size of each rolling log file. So a MaxFileSize of 1000MB and a MaxBackupIndex of 12 could result in approximately 13GB of logs written to the Cache volume (one current log and 12 rolled logs, each approximately 1000MB in size).

WARNING! The Cache volume is typically the system drive. Setting MaxFileSize to a value that will cause the system volume to fill up can have serious consequences on the server. This can include (but is not limited to) causing DB corruption of the CBU agent, causing restores to fail, as well as cleanups and backups to fail, and crippling the server in other ways. If you need a large amount of space for TRACE logging, make sure it is available on your system drive, with more room to spare for other apps and files. Alternatively, consider setting your log path in log4cxx.xml (param name=“File”) to a volume with sufficient space to hold the maximum amount of data that is generated by the logs. (See below the section, titled, “Locations of Cloud Backup agent files,” to locate your log4cxx.xml config on Windows or Linux.)

#8
Under Where to store saved logs, the paragraph should become two paragraphs, thus:
Logging in INFO mode (or lower) generates a relatively small amount of log volume, but verbose logging (such as DEBUG and TRACE) can quickly accumulate a large amount of data in a short period of time. The preferred method of saving log files should be through the Request Agent Log button on the server CBU System Details page; however, there may be times when this is impossible or impractical. In those cases, you may have to save the log files manually. Please see below the section, titled, “Locations of Cloud Backup agent files,” to locate your log4cxx.xml config on Windows or Linux. In that config will be a tag with “param name=‘File’” with the current path to your log files.

When saving log files manually, in order to keep the file sizes manageable, the saved logs should typically be compressed using a zip or archive utility. But even when they are compressed, log files are still sometimes too large to attach to a support ticket. In order to make your logs easily available to Rackspace Support, we recommend that you upload them to your Cloud Files account in a public container. From there, you can copy the download links for the log files and paste the links into your support ticket.

#9
Under Locations of Cloud Backup agent files, the bullet point:
Logs: /var/log

should read like this:
Logs: /var/log (This value may be different on your server, depending on your settings in log4cxx.xml under Configuration files.)

And the bullet point:
Logs: %ProgramData%\Driveclient\logs

should read like this:
Logs: %ProgramData%\Driveclient\logs (This value may be different on your server, depending on your settings in log4cxx.xml under Configuration files.)

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c31aca6a4a/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f2113607e0/how-to/).

**Comment by cyrichardson** [comment]
@kmsholcomb Would you have some time to edit the changes to this one?

**Comment by kmsholcomb** [comment]
Will do, @cyrichardson.

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. The attached Word doc and PDF contain my suggested edits. I looked at the whole article, and actually had some suggestions for rearranging some of the info! More than what you expected, I'm sure. :) Please let me know if you have any questions. Thanks!

[Cloud Backup agent logging basics_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/366826/Cloud.Backup.agent.logging.basics_editsKH.pdf)
[Cloud Backup agent logging basics_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/366827/Cloud.Backup.agent.logging.basics_editsKH.docx)

**Comment by cyrichardson** [comment]
@kmsholcomb Thanks a ton! I'll apply your edits today.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c0a878b28a/how-to/). :bow:

**Comment by catlook** [comment]
👍

**Pull request merged**
