### PR TITLE
Change public folder article title for technical accuracy

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1754

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c336cbc865/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-46fbfdc608/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @DonNateR, Just a few edits in the attached file. Let me know if you have any questions. Thanks!

[Public folder permissions for Exchange 2007 and 2010_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/690744/Public.folder.permissions.for.Exchange.2007.and.2010_editsKH.pdf)
[Public folder permissions for Exchange 2007 and 2010_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/690743/Public.folder.permissions.for.Exchange.2007.and.2010_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ae44e6955c/how-to/)

**Pull request merged**
