### PR TITLE
Create split-domain-routing.md

### PR DESCRIPTION
**Pull request by hikarutilmitt**

### CODE REVIEW

**Comment by nimbinatus** [comment]
Opened PR on the patch-18 branch, hikarutilmitt/rackspace-how-to#4

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-07b3abe04b/how-to/). :bow:

**Comment by nimbinatus** [comment]
Opened second PR on the patch-18 branch, hikarutilmitt/rackspace-how-to#14

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-44e7505f7e/how-to/). :bow:

**Pull request merged**
