### PR TITLE
reorg managed ops to app services

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 5258

Break out Managed Ops content into either service level articles in Account Management or into the new Application Services categories.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1129 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-70633ac24/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1130 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-77fb2b3cc/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1137 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-77fb2b3cc/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1169 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7cb16905c/how-to/). valid for 14 days

**Comment by stephamon** [comment]
This needs a little more work before it's really ready to be a PR, so closing for now.

**Pull request closed without merging**
