### PR TITLE
Renamed email address configuration for iphone

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-8f8dc9674e/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-97e3deb945/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e481b968a9/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bb0ff12c6d/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-20467afd4e/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-21510f287e/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b0df9444fe/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-754a6639be/how-to/).

**Comment by stephamon** [comment]
Hi @kmsholcomb can you take a look at this article?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8c7add9a99/how-to/)

**Comment by kmsholcomb** [comment]
Hi @stephamon. See my attached edits. Please let me know if you have any questions. Thanks!

[Renamed email address configuration for iPhone iOS_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1285923/Renamed.email.address.configuration.for.iPhone.iOS_editsKH.docx)
[Renamed email address configuration for iPhone iOS_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1285924/Renamed.email.address.configuration.for.iPhone.iOS_editsKH.pdf)

**Comment by WilliamLoy** [comment]
Thank you for the critique @kmsholcomb! I definitely understand your concerns in regards to rename config articles being redundant when a new set up article would be applicable in both instances. While that may work with mobile devices, it will not translate to desktop clients. For consistency, we decided to distinguish a rename config article from a new setup article so that context is still provided regardless of desktop or mobile workflow post-address rename.   
 
Hope that helps!

**Pull request merged**
