### PR TITLE
Remove hard to read email migration table

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1747 

- Add calendar color categories to items not migrated by Migration Wiz

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0768482cb9/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-adaa1d1024/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My edits are in the attached Word doc and PDF copy of it. Please let me know if you have any questions. Thanks!

[Items migrated during a Cloud Office migration_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/714837/Items.migrated.during.a.Cloud.Office.migration_editsKH.pdf)
[Items migrated during a Cloud Office migration_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/714838/Items.migrated.during.a.Cloud.Office.migration_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-924822bffb/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c3005b3740/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6ab4bbd522/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-8426d1b469/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
