### PR TITLE
Add OpenSSL and Elliptic Curve operations

### PR DESCRIPTION
**Pull request by cyrichardson**
At @BadCrumpany request.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 683 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-88fb5d613/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 686 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3c92359f6/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@BadCrumpany Would you like to review this new file here? 
Also, is cloud-servers the correct place for this new article on support.rackspace.com?

**Comment by rackernexus** [comment]
Build 687 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-378ad2935/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 688 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4cfc0da9e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 689 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4cfc0da9e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 690 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3b2148494/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 691 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c979a357e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 692 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ed2913ced/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 693 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e783312a6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 763 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8497d2e93/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
https://support-revs.staging.deconst.org/build-8497d2e93/how-to/elliptic-curve-operations/

**Comment by cyrichardson** [comment]
@BadCrumpany Here's a link to the published article: https://support.rackspace.com/how-to/elliptic-curve-operations/

**Pull request merged**
