### PR TITLE
replace rsync with InstanceSync

### PR DESCRIPTION
**Pull request by inflatador**
mainly sourced from my own article here: https://support.rackspace.com/how-to/migrate-gogrid-cloud-servers-to-rackspace-cloud/

### CODE REVIEW

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 866 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5d3752e84/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 868 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9be9bb688/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready for editing :)

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 870 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-225de1467/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 872 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-973237b41/how-to/). valid for 14 days

**Pull request merged**
