### PR TITLE
New article: RBAC for ticketing [MERGE MAY 16]

### PR DESCRIPTION
**Pull request by gairehari**
Please do not merge this now, we will be merging this change in few weeks once Reach UI is done with their changes.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ee548212e1/how-to/)

**Comment by gairehari** [comment]
Can we please make this change live on May 16 ?

**Comment by DonNateR** [comment]
We'll get this merged on May 16th @gairehari , thank you for your contribution!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e19756afaa/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-4730136e64/how-to/). :bow:

**Pull request merged**
