### PR TITLE
slight formatting adjustment

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 2115 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-781f61334/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 2117 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-781f61334/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 2118 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-87f57eb20/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2120 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-388b3751e/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2122 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-eefcbb537/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 2134 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cf8656420/how-to/). valid for 14 days

**Comment by stephamon** [comment]
build me

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 2135 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cf8656420/how-to/). valid for 14 days

**Comment by catlook** [comment]
permalink: ngfw-feature-matrix

**Comment by rackernexus** [comment]
Build 2136 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-caa67beca/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2138 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-563a165c1/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2140 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-577cb4401/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2142 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c3da72ab9/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2144 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-86c4fb117/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
ngfw-feature-matrix

**Comment by rackernexus** [comment]
Build 2146 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f1bfacc3e/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2147 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f1bfacc3e/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2148 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-301b5bb7c/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 2149 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-895d9f66a/how-to/). valid for 14 days

**Comment by catlook** [comment]
Are you prepared to publish as is?

**Pull request closed without merging**
