### PR TITLE
Changed name of 'Next section' link to match destination page title: INFODEV-1050

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by RackerKate** [comment]
Addresses issue #2472.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-6cd2b642f8/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4ad5a2a078/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-f43ee88831/how-to/). :bow:

**Comment by cyrichardson** [comment]
@RackerKate @DonNateR I'll look at this now.

**Comment by RackerKate** [comment]
Sorry. @ReneeRendon said to just delete that section, so I went with it.

**Comment by cyrichardson** [comment]
No worries, @RackerKate. I'll give the whole article a look. Back with you shortly on it.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[managing-role-based-access-control-rbac_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1721005/managing-role-based-access-control-rbac_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5565b57fff/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-baed4af71f/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-895331f04e/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-057dac8f8d/how-to/)

**Comment by RackerKate** [comment]
Out for SME review/audit.

**Comment by RackerKate** [comment]
Approved by SME.

**Pull request merged**
