### PR TITLE
Add multi-factor auth in myracksapce portal article

### PR DESCRIPTION
**Pull request by kylelaffoon**
- Completes #1363

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-73167b29b3/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-06548441be/how-to/)

**Comment by ReneeRendon** [comment]
Hi Kyle,

I see one thing that needs to be corrected and have two questions.

- The section called: "Configure account-wide multi-factor authentication settings from an
Administrator account" needs to be corrected. It is partially a heading and partially para.

- Should "Identity" be capitalized (line 37)? I'm thinking it should be lowercase.

- Do any redirects need to be set up since you are changing the permalink? Or is this a completely new article?

**Comment by kylelaffoon** [comment]
@ReneeRendon This is a new article. Permalink was wrong because I had started with a copy of another article as a template. I'll apply your changes listed above

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-2233872123/how-to/). :bow:

**Pull request closed without merging**
