### PR TITLE
Merge rescue mode articles & retire Cloud Essentials versions.

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9942fbeb57/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0a591d1d5c/how-to/).

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[rescue-mode_cyrEdits2.docx](https://github.com/rackerlabs/rackspace-how-to/files/2520872/rescue-mode_cyrEdits2.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f6d6aceb60/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f213c89d9d/how-to/)

**Pull request merged**
