### PR TITLE
Audit article on streaming content w/ Cloud Files: INFODEV-2706

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bcddb5c75d/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
Only 1 suggestion, @RackerKate: 
[getting-started-with-cloud-files-streaming_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2674374/getting-started-with-cloud-files-streaming_cyrEdits.docx)

**Pull request merged**
