### PR TITLE
incorporate sme edits

### LINKED ISSUE #1647: Edit to "Email access options during an email migration"

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1647

### CODE REVIEW

**Comment by stephamon** [comment]
@kmsholcomb can you add this to your editing list please? Thanks!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-08395d25b3/how-to/).

**Comment by kmsholcomb** [comment]
Hi @stephamon. My edits are attached. Maybe I tinkered with it too much. Sometimes I start to doubt myself. :) But the whole intro seemed a little disjointed, so I tried to straighten it out a bit. Anyway, please let me know if you have any questions. Thanks!

[Email access options when migrating to Rackspace_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/625673/Email.access.options.when.migrating.to.Rackspace_editsKH.pdf)
[Email access options when migrating to Rackspace_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/625674/Email.access.options.when.migrating.to.Rackspace_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bafe729c81/how-to/).

**Pull request merged**
