### PR TITLE
INFODEV-3203

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-de2fe31a40/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7ee985fb74/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0b83ec12a6/how-to/)

**Comment by cyrichardson** [comment]
@WilliamLoy On this one now.

**Comment by cyrichardson** [comment]
@WilliamLoy Suggested changes here: 
[rackspace-directory-sync-best-practices-and-common-errors_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2773562/rackspace-directory-sync-best-practices-and-common-errors_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-13d59dcac8/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d650328129/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6ec60a3d9c/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-acb7719121/how-to/)

**Pull request merged**
