### PR TITLE
Create Add Cloud Networks Interface to Existing Cloud Server

### PR DESCRIPTION
**Pull request by BadCrumpany**
Migrating Articles from the Community site to the Knowledge Center

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-28648121c0/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-5533ebf325/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-ebe2e65d4e/how-to/)

**Comment by RackerKate** [comment]
Due to build issues, replaced by #3086.

**Pull request closed without merging**
