### PR TITLE
Troubleshoot DNS experiment article: INFODEV-2630

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8413fdfc81/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d398ba41f7/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[dns-overview-and-troubleshooting-articles_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2543878/dns-overview-and-troubleshooting-articles_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-eb8fbc592b/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Reviewed. The backslashes aren't appearing. :-(

**Comment by cyrichardson** [comment]
Ack! Thanks, @RackerKate!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-25a80778ca/how-to/). :bow:

**Pull request merged**
