### PR TITLE
full audit

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready for editing :)

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by rackernexus** [comment]
Build 676 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ffce65b62/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 677 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0ea1ca397/how-to/). valid for 14 days

**Pull request merged**
