### PR TITLE
Audit article: INFODEV-2604

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7a00d343e0/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Looks like something odd has happened in the build ^^.

**Comment by cyrichardson** [comment]
@RackerKate Maybe making a small change to force the build again will fix the build problem. I've not seen that message before ("Pending - Build triggered. sha1 is merged.").

**Comment by edwardjrp** [comment]
@RackerKate @cyrichardson Please ignore this pending checks for the moment. We are undergoing configurations for docs content repositories in the deconst migration process

**Pull request merged**
