### PR TITLE
[WIP] full audit rbac orchestration

### LINKED ISSUE #1768: Full Audit: Permissions matrix for Cloud Orchestration
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/permissions-matrix-for-cloud-orchestration.md

- [x] Edit formatting to meet standards
- [x] SME review
- [x] Editor review
- [x] Quality checklist

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1768 

Update formatting to match standard

### CODE REVIEW

**Comment by stephamon** [comment]
Currently in SME hands for review

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e28f7f63dd/how-to/)

**Comment by stephamon** [comment]
Approved by Aaron M. as still up-to-date.

@kmsholcomb could you give this one a look-over? Thank you!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e2dc48572b/how-to/).

**Comment by kmsholcomb** [comment]
Will do, @stephamon

**Comment by kmsholcomb** [comment]
Hi @stephamon. Just a few tiny marks. :)

[Permissions matrix for Cloud Orchestration_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/720061/Permissions.matrix.for.Cloud.Orchestration_editsKH.pdf)
[Permissions matrix for Cloud Orchestration_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/720060/Permissions.matrix.for.Cloud.Orchestration_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b665583e6e/how-to/)

**Pull request merged**
