### PR TITLE
Wl rse mac hex migrations

### PR DESCRIPTION
**Pull request by stephamon**
takes over #2172

### CODE REVIEW

**Comment by stephamon** [comment]
@kmsholcomb can you edit this please?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c48a4f4f79/how-to/)

**Comment by kmsholcomb** [comment]
Will do!

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits are attached. Please let me know if you have any questions. Thanks!

[Prepare Mac users for Rackspace Email to Microsoft Exchange migration_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1170406/Prepare.Mac.users.for.Rackspace.Email.to.Microsoft.Exchange.migration_editsKH.pdf)
[Prepare Mac users for Rackspace Email to Microsoft Exchange migration_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1170405/Prepare.Mac.users.for.Rackspace.Email.to.Microsoft.Exchange.migration_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-143dc74125/how-to/)

**Pull request merged**
