### PR TITLE
Add email mailboxes

### PR DESCRIPTION
**Pull request by WilliamLoy**
I am sending the screen shots in an email as well. 

addmailboxsc1
addmailboxsc2
addmultmailboxessc1
addrselicensesc1
addrselicensesc2

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-301ccf1a47/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9d7f1f7410/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b373287bc2/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-54cd901ffc/how-to/)

**Comment by DonNateR** [comment]
Moved to PR #2100

**Pull request closed without merging**
