### PR TITLE
Create types-of-ssl-certificates

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1762 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-224223b5d/how-to/). valid for 14 days

**Pull request merged**
