### PR TITLE
Create article on how to reset a VPN user password

### PR DESCRIPTION
**Pull request by csilva235**
New article for dedicated firewalls.

Submitted on behalf of author.

### CODE REVIEW

**Comment by chri2547** [comment]
build me

**Comment by rackernexus** [comment]
Build 2043 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3fb0c55c7/how-to/). valid for 14 days

**Comment by chri2547** [comment]
build me

**Comment by rackernexus** [comment]
Build 2046 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-802c847f0/how-to/). valid for 14 days

**Comment by catlook** [comment]
on it

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
@chri2547 I kicked off a new build. After fixing the meta, we should get a preview this time!

**Comment by rackernexus** [comment]
Build 2049 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9e27d2e4a/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2052 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b4730b155/how-to/). valid for 14 days

**Comment by catlook** [comment]
Finally got a real preview: https://support-revs.staging.deconst.org/build-b4730b155/how-to/reset-your-cisco-asa-vpn-user-password-by-using-the-rackspace-portal/

**Pull request merged**
