### PR TITLE
[WIP] full audit cdn permissions matrix

### LINKED ISSUE #1772: Full Audit: Permissions matrix for Rackspace CDN
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-cdn/permission-matrix-for-rackspace-cdn.md

- [x] Update formatting to match standard
- [x] SME review
- [x] Editor review
- [ ] Quality checklist

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1772 

Update formatting to match standard and API reference

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-4b3287e640/how-to/). :bow:

**Comment by stephamon** [comment]
Being reviewed by SME.

**Comment by stephamon** [comment]
SME approved! 

@kmsholcomb could you give this a look? It's probably fine, but your discerning eye is appreciated!

**Comment by kmsholcomb** [comment]
Will do, @stephamon.

**Comment by kmsholcomb** [comment]
Hi @stephamon. Just a couple of edits in the content preceding the table. I think that we added the extra RBAC wording when I was editing a couple of these RBAC articles for Laura. Thanks!

[Permissions Matrix for Rackspace CDN_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/714881/Permissions.Matrix.for.Rackspace.CDN_editsKH.pdf)
[Permissions Matrix for Rackspace CDN_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/714882/Permissions.Matrix.for.Rackspace.CDN_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-262d3df980/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9d6f2427c4/how-to/).

**Pull request merged**
