### PR TITLE
Create configue email encryption o365

### PR DESCRIPTION
**Pull request by wstubbs12**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@cyrichardson  this one is ready as well

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1607 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0862139c6/how-to/). valid for 14 days

**Pull request merged**
