### PR TITLE
broken link fixed

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by viridaria** [comment]
build me

**Comment by viridaria** [comment]
linked changed from 
https://www.rackspace.com/cloud/servers/features#images 
to
https://support.rackspace.com/how-to/cloud-images-faq/

Already ok'ed by Dan Verson

**Comment by rackernexus** [comment]
Build 2173 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d0e11e02c/how-to/). valid for 14 days

**Comment by catlook** [comment]
this was a fix to an existing article!

**Pull request merged**
