### PR TITLE
New Article: Keep a cloud server up to date

### PR DESCRIPTION
**Pull request by DonNateR**
From PR #2193

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f99383917f/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-7773059c14/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-23a649a90c/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9ceb33758b/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits are attached. I think that there is far too much basic instruction in the Linux procedures, so most of my edits there are just comments to simplify! Please let me know if you have any questions. Thanks!

[Keep a cloud server up to date_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1265226/Keep.a.cloud.server.up.to.date_editsKH.docx)
[Keep a cloud server up to date_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1265227/Keep.a.cloud.server.up.to.date_editsKH.pdf)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0ca0015c69/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8705fa8351/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-921cce3bb5/how-to/). :bow:

**Comment by stephamon** [comment]
👍

**Pull request merged**
