### PR TITLE
Infodev 4086

### PR DESCRIPTION
**Pull request by WilliamLoy**
@cyrichardson can I get your eyes on this when you have a chance please?

### CODE REVIEW

**Comment by cyrichardson** [comment]
On it, @wiliamLoy.

**Comment by cyrichardson** [comment]
@WilliamLoy On it.

**Comment by rackernexus** [comment]
Build 181 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-af1ea2caf/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@WilliamLoy Please recheck editorial changes and see if you agree with them.

**Comment by rackernexus** [comment]
Build 182 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a872109e6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 194 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-88dabf8f3/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 196 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-46c40732d/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 197 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3f15e88d7/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 199 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a2f4e12d9/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 201 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f114c728d/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 203 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6a002f8de/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 205 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fdb03c80e/how-to/). valid for 14 days

**Pull request merged**
