### PR TITLE
Changed to use headings rather than bold

### PR DESCRIPTION
**Pull request by cyrichardson**
so spaces in published article is better

### CODE REVIEW

**Comment by cyrichardson** [comment]
@tofarley This is just a formatting changes so the information that was formerly bolded isn't right against the bottom of the table that precedes it. Please review and let me know what you think.

**Comment by rackernexus** [comment]
Build 492 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c2ce78dd8/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 495 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2a4c70146/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 497 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3773c1653/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 499 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-15105e4b4/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 500 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-15105e4b4/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 502 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fea340a11/how-to/). valid for 14 days

**Pull request merged**
