### PR TITLE
Updating Parse How-To

### PR DESCRIPTION
**Pull request by chrishultin**
Updating the Parse How-To to accurately match the required steps.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4f41e28033/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-ff11ee169b/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits are in the attached Word doc (and PDF copy of it). Most of the edits are around formatting (creating steps) and word tightening, but I do have a few questions. Please let me know if _you_ have any questions. Thanks!

[Migrating from Parse to Rackspace_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/731285/Migrating.from.Parse.to.Rackspace_editsKH.pdf)
[Migrating from Parse to Rackspace_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/731286/Migrating.from.Parse.to.Rackspace_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-20dd00a537/how-to/). :bow:

**Comment by DonNateR** [comment]
Changes moved to PR #1799

**Pull request closed without merging**
