### PR TITLE
Replaced HTML Entities

### PR DESCRIPTION
**Pull request by moebrowne**
There were HTML entities in the content that show the entity code rather than the intended character

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @moebrowne good catch! Can you bring the branch back up to date and I'll merge it?

**Comment by moebrowne** [comment]
Hi @stephamon it should now be up to date!

**Comment by stephamon** [comment]
@moebrowne Ah, sorry! One more time!

**Comment by moebrowne** [comment]
@stephamon No problem, should be good to go now :D

**Pull request merged**
