### PR TITLE
Create ntfs permissions configuration and troubleshooting

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1232 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-aef14819d/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1242 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ef8d4c0f2/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1243 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-364e92817/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1244 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1d52db43c/how-to/). valid for 14 days

**Comment by catlook** [comment]
Sent for editorial review

**Comment by rackernexus** [comment]
Build 1250 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d124a6425/how-to/). valid for 14 days

**Pull request merged**
