### PR TITLE
Update Cloud Backup control panel links to use 'https' and clarify language: INFODEV-2693

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-550d028f81/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review please.

**Comment by cyrichardson** [comment]
@RackerKate On it in about an hour (after ATX meeting - a panel of leaders here speaking)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-477ae8d19b/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please recheck with new wording.

**Comment by cyrichardson** [comment]
@RackerKate On this one now.

**Pull request merged**
