### PR TITLE
Create media-server-comparison

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by chri2547** [comment]
@catlook , this looks fine to me.

**Comment by catlook** [comment]
@chri2547 review my edits and see if you like them.

**Comment by chri2547** [comment]
build me

**Comment by rackernexus** [comment]
Build 2219 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-20bf182cd/how-to/). valid for 14 days

**Pull request merged**
