### PR TITLE
first draft

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-14867b35ab/how-to/)

**Comment by WilliamLoy** [comment]
@cyrichardson  ready for your expertise

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by cyrichardson** [comment]
@WilliamLoy Suggestions here: 
[working-with-audio-and-voice-calls-in-hosted-skype-for-business_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2967785/working-with-audio-and-voice-calls-in-hosted-skype-for-business_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-16842b5f93/how-to/)

**Pull request merged**
