### PR TITLE
Reset an Active Directory user password

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1261 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a8d8aaa1b/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
On it with editorial review, @BadCrumpany.

**Comment by rackernexus** [comment]
Build 1263 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5a85103ef/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1264 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-863159fc5/how-to/). valid for 14 days

**Pull request merged**
