### PR TITLE
Create enable-ssh-remote-root-login-ubuntu-and-centos

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1830 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d344bfb40/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1832 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-007b8d846/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1835 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a6553b1a1/how-to/). valid for 14 days

**Pull request merged**
