### PR TITLE
Update rackspace-cloud-essentials-centos-configuring-a-user-in-vsftpd.md

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9752b6ef67/how-to/)

**Comment by kylelaffoon** [comment]
- Fixes #1085

**Comment by kylelaffoon** [comment]
Aaron Davis reported that the current draft will only work for chroot with SSH and SFTP. He is testing the simpler option with vsftpd and sending us feedback.

**Comment by kylelaffoon** [comment]
Covered by #1097

**Pull request closed without merging**
