### PR TITLE
Create create-user-and-grant-permissions-in-mysql

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1848 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ba1b02f7e/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1851 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-666c08a77/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1852 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-666c08a77/how-to/). valid for 14 days

**Pull request merged**
