### PR TITLE
audit articles with sme feedback

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 5473 and 5478

### CODE REVIEW

**Comment by stephamon** [comment]
Also 5472

**Comment by rackernexus** [comment]
Build 1396 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b363bba74/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1398 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3fab293a7/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1401 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ef9c8381e/how-to/). valid for 14 days

**Pull request merged**
