### PR TITLE
New Article: Firewall manager v2: port-groups

### PR DESCRIPTION
**Pull request by trevorbecker**
1st draft article 3
sending email with images soon

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bf819ceebb/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f47add6b6f/how-to/).

**Comment by stephamon** [comment]
@kmsholcomb can you add this to your editing list please?

**Comment by kmsholcomb** [comment]
Will do. I am editing the Firewall Manager v2 object groups article for Nate right now.

**Comment by kmsholcomb** [comment]
Hi @stephamon. See my comment and edits for https://github.com/rackerlabs/rackspace-how-to/pull/1923. Because the articles are similar, I think you can apply many of those edits to this one. I'll be happy to look at this article after you've updated it accordingly. Thanks!

**Comment by trevorbecker** [comment]
@stephamon per comments in #1923 

the term "port-group" will remain, since it is a Cisco syntax term that requires the dash

**Comment by stephamon** [comment]
Moved to #1938 to add images and editor feedback

**Pull request closed without merging**
