### PR TITLE
[WIP] Add new troubleshooting article

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1441.

- [x] SME review
- [x] Editorial review

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-eadcafbf13/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a418702cb1/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f93c420e68/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR: My suggested edits are in the attached Word doc (and PDF copy of it). There were some formatting issues, mostly with indented code, so pay close attention to that. Otherwise, just many nitpicky edits, and some suggestions to put the content under some of the steps into bullets. Please let me know if you have any questions about anything. Thanks!

[Troubleshooting when your website is down_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/487787/Troubleshooting.when.your.website.is.down_editsKH.pdf)
[Troubleshooting when your website is down_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/487786/Troubleshooting.when.your.website.is.down_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dac114224a/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2bddad607b/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-2882cd560a/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
