### PR TITLE
[WIP] Add email migration preparation article

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes issue #1377 

Both articles in this pull request need to undergo a review:

- [x] SME review
- [x] Editorial review

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a19059d04b/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6a3abef733/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6b1c271094/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-77c460b99b/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-71e4594196/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e42d3ea551/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. The attached docs have my edits (the PDFs are copies of the Word docs). Please let me know if you have any questions. Thanks!

[Prepare POP IMAP and Exchange mail servers for migration_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/448076/Prepare.POP.IMAP.and.Exchange.mail.servers.for.migration_editsKH.pdf)
[Prepare POP IMAP and Exchange mail servers for migration_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/448078/Prepare.POP.IMAP.and.Exchange.mail.servers.for.migration_editsKH.docx)
[Migrate your email by using the Self Service tool_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/448077/Migrate.your.email.by.using.the.Self.Service.tool_editsKH.pdf)
[Migrate your email by using the Self Service tool_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/448079/Migrate.your.email.by.using.the.Self.Service.tool_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9d9824df31/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-964a16d277/how-to/).

**Comment by ReneeRendon** [comment]
-The link in the note at the top states that 'If you want to use the full version, see Accessing the full version of MigrationWiz.'  When you follow that link it takes you to the article named "Access the full version of MigrationWiz". https://staging.developer.rackspace.com/support.rackspace.com/build-964a16d277/how-to/accessing-the-full-version-of-migrationwiz/
You may want to add the word Migration between Self-Service and Tool in the link in the first paragraph of the "Full version" article.

-In the second to last bullet point under "Before you Migrate" , the word "tell" is misspelled.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-579902cdfc/how-to/)

**Comment by DonNateR** [comment]
@ReneeRendon: I've addressed your first note in PR #1426. I'll also add a redirect since the metadata changed. I thought you were referencing a different pull request when we spoke earlier :) 

The typo has also been fixed. Merge when ever you are ready.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f5b4f82178/how-to/)

**Comment by ReneeRendon** [comment]
Looks great!

**Pull request merged**
