### PR TITLE
Localusermgmt

### PR DESCRIPTION
**Pull request by Sterling463**
@stephamon last one

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 954 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0d77cd2b9/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 957 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-abf30b898/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 960 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-affd57e92/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
Build me

**Comment by rackernexus** [comment]
Build 965 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-52230615e/how-to/). valid for 14 days

**Pull request merged**
