### PR TITLE
Create Investigating Compromised Servers

### PR DESCRIPTION
**Pull request by BadCrumpany**
Migrating article from the community to the knowledge center.  This article is very comprehensive and the two articles found currently in the knowledge center focus on specific issues.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-2ad48624fa/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c97fa04cbc/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d219a9f4a8/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dc4db7a873/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[investigate-compromised-servers_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2770996/investigate-compromised-servers_cyrEdits.docx)

**Pull request merged**
