### PR TITLE
Add TriCore Intro to DBs FAQ article: INFODEV-1174

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4051994930/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c4abadaf32/how-to/)

**Comment by cyrichardson** [comment]
@RackerKate Minor suggestions here: 
[intro-to-databases-faq_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1939495/intro-to-databases-faq_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-25260304b8/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1925db1d90/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e40bfe8f61/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-11b1e8294b/how-to/)

**Comment by RackerKate** [comment]
The divider before the "General" section doesn't appear in the updated preview, but it's there in the code.

**Pull request merged**
