### PR TITLE
Update to Netsec spheres of support from PR#3208

### PR DESCRIPTION
**Pull request by abekele0413**
I added intro lines requested from last PR #3208 and inserted one blank line below "General topics"

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-2fe7124428/how-to/)

**Comment by catlook** [comment]
reviewing

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c5e9f8f794/how-to/). :bow:

**Pull request closed without merging**
