### PR TITLE
Community Article - Overview of Managed Windows Patching Service: INFODEV-3540

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-068e840bd3/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-07b7edb9af/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-baf9a59d73/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just suggest the registered trademark for Windows as shown here:
[overview-of-the-managed-windows-patching-service_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2870917/overview-of-the-managed-windows-patching-service_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-de6ab9828f/how-to/). :bow:

**Pull request merged**
