### PR TITLE
Create article

### PR DESCRIPTION
**Pull request by BadCrumpany**
This was an article that was in the Rackspace Community before it was decommissioned.  There has been a request to have the article on the support.rackspace.com site so it can be accessible.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e8cbe148ea/how-to/)

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
rebuild me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by cyrichardson** [comment]
@catlook Editorial changes applied for your review. You might need to check that the link https://curl.haxx.se/ca/cacert.pem goes to the right place. I got kind of strange results when I clicked on it. Thanks!

**Comment by catlook** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Pull request merged**
