### PR TITLE
[RPC-OpenStack] Remove outdated RPC security doc

### PR DESCRIPTION
**Pull request by major**
The RPC security document is really old and should be removed
and replaced with something else. This patch removes it for now.
It's not in a document index at the moment, so it should be safe
to remove.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c643377e16/how-to/)

**Comment by kencjohnston** [comment]
So the repeal first and replace tactic. I like it.

**Comment by DonNateR** [comment]
@major: We'll get this removed ASAP. Is there an article you want this redirected to?

**Comment by major** [comment]
@DonNateR There's not a good doc yet. We're laying out an outline for a new one.

**Comment by stephamon** [comment]
redirected with https://github.com/rackerlabs/nexus-control/pull/747

**Pull request merged**
