### PR TITLE
Audit monitoring-cloud-databases-in-the-cloud-control-panel: INFODEV-1361

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9ed36921a1/how-to/). :bow:

**Comment by ayersek64** [comment]
This PR should be reviewed by Reach and/or Ops team members.

**Comment by ayersek64** [comment]
Memory alarm intro:
The following criteria returns a Warning status when the amount of memory that has been allocated is above 80% of the available memory, and returns a Critical status when the amount of memory that has been allocated is above 90% of the available memory.

Network alarm intro:
The following criteria returns a Warning status when the rate of bytes received is above 18350080B per second, and returns a Critical status when the rate of bytes received is above 24903680B per second.

if (rate(metric['rx_bytes']) > 24903680) {
            return new AlarmStatus(CRITICAL, "Network receive rate on eth0 is above your
          critical threshold of 24903680B/s");
          }
 
         if (rate(metric['rx_bytes']) > 18350080) {
            return new AlarmStatus(WARNING, "Network receive rate on eth0 is above your
         warning threshold of 18350080B/s");

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3ec242289a/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7d135d2906/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-d6873a9eb5/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f2ea58cb0c/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-92c95b4180/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-181f133633/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate In the queue, on it shortly.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[monitoring-cloud-databases-in-the-cloud-control-panel_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2167942/monitoring-cloud-databases-in-the-cloud-control-panel_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5f40288c83/how-to/)

**Pull request merged**
