### PR TITLE
Add Jellyfish link: infodev-2400

### PR DESCRIPTION
**Pull request by RackerKate**
Will do a full audit via a separate PR.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0304586d97/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[nslookup-checking-dns-records-on-windows_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2456391/nslookup-checking-dns-records-on-windows_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8a78e4d79c/how-to/)

**Pull request merged**
