### PR TITLE
[MVP] Rackspace Migration Manager FAQ

### LINKED ISSUE #1839: [MVP] Rackspace Migration Manager: Create FAQ article
Use information from doc audit to create FAQ article - Internally Documented

Provide link to the PR for this issue to the PM, Trent Gillaspie, for review/additions.

### PR DESCRIPTION
**Pull request by cyrichardson**
Moved from FAWS folder to Rackspace Migration Manager folder.

Fixes #1839

Replaces PR #1840

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7b0fc7f50f/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b07a90bf2e/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-50fd60eefa/how-to/)

**Comment by cyrichardson** [comment]
@amitgandhinz Trent reviewed these earlier. They are from https://one.rackspace.com/display/OPS/Migration+Beta+Comms+-+Customer+Facing+Racker+FAQ%27s

I thought you might want to review them when you have time.

**Comment by amitgandhinz** [comment]
do we still want to refer to it as a Beta Migration Program?  Given that the rollout will be to selected customers within range, and those customers do not need to reach out to their AM to participate?

**Comment by cyrichardson** [comment]
@trentgillaspie See Amit's question above.

**Comment by cyrichardson** [comment]
Moving to blocked status until product launch.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-29c11d5dfe/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e082ff4118/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d1c3a198ad/how-to/)

**Comment by cyrichardson** [comment]
Ready for MVP launch

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424

**Pull request closed without merging**
