### PR TITLE
added manual execution of secure installation utility

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 343 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2f7a84892/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 345 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c2c639c79/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 347 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8ec78a9e3/how-to/). valid for 14 days

**Pull request merged**
