### PR TITLE
[WIP] update per issue #1730

### LINKED ISSUE #1730: Edit to "Add Rackspace Email mailboxes"
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email/add-rackspace-email-mailboxes.md

1. Current Section without Changes:  No mention of how to add mailboxes when "Add Mailbox" button is not enabled.
*Proposed Changes:* Add in a section to cover instructions for customers whose "Add Mailboxes" button is greyed out in its own textbox and/or as a block indent. Please see the following text for the proposed addition of text and screenshot: 

"NOTE: If your “Add Mailbox” button is “greyed out,” then you will need to first add the necessary license(s) to your account. 
 
"Add license(s)
1.	Log in to the Cloud Office Control Panel using your Rackspace Cloud Office Admin ID and password.
2.	In the Go to section list, choose Rackspace Email.
3.	Click the Email Accounts tab.
4.	If you have multiple domains, select the appropriate domain name.
5.	Click Upgrade this plan.
6.	Within the appropriate section, add the desired number of mailboxes.
7.	Click Continue.
8.	Review the Order Summary and purchase the licenses by clicking Complete Order."

addmailbox_greyedout

2. Current Section without Changes: From all sections, first instruction, "Log in to the Cloud Office Control Panel using your Rackspace username and password." is too vague; customers may confuse their "Rackspace username and password" with their email account or MyCustomer portal credentials. 
*Proposed Changes:* Since a customer may have multiple Rackspace usernames/passwords, clarify the sentence, "Log in to the Cloud Office Control Panel using your Rackspace Cloud Office Admin ID and password."

3. Current Section without Changes: From section "Add a Single Mailbox," number six, directions for User Name reads: "Enter the first part of the email address. For example, myname@mydomain.com."
*Proposed Changes:* Clarify "the first part" and the example. "User Name: Enter the first part of the email address – the part before the @ symbol. For example: “myname” (without quotes) from myname@mydomain.com"

4. Current Section without Changes: From section "Add Multiple Mailboxes," there is a screenshot which displays the button "Choose File"
*Proposed Changes:* Replace screenshot with attached, updated screenshot which displays the button "Browse..."
addmailboxes

5. Current Section without Changes: From section "Add Multiple Mailboxes," number seven, "In the Import File section, click the Choose File button and locate and select the CSV or Excel file that you created."
*Proposed Changes:* Replace "Choose File" with "Browse..." since this is how it appears in the Cloud Office Control Panel. 

See attached document with my proposed changes:
[Add Rackspace Email mailboxes.docx](https://github.com/rackerlabs/rackspace-how-to/files/672274/Add.Rackspace.Email.mailboxes.docx)

### PR DESCRIPTION
**Pull request by nimbinatus**
Updating with new data per SME request. Also removed unneccesary screenshot (added new one to assets to ensure it is there if we need it).

Fixes #1730.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-50e8924719/how-to/)

**Comment by nimbinatus** [comment]
@kmsholcomb, can you add this to your editing queue? An SME sent in the changes as issue #1730. I'm also debating about the last screenshot. Do you think it is necessary?

**Comment by kmsholcomb** [comment]
Hi. @nimbinatus. My edits are in the attached Word doc (and PDF copy of it). I've got a few comments that pertain to that last screenshot. (And no, I don't think it is necessary.) Please let me know if you have any questions. Thanks!

[Add Rackspace Email mailboxes_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/683350/Add.Rackspace.Email.mailboxes_editsKH.pdf)
[Add Rackspace Email mailboxes_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/683351/Add.Rackspace.Email.mailboxes_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-604c02ee1a/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3239554d82/how-to/). :bow:

**Comment by DonNateR** [comment]
LGTM

**Pull request merged**
