### PR TITLE
Audit article: INFODEV-2859

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d3ffec5ea7/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-382fe6ecf0/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
Just a couple of suggestions, @RackerKate:
[streaming-audio-and-video-with-html-5_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2677368/streaming-audio-and-video-with-html-5_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4c54f63000/how-to/)

**Pull request merged**
