### PR TITLE
full audit install mysql on ubuntu

### PR DESCRIPTION
**Pull request by stephamon**
apply SME edits

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at this for me?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-729a4a68fd/how-to/)

**Comment by cyrichardson** [comment]
Will do!

**Comment by cyrichardson** [comment]
@stephamon Suggestions here 
[installing-mysql-server-on-ubuntu_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1807793/installing-mysql-server-on-ubuntu_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cef729077c/how-to/)

**Pull request merged**
