### PR TITLE
Cross-linked with new-user workflow article

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 244 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-10146aa56/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 245 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8508b77ae/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 246 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-293648038/how-to/). valid for 14 days

**Comment by catlook** [comment]
publish monday 7/29

**Pull request merged**
