### PR TITLE
Updated RMS Network Defense Language - 4-1-2020

### PR DESCRIPTION
**Pull request by Power2ouse**
I was asked by Kayse Horton to review the material and update as needed. I have done so, and my changes in the fork.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1524 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-940c0d0bd/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by edwardjrp** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by stephamon** [comment]
build me

**Comment by rackernexus** [comment]
Build 1649 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-858266b39/how-to/). valid for 14 days

**Pull request merged**
