### PR TITLE
update purchase ssl cert article

### PR DESCRIPTION
**Pull request by stephamon**
Update and rework existing SSL article

JIRA 2587

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c4684d555b/how-to/).

**Comment by cyrichardson** [comment]
This one will be next, @stephamon.

**Comment by cyrichardson** [comment]
@stephamon A few suggested changes here: 
[purchase-or-renew-an-ssl-certificate_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2506822/purchase-or-renew-an-ssl-certificate_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d9d97d9199/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bd0df5df29/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-95d564de70/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b8b5de8c72/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-442a0909f3/how-to/)

**Pull request merged**
