### PR TITLE
Create truncating-and-shrinking-log-files-in-sql-server

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2015 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-443bf655a/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2017 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a4b5b6b8c/how-to/). valid for 14 days

**Pull request merged**
