### PR TITLE
Community Linux logs

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-cba6bd4384/how-to/). :bow:

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[linux-log-files_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2793156/linux-log-files_cyrEdits.docx) and 
[checking-running-services-on-linux_cyrEdits2.docx](https://github.com/rackerlabs/rackspace-how-to/files/2793159/checking-running-services-on-linux_cyrEdits2.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-88fd8a81b3/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-737df3e2d3/how-to/)

**Pull request merged**
