### PR TITLE
Create basic linux user management document.

### PR DESCRIPTION
**Pull request by csilva235**
Article for how to create basic users in a Linux OS.

This article currently has placeholders for links to how to add sudo users in Linux for RHEL and Debian.

Both of those articles are being submitted today.

### CODE REVIEW

**Comment by csilva235** [comment]
Placeholder links point to new submissions:

#3660 and #3661

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1675 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3c5297411/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1676 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3c5297411/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1681 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6c1f9dbdb/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1682 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8724c7e38/how-to/). valid for 14 days

**Pull request merged**
