### PR TITLE
Grammar: change "is" to "are"

### PR DESCRIPTION
**Pull request by offthewoll**
Changed "Communications between the Active Directory password hook and
Directory Sync **_is_** secured with Microsoft Windows Communication
Foundation (WCF).." to "Communications between the Active Directory password hook and
Directory Sync **_are_** secured with Microsoft Windows Communication
Foundation (WCF).." since the subject of the sentence, "Communications", is plural.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 306 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-98dd87ec5/how-to/). valid for 14 days

**Comment by catlook** [comment]
Fair enough!  Could have changed it to "Communication .... is"  just as easily.  Definitely, subject and verb should agree :)

**Comment by rackernexus** [comment]
Build 307 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-dce9736be/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 308 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c9fbda81f/how-to/). valid for 14 days

**Pull request merged**
