### PR TITLE
Update cloud-files-faq.md - fix spelling error

### PR DESCRIPTION
**Pull request by cyrichardson**
!!!STOP!!!

Before creating a pull request, make sure that you are submitting your change on a **BRANCH** instead of a fork. 
You can review how to make a branch in the **contribution guidelines**(https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) for this repository. 

Please describe the changes you made in the bulleted list below. Use present tense. For example, if you added a question about image backups to the Cloud Images FAQ, you would say, "Add question about image backups to FAQ."

- 

- 

- 

**DO NOT MERGE YOUR OWN PULL REQUEST**

### CODE REVIEW

**Comment by cyrichardson** [comment]
@kmsholcomb We pushed this one through without your edits because the support folks said they needed it asap. But Nate and I would love it if you could edit the new question about eventual consistency. Thanks!

**Comment by kmsholcomb** [comment]
@cyrichardson: Will do!

**Comment by kmsholcomb** [comment]
@cyrichardson: I have just a few suggested edits, in the attached file. Please let me know if you have any questions. Thanks!

[What does eventual consistency mean in Cloud Files_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/178391/What.does.eventual.consistency.mean.in.Cloud.Files_editsKH.docx)

**Comment by cyrichardson** [comment]
Thanks, Kelly! I'll go apply them!

**Comment by cyrichardson** [comment]
Thanks, @kmsholcomb! I'll apply them!

**Pull request merged**
