### PR TITLE
Support PIN edits

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@cyrichardson would you mind reviewing my changes?
thanks!

**Comment by cyrichardson** [comment]
Will do, @WilliamLoy. On it now.

**Comment by rackernexus** [comment]
Build 251 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8433b151c/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 252 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-63f4f3315/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 253 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c5d8d36b1/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 254 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d89cf8e32/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 255 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e562da53a/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 256 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6c2db6bbf/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson would you mind reviewing the one line change? Thanks!

**Comment by cyrichardson** [comment]
Looking now, @WilliamLoy. Thanks for making me legitimate.

**Comment by cyrichardson** [comment]
Approved, @WilliamLoy!

**Comment by rackernexus** [comment]
Build 257 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ebb343b3d/how-to/). valid for 14 days

**Pull request merged**
