### PR TITLE
audit

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-70513ce95c/how-to/)

**Comment by cyrichardson** [comment]
@catlook Some suggestions here: 
[backing-up-your-files-with-rsync_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2539886/backing-up-your-files-with-rsync_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-bcf2ebb6dd/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-31efeb9cc1/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c0d309cd2d/how-to/). :bow:

**Pull request merged**
