### PR TITLE
Add new w3tc article for alternate method

### PR DESCRIPTION
**Pull request by stephamon**
Part of #1578 

My SME gave me an alternate method for using the W3TC plug-in with WordPress.

@kmsholcomb Will you add this to your editing list as well?

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-91a1b23de8/how-to/)

**Comment by kmsholcomb** [comment]
Hi, @stephamon. Edits attached. Please let me know if you have any questions. Thanks!

[Configure W3 Total Cache for WordPress with origin pull Rackspace CDN_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/745995/Configure.W3.Total.Cache.for.WordPress.with.origin.pull.Rackspace.CDN_editsKH.pdf)
[Configure W3 Total Cache for WordPress with origin pull Rackspace CDN_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/745996/Configure.W3.Total.Cache.for.WordPress.with.origin.pull.Rackspace.CDN_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-51aab09eee/how-to/)

**Comment by nimbinatus** [comment]
LGTM; ready to merge

**Pull request merged**
