### PR TITLE
Community Article - Basic Security Steps for Linux

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-70f0f1a1db/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f8515b7991/how-to/)

**Comment by cyrichardson** [comment]
@WilliamLoy Reviewing now... stay tuned.

**Comment by cyrichardson** [comment]
@WilliamLoy Suggested changes here: 
[basic-security-steps-for-linux_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2804786/basic-security-steps-for-linux_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4921413731/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-20f0bd1400/how-to/)

**Pull request merged**
