### PR TITLE
cloud office getting started

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 477 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2988b3c29/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson would you mind editing? :)

**Comment by cyrichardson** [comment]
@WilliamLoy Looking now!

**Comment by rackernexus** [comment]
Build 482 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e25c68d3b/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 483 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cbfc4060d/how-to/). valid for 14 days

**Pull request merged**
