### PR TITLE
BCP-update-billing-svcs-overview: INFODEV-904

### PR DESCRIPTION
**Pull request by RackerKate**
Replaces #2420.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-8b4d37f015/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0adad41952/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate On it!

**Comment by cyrichardson** [comment]
@RackerKate  Suggestions are here:
[billing-services-overview_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1732466/billing-services-overview_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d372093b4d/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0bfcc35abe/how-to/)

**Pull request merged**
