### PR TITLE
Attempt to fix display issue: INFODEV-3043

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a30d046b4a/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0334fe742a/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8102c28d41/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review. This is not a full audit; it was just intended to be a fix for a display error, but I did change some wording as well.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[cloud-backup-faq_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2733487/cloud-backup-faq_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-350df4a2ac/how-to/)

**Pull request merged**
