### PR TITLE
Audit centos-6-apache-and-php-install: INFODEV-2398

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-50666642d0/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate, on it!

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of suggestions here: 
[centos-6-apache-and-php-install_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2429640/centos-6-apache-and-php-install_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e1c5ef1834/how-to/)

**Pull request merged**
