### PR TITLE
raid cleanup

### PR DESCRIPTION
**Pull request by catlook**
retire article, remove a couple of links, and edit another article.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-243beea330/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0523867eb7/how-to/)

**Comment by cyrichardson** [comment]
@catlook Suggestions here: 
[preparing-data-disks-on-linux-cloud-servers_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2920313/preparing-data-disks-on-linux-cloud-servers_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-38fae08f76/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-fb6039a979/how-to/)

**Pull request merged**
