### PR TITLE
Full Audit: RPC FAQ

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1741

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-00c3d594ae/how-to/)

**Comment by kmsholcomb** [comment]
Edits attached @DonNateR. PLease let me know if you have any questions. Thanks!

[Rackspace Private Cloud FAQ_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/952559/Rackspace.Private.Cloud.FAQ_editsKH.pdf)
[Rackspace Private Cloud FAQ_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/952560/Rackspace.Private.Cloud.FAQ_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c555049a2d/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2a1641f93f/how-to/).

**Comment by stephamon** [comment]
👍

**Pull request merged**
