### PR TITLE
Replace Vyatta with Gateway Instances link

### PR DESCRIPTION
**Pull request by inflatador**
Vyatta is end of support

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9183deb972/how-to/)

**Comment by cyrichardson** [comment]
@inflatador Please review the changes I made and make sure you agree with them.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3b25a21a7a/how-to/)

**Comment by inflatador** [comment]
Looks great to me! Thanks for your help @cyrichardson  !

**Comment by cyrichardson** [comment]
Thanks, @inflatador! Merging now.

**Pull request merged**
