### PR TITLE
Updating VMware index file with relevant content

### PR DESCRIPTION
**Pull request by asettle**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c3af0c185e/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cf7c8fbffd/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9414736781/how-to/)

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at these for a full audit? Thanks!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-38d72e20ba/how-to/). :bow:

**Comment by cyrichardson** [comment]
I'll get right on it!

**Comment by cyrichardson** [comment]
@stephamon Here's edits for one of the file
[Managed-VMware-Services.docx](https://github.com/rackerlabs/rackspace-how-to/files/1674189/Managed-VMware-Services.docx)

**Comment by cyrichardson** [comment]
@stephamon  - here are comments for the 2nd changed article:

[Server-Virtualization-FAQ.docx](https://github.com/rackerlabs/rackspace-how-to/files/1674304/Server-Virtualization-FAQ.docx)



Please let me know if you would like for me to review the files that were only renamed.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-ccfeef2736/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-98395a14e0/how-to/)

**Pull request merged**
