### PR TITLE
Full audit: About TTL Best practices

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-8aa66ec4e0/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7b029cdd2f/how-to/)

**Comment by cyrichardson** [comment]
@DonNateR Suggested changes here: 
[Best practices for using TTL_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2116842/Best.practices.for.using.TTL_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f1659bf790/how-to/).

**Pull request merged**
