### PR TITLE
New Rackspace Email Plus article

### PR DESCRIPTION
**Pull request by nimbinatus**
Continuation of PR #1809 

cc: @bhazzard

### CODE REVIEW

**Comment by nimbinatus** [comment]
@kmsholcomb, here's that article. Thanks!

**Comment by kmsholcomb** [comment]
Hi, @nimbinatus. Not many edits, just a couple of comments. Please let me know if you have any questions. Thanks!

[Getting Started with Rackspace Email Plus_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/761355/Getting.Started.with.Rackspace.Email.Plus_editsKH.pdf)
[Getting Started with Rackspace Email Plus_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/761356/Getting.Started.with.Rackspace.Email.Plus_editsKH.docx)

**Comment by nimbinatus** [comment]
@kmsholcomb, does this look good now?

**Comment by nimbinatus** [comment]
waiting for final stamp to deploy

**Comment by nimbinatus** [comment]
final approval rec'd from SME

**Pull request merged**
