### PR TITLE
Correct spacing for numbering consistency

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c6a5f81f3d/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-da06588bcf/how-to/)

**Comment by stephamon** [comment]
👍  (silly picky markdown!)

**Comment by kylelaffoon** [comment]
Thanks @stephamon!

**Pull request merged**
