### PR TITLE
[Audit] Architecture reqs for RPC powered by MS

### PR DESCRIPTION
**Pull request by RobinJoe**
Editing the How-to article following the Style Guidelines for contributing
content:

* Spacing and formatting
* Clarify pronouns
* Sentence and word order

closes rackerlabs/rackspace-how-to/issues/#1531

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e82830c050/how-to/).

**Comment by DonNateR** [comment]
@RobinJoe: Did we confirm with an RPC engineer that any of the technical aspects of the article don't need to be updated?

**Comment by RobinJoe** [comment]
@DonNateR I've contacted the article author (Gerry Le Canu), and sent a message to the DevEx mailing list to check on the content to see if it needs an update.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e48eea8cc6/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @RobinJoe. My suggested markup is in the attached Word doc (and PDF copy of it--I find the PDf a little easier to decipher). My edits are mainly fairly light, but I did try to cut down that intro, which had a very marketing feel to it. Please let me know if you have any questions. Thanks!

[Architecture requirements for Rackspace Private Cloud powered by Microsoft_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/556570/Architecture.requirements.for.Rackspace.Private.Cloud.powered.by.Microsoft_editsKH.docx)
[Architecture requirements for Rackspace Private Cloud powered by Microsoft_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/556571/Architecture.requirements.for.Rackspace.Private.Cloud.powered.by.Microsoft_editsKH.pdf)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-d2bb32272e/how-to/)

**Comment by DonNateR** [comment]
Merging

**Pull request merged**
