### PR TITLE
full audit delete server

### PR DESCRIPTION
**Pull request by stephamon**
add audit date

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at this? No changes from the SME!

**Comment by cyrichardson** [comment]
On it, @stephamon.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8cedd68444/how-to/)

**Comment by cyrichardson** [comment]
@stephamon Some suggested changes here: 
[delete-a-server_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2349382/delete-a-server_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-20a27aeb0c/how-to/)

**Pull request merged**
