### PR TITLE
INFODEV-449 TriCore: Convert and add article for Oracle EBS

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by cyrichardson** [comment]
@stephamon This is the last TriCore doc conversion. Again, please let me know if you think the length is too long. Also, when you have time, could you please provide your technical editor review?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-fb709e8eb7/how-to/). :bow:

**Comment by cyrichardson** [comment]
[TriCore_Oracle_Tips_eBook[1].pdf](https://github.com/rackerlabs/rackspace-how-to/files/1377218/TriCore_Oracle_Tips_eBook.1.pdf)

Here's the original file from the RAX and TriCore marketing folks.

**Comment by stephamon** [comment]
Hey @cyrichardson, I think the length is okay. I'm not sure how you could break it up other than creating a set of short articles for each H3 section, but I think it's better to keep it together.

Here are my suggestions. There are a few clarifying questions. Let me know if you have any questions or need anything else!

[Oracle.E-Business.Suite.tips_SF.docx](https://github.com/rackerlabs/rackspace-how-to/files/1380367/Oracle.E-Business.Suite.tips_SF.docx)
[Oracle.E-Business.Suite.tips_SF.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1380368/Oracle.E-Business.Suite.tips_SF.pdf)

**Comment by cyrichardson** [comment]
@stephamon Thanks a ton!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-27a0344fbc/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-94f9ac8138/how-to/). :bow:

**Comment by cyrichardson** [comment]
Stephanie's edits applied 10/16.

**Comment by cyrichardson** [comment]
Approval to publish from TriCore marketing staff. They will request removal of the link to the TriCore blog site when that site goes offline in a while. They will send email to how-to@rackspace.com to remove that link when it is time.

**Comment by DonNateR** [comment]
Looks good.

**Pull request merged**
