### PR TITLE
add additional information as per sme request

### LINKED ISSUE #1322: Full audit, "Migrate to Rackspace From another hosting provider"
- [x] SME Review (Tyler Lutz, Jason Hummons). May need updates from Launch team
- [x] Editorial review

Fixes issue #1271

### PR DESCRIPTION
**Pull request by stephamon**
Adding some additional information as suggested by Jason Hammons

Fixes #1322

### CODE REVIEW

**Comment by stephamon** [comment]
@kmsholcomb Can you add this to your list to edit? Thanks!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-307852083b/how-to/)

**Comment by kmsholcomb** [comment]
I'll look at it today, @stephamon.

**Comment by kmsholcomb** [comment]
Hi @stephamon. My edits are in the attached Word (and PDF) file. Of course I edited the whole thing. :) Please let me know if you have any questions. Thanks!

[Migrate to Rackspace from another hosting provider_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/418533/Migrate.to.Rackspace.from.another.hosting.provider_editsKH.pdf)
[Migrate to Rackspace from another hosting provider_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/418534/Migrate.to.Rackspace.from.another.hosting.provider_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5cd916eacd/how-to/)

**Comment by ReneeRendon** [comment]
On the note at the bottom, the last sentence doesn't sound correct. I believe it needs to say " ... or **to** change the source and destination paths." ?

**Comment by ReneeRendon** [comment]
@stephamon 
Scratch that comment. I was not looking at the final corrections. Sorry about that.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c825ee4b60/how-to/). :bow:

**Pull request merged**
