### PR TITLE
Add remediating compromise Office 365

### PR DESCRIPTION
**Pull request by wstubbs12**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
Build me

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1065 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6f4df6a81/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1068 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6f4df6a81/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1069 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6f4df6a81/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1109 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a2f01bdd1/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1110 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a2f01bdd1/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1166 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b1f9ff43a/how-to/). valid for 14 days

**Pull request merged**
