### PR TITLE
Modified servers  to conform to new rbac template.

### PR DESCRIPTION
**Pull request by catlook**
closes issue #1619

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e6bc0e665e/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-67dcf99070/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-24d6f72e5c/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-023271ff64/how-to/).

**Comment by stephamon** [comment]
👍

**Pull request merged**
