### PR TITLE
Update Object Rocket doc article

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes part of issue #1520  
- Replace any outdated links that had obvious equivalents 
- Outdated links that do not have obvious equivalents have not been updated.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-793c083292/how-to/)

**Comment by troyswanson** [comment]
Let me compile a list of links that you should use instead.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f94c096fca/how-to/).

**Comment by troyswanson** [comment]
It looks like a lot of the API docs that used to be linked here don't really exist anymore.

Maybe just trim it down to:

```
- [Documentation](https://objectrocket.com/docs/api_v2.html)
- [Overview](https://objectrocket.com/docs/api_v2_getting_started.html)
```

**Comment by troyswanson** [comment]
Also, you might want to remove the entire "Tools" section.

I don't believe we surface those projects anywhere anymore.

**Comment by DonNateR** [comment]
I'll go ahead and remove the entire section. You want me to change the API links to reflect the doc's current structure?

**Comment by troyswanson** [comment]
Yeah that would probably be best.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-8fe3457dce/how-to/)

**Comment by DonNateR** [comment]
@troyswanson I updated the links and removed the tools section. Is there anything else you want to update at this time?

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My edits are attached (Word doc and PDF copy). Mainly just a bunch of nitpicky copy edits. Let me know if you have any questions. Thanks!

[ObjectRocket Documentation_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/562171/ObjectRocket.Documentation_editsKH.pdf)
[ObjectRocket Documentation_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/562172/ObjectRocket.Documentation_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-acbd5cbbca/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
