### PR TITLE
added new getting started product folder and article

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 310 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c6d0dc921/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 311 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c6d0dc921/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@stephamon can I get an edit review on this when you have a moment please? thanks

**Comment by rackernexus** [comment]
Build 312 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fe422fd82/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
LGTM

**Comment by rackernexus** [comment]
Build 313 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1150df918/how-to/). valid for 14 days

**Pull request merged**
