### PR TITLE
Create install-nginx-on-ubuntu

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by viridaria** [comment]
Build me

**Comment by rackernexus** [comment]
Build 2183 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-753c6ec3c/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2185 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-753c6ec3c/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Pull request merged**
