### PR TITLE
Create configuring-mssql-database-backup

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2294 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-af257ce18/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2296 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1ab7fe3f4/how-to/). valid for 14 days

**Pull request merged**
