### PR TITLE
Add enable autoupdates windows pubcloud: INFODEV-2493 and INFODEV-2494

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e20def75d0/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Review/merge please.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-59cd302825/how-to/)

**Pull request merged**
