### PR TITLE
Ccl linux file permissions

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b2cf402431/how-to/). :bow:

**Comment by cyrichardson** [comment]
@catlook Suggestions for new file here: 
[linux-file-permission-concepts_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2941961/linux-file-permission-concepts_cyrEdits.docx)

**Comment by cyrichardson** [comment]
Changes to existing file LGTM.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4b26c48f8e/how-to/)

**Pull request merged**
