### PR TITLE
Remove additional "S"

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5862fff3d8/how-to/)

**Comment by cyrichardson** [comment]
Because the section on https://support.rackspace.com/how-to/cloud-databases/ is labeled "Cloud Databases" and that's how other articles refer to this Public Cloud service, I would keep the "s" in the title.

**Comment by cyrichardson** [comment]
@RackerKate @BadCrumpany I think you can just close this PR without merging it.

**Comment by RackerKate** [comment]
Thanks @BadCrumpany!

**Pull request closed without merging**
