### PR TITLE
Add draft of new article that has instructions for resizing computer …

### PR DESCRIPTION
**Pull request by RackerKate**
…and mem servers: INFODEV-2314.

Needs SME review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e7a520e458/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-321d3d227e/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-20b27a4039/how-to/)

**Comment by RackerKate** [comment]
Replaced by #2764.

**Pull request closed without merging**
