### PR TITLE
Add new article on MyRack user name changes for Richard Goodwin: INFODEV-2485

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-075979ee93/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-282b12b775/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review. This is a high-priority article that Richard Goodwin says needs to go up today. Thanks!

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-5fdf1623bc/how-to/)

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[myrackspace-user-name-updates_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2415914/myrackspace-user-name-updates_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-6f32359b42/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2b114e5f14/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-52f94b3b26/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-89e7504feb/how-to/)

**Pull request merged**
