### PR TITLE
Move release notes into a separate PR

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by cyrichardson** [comment]
@joe2995 We'll see if this builds.

**Comment by rackernexus** [comment]
Build 644 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fc0acecb5/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 646 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5dbfa28df/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 647 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-99f5668d0/how-to/). valid for 14 days

**Comment by Joe2995** [comment]
Outstanding! Please merge/publish.

**Pull request merged**
