### PR TITLE
Update Reset a MySQL root password

### PR DESCRIPTION
**Pull request by ReneeRendon**
Update Reset a MySQL root password article.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-542a68b978/how-to/)

**Comment by ReneeRendon** [comment]
Waiting for reply from SMEs: (sent June7)

Hey Trey and Reese,

I have a question about this article.  https://support.rackspace.com/how-to/mysql-resetting-a-lost-mysql-root-password/

Some of the commands specify a difference in Ubuntu and CentOS commands, such as under the title **Stop MySQL**.  

Ubuntu or Debian
sudo /etc/init.d/mysql stop

CentOS, Fedora, and RHEL
sudo /etc/init.d/mysqld stop

Then in other places, there is no difference in the commands specified, such as under the title **Safe mode.**
sudo mysqld_safe --skip-grant-tables &

Would you use the 
sudo mysqld_safe --skip-grant-tables &    
command for Ubuntu and Debian as well as for CentOS, Fedora, and RHEL? 

Thanks,
Renée

**Comment by ReneeRendon** [comment]
Fixes #907

**Comment by ReneeRendon** [comment]
Did not hear back from the SMEs, but I believe Google supplied me with the correct answer.

**Comment by ReneeRendon** [comment]
Hi @kmsholcomb 
This one is ready for you to review.

**Comment by kmsholcomb** [comment]
Hi @ReneeRendon. The attached PDF has my suggested edits (which I did in a Word doc). Please let me know if you have any questions. Thanks!

[Reset a MySQL root password_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/309680/Reset.a.MySQL.root.password_editsKH.pdf)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-45d1232305/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-16bd5e31ac/how-to/)

**Pull request merged**
