### PR TITLE
add new billing article

### LINKED ISSUE #1901: New article: Billing invoice consolidation
This article does not need to be published until the feature is live in June 2017. I've gotten a lot of information from the development team that I'll use to pull together one or more articles.

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1901 

Do not merge until 08/14.

Still waiting on some information and screenshots from SMEs.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dcf5477f3b/how-to/)

**Comment by stephamon** [comment]
New launch date 09/18.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9430e6e3c5/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f528935b8c/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-6f9c451963/how-to/)

**Comment by stephamon** [comment]
Moved to #2224

**Pull request closed without merging**
