### PR TITLE
add binary updater for linux

### PR DESCRIPTION
**Pull request by brett-johnson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1458 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4ff9e4393/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1464 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-61fdaad61/how-to/). valid for 14 days

**Comment by brett-johnson** [comment]
@catlook is there anything holding this one up? Thanks!

**Comment by catlook** [comment]
one updated and one new article

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1600 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-14e6091ad/how-to/). valid for 14 days

**Pull request merged**
