### PR TITLE
Add SERVICENETENABLED installation option

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #947

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0a69f885d5/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Attached PDF contains markup. Please let me know if you have any questions. Thanks!

[Install the Cloud Backup agent on Windows by using silent installation_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/278320/Install.the.Cloud.Backup.agent.on.Windows.by.using.silent.installation_editsKH.pdf)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6382c8c0ec/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0d9e49a130/how-to/)

**Comment by stephamon** [comment]
👍

**Comment by cyrichardson** [comment]
@brett-johnson @rackmetzler Nate has completed this update. See https://support.rackspace.com/how-to/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation/. Additional edits by our technical editor also included!

**Comment by brett-johnson** [comment]
👍 Like it!

**Pull request merged**
