### PR TITLE
[WIP] Full Audit, ref issue #1577

### LINKED ISSUE #1577: Full audit: Scale multinode Wordpress sites using orchestration
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/cloud-orchestration/how-to-scale-multinode-wordpress-by-using-rackspace-orchestration.md

Each step must be performed in order for an article to be considered audited:

- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist 
- [x] Update audit_date: Update the `audit_date` metadata in the article with the date of the full audit's completion

See issue #1423  for more information.

### PR DESCRIPTION
**Pull request by nimbinatus**
proofed before SME review

Fixes #1577

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4e33a500d5/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e194444ff0/how-to/)

**Comment by nimbinatus** [comment]
rec'd +1 from Aaron (SME). @kmsholcomb, can you add this article to your editing queue? Thanks!

**Comment by kmsholcomb** [comment]
Hi @nimbinatus. See the attached Word doc (or PDF copy of it) for my suggested edits. There aren't many, but I did have a suggestion about terminology. Please let me know if you have any questions. Thanks!

[Scale a multinode WordPress stack by using Rackspace Orchestration_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/717495/Scale.a.multinode.WordPress.stack.by.using.Rackspace.Orchestration_editsKH.pdf)
[Scale a multinode WordPress stack by using Rackspace Orchestration_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/717494/Scale.a.multinode.WordPress.stack.by.using.Rackspace.Orchestration_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f38801a83e/how-to/)

**Comment by nimbinatus** [comment]
Thanks, @kmsholcomb! The changes all make sense.

**Pull request merged**
