### PR TITLE
Audit article: INFODEV-2571

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-913716cc19/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7ebb5072eb/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson For your review, please.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Pull request merged**
