### PR TITLE
Configure phpmyadmin

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 2269

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by stephamon** [comment]
Hey @cyrichardson I got a fairly big one for you!

**Comment by cyrichardson** [comment]
On it, @stephamon.

**Comment by cyrichardson** [comment]
@stephamon Suggested changes here: 
[install-and-configure-phpmyadmin_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2804979/install-and-configure-phpmyadmin_cyrEdits.docx)

**Comment by stephamon** [comment]
Going to close this out and push a fresh PR to see if that'll fix my issues

**Pull request closed without merging**
