### PR TITLE
Apply editor's suggestions

### PR DESCRIPTION
**Pull request by ReneeRendon**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-36f121fc3e/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7b20341250/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-681bdf894d/how-to/).

**Comment by kylelaffoon** [comment]
LGTM

**Pull request merged**
