### PR TITLE
Add rackspace-migration-manager folder and delete template from

### PR DESCRIPTION
**Pull request by cyrichardson**
FAWS folder

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-01224e98f5/how-to/)

**Comment by cyrichardson** [comment]
@DonNateR When you have time, would you please review and merge this for me? Thanks!

**Comment by cyrichardson** [comment]
OK. Thanks!

**Comment by cyrichardson** [comment]
Fixes #2080

**Comment by DonNateR** [comment]
Talked to Renee, I'll go ahead and merge.

**Comment by cyrichardson** [comment]
@DonNateR Thank you!

**Pull request merged**
