### PR TITLE
Audit multi-region support in CF article: INFODEV-2396

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-fda574c708/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[multi-region-support-in-cloud-filesz-cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2516622/multi-region-support-in-cloud-filesz-cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5cde71d77c/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3bd676e2c9/how-to/). :bow:

**Pull request merged**
