### PR TITLE
Update add-delete-or-disable-admin-accounts.md

### PR DESCRIPTION
**Pull request by hikarutilmitt**
Making a small change due to a rediscovered bug with the CP.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-29fceafc85/how-to/)

**Comment by nimbinatus** [comment]
@hikarutilmitt , I did a bit of minor proofing. Still look good to you? If it does, I'll merge it.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d1115aa591/how-to/)

**Comment by nimbinatus** [comment]
closing this one in favor of the newer #1684 PR...

**Pull request closed without merging**
