### PR TITLE
Adjust future referencing statement for graphs reporting MySQL metric…

### PR DESCRIPTION
**Pull request by kylelaffoon**
…s to currently available status.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-8570bdd534/how-to/). :bow:

**Comment by catlook** [comment]
👍

**Comment by kylelaffoon** [comment]
Thanks @catlook

**Comment by kylelaffoon** [comment]
Relates to #409

**Pull request merged**
