### PR TITLE
revised article

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 520 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d2a74aa2a/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready for you :) Have not heard back from the SME in weeks and I used the wiki they gave to write it so we should be ok to proceed.

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by rackernexus** [comment]
Build 681 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-67869c8be/how-to/). valid for 14 days

**Pull request merged**
