### PR TITLE
Applied requested support edits

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 235 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cc477fc09/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready for you :)

**Comment by cyrichardson** [comment]
On it, @WilliamLoy

**Comment by WilliamLoy** [comment]
LGTM!

**Comment by rackernexus** [comment]
Build 237 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2141945f8/how-to/). valid for 14 days

**Pull request merged**
