### PR TITLE
Customer warning: CBU doesn't follow symlinks.

### PR DESCRIPTION
**Pull request by brett-johnson**
If a customer believes that CBU will follow symlinks and backup files that are pointed to by the symlinks, they will likely never know that those files are not getting backed up until much too late, when they want to restore one of those files. We need to do due diligence to make sure customers know symlinks are, by design, not followed during CBU backup operations.

### CODE REVIEW

**Comment by DonNateR** [comment]
Hello @brett-johnson!

Just to get some clarification about the change you made, could you explain to me how the symlink issue came about? For example, has your team received a lot of support inquiries concerning symlinks and Cloud Backups?

**Comment by brett-johnson** [comment]
Don, if you are internal to Rackspace, please give me your Rackspace contact information, and I will be glad to discuss this with you. Thanks!

**Comment by brett-johnson** [comment]
The short answer to your question is this. I am the CBU agent dev lead at Rackspace.

The CBU team made an architectural decision at the outset not to follow symlinks, for reasons too lengthy to discuss here. But customers are not unlikely to expect symlinks to be followed by backups. In these cases, the only way the customer would typically know that their symlink is not being followed is when they attempt to restore a file. The file would not be restorable at that point, because it was (by design) never backed up. This would cause great frustration on the part of the customer and could lead to churn.

The intent of this documentation is to mitigate a circumstance like this by making customers aware of our policies, so that they have proper information needed to create backups that protect the files that they intend to protect.

Hope this helps.

**Comment by DonNateR** [comment]
@brett-johnson: Thanks for answering so quickly! If you can make your branch up to date with the How-to master branch by clicking *Update Branch* on this page, I can review your PR for grammar and merge it.

**Comment by DonNateR** [comment]
@brett-johnson If you want to reach out to me directly, my email is nate.archer@rackspace.com.

**Comment by brett-johnson** [comment]
Nate, thanks for getting back with me. Please let me know if I need to do anything else, to get this merged into production.

**Comment by DonNateR** [comment]
@brett-johnson: Quick update, I've had our editor review your request. Because the change is on fork, I can edit the changes directly, so I'm going to go ahead and merge your PR, than make our editorial changes on a separate PR. 
After the editorial changes have been made, I'll ping you on Github so you can review the changes and give your approval.

**Pull request merged**
