### PR TITLE
Create SSH - Two-Factor Authentication Using Google Authenticator

### PR DESCRIPTION
**Pull request by BadCrumpany**
Created an article from the community as the community will close soon.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-922b556567/how-to/)

**Comment by BadCrumpany** [comment]
Hey Kate!  The article you posted the link for deals with multi-factor authentication when logging in to the control panel. This new article is about adding two-factor authentication when logging into a Linux server via ssh, using google authenticator.  Thanks!

**Comment by RackerKate** [comment]
Thanks Shaun! This is something that an individual user would do, rather than an administrator, is that right?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9f05b88813/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-42b0cbc575/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3e490e0f87/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3b480f4fd0/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-48198e07d4/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ac018a2cd7/how-to/).

**Comment by RackerKate** [comment]
Re-created this article via a fresh branch/PR to break up the single large paragraph that was appearing. See https://github.com/rackerlabs/rackspace-how-to/pull/3047.

**Pull request closed without merging**
