### PR TITLE
Add a 'types of databases' H2 article for TriCore: INFODEV-1170

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b8d030f619/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate Edits/suggestions here: 
[types-of-databases_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1939638/types-of-databases_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-54d637413e/how-to/). :bow:

**Pull request merged**
