### PR TITLE
alternative option

### PR DESCRIPTION
**Pull request by jaymitripp**
Fixes issue #1876 

offer an alternative for those who are not developers so-to-speak

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-024a644794/how-to/)

**Comment by DonNateR** [comment]
@jaymitripp: Thank you for your contribution. I will add this to our next sprint!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-83be9bd5cb/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4e35c0a458/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-88775e9489/how-to/)

**Comment by kmsholcomb** [comment]
Hi, @DonNateR. Just a few tweaks. :)

[Application load testing_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/791316/Application.load.testing_editsKH.pdf)
[Application load testing_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/791317/Application.load.testing_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-1ca922c81e/how-to/)

**Pull request merged**
