### PR TITLE
Community Article - Building an Application on Rackspace: INFODEV-3428

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b03a42c3ea/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8935df043b/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of nits: 
[build-your-application-on-the-rackspace-cloud_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2829682/build-your-application-on-the-rackspace-cloud_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b1f2d0aebb/how-to/)

**Pull request merged**
