### PR TITLE
Ccl comm pitchfork

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ddd43d3e39/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-269f65045d/how-to/)

**Comment by cyrichardson** [comment]
@catlook Here are suggested changes for one of the articles: 
[pitchfork-the-rackspace-cloud-api-web-application_cyrEdit.docx](https://github.com/rackerlabs/rackspace-how-to/files/2783249/pitchfork-the-rackspace-cloud-api-web-application_cyrEdit.docx)

**Comment by cyrichardson** [comment]
@catlook Here are suggested change for the FAQ: 
[cloud-load-balancers-faq_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2783344/cloud-load-balancers-faq_cyrEdits.docx)

**Comment by cyrichardson** [comment]
@catlook Here are suggested edits for the troubleshooting article: 
[cloud-load-balancer-troubleshooting_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2783361/cloud-load-balancer-troubleshooting_cyrEdits.docx)

**Pull request merged**
