### PR TITLE
Add images and review to Steve's update.

### PR DESCRIPTION
**Pull request by DonNateR**
- Review for PR #1458

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-14ebb6a40f/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-f4807bf58b/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @DonNateR. The attached Word doc (and PDF copy of it) contains my markup and suggestions. I suggested rearranging some content in a few places, just to help with the flow. Otherwise, the copy edits are pretty straightforward (I think). Please let me know if you have any questions. Thanks!

[Managing Cloud Databases HA instance groups in the Cloud Control Panel_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/475483/Managing.Cloud.Databases.HA.instance.groups.in.the.Cloud.Control.Panel_editsKH.pdf)
[Managing Cloud Databases HA instance groups in the Cloud Control Panel_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/475484/Managing.Cloud.Databases.HA.instance.groups.in.the.Cloud.Control.Panel_editsKH.docx)

**Comment by stephamon** [comment]
👍

**Pull request merged**
