### PR TITLE
Audit article on Cloud DBs resources: INFODEV-2994

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-82c99909a6/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by RackerKate** [comment]
@stephamon Please review.

**Comment by stephamon** [comment]
@RackerKate I'm on it!

**Pull request merged**
