### PR TITLE
Create disabling-the-admin-user-in-windows

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
@BadCrumpany questions: why would you want to disable the admin user? Can you better explain the Control Panel warning at the beginning of the article? Are we talking about accidentally disabling the admin by using the control panel instead of using the recommended method?

**Comment by rackernexus** [comment]
Build 1787 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6ae02cd61/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1789 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-71c9f60b3/how-to/). valid for 14 days

**Comment by catlook** [comment]
disable-the-administrator-user-in-windows/

**Pull request merged**
