### PR TITLE
Create disabling-a-vhost-in-ubuntu-and-centos-for-apache-and-nginx

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1773 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-72c52d1bd/how-to/). valid for 14 days

**Pull request merged**
