### PR TITLE
More details on how to install nova-agent

### PR DESCRIPTION
**Pull request by inflatador**
Also, how to run servers without nova-agent

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1719 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2648d3714/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1720 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2648d3714/how-to/). valid for 14 days

**Comment by catlook** [comment]
nova-agent-unix-and-rackspace-agent-windows

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1722 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1ded1763b/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1723 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1ded1763b/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1724 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7a02e1d86/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1730 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f81c3d16c/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1732 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d3e2ebbe1/how-to/). valid for 14 days

**Pull request merged**
