### PR TITLE
Create nova-agent troubleshooting

### PR DESCRIPTION
**Pull request by csilva235**
New document for troubleshooting nova-agent or Rackspace Cloud Server Agent on Cloud servers.

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2089 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-028a82952/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2091 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f5e852049/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2093 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cc0cfa813/how-to/). valid for 14 days

**Comment by catlook** [comment]
Chris approved

**Pull request merged**
