### PR TITLE
Add archiving 365

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e5ba706c8b/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-492453e785/how-to/)

**Comment by cyrichardson** [comment]
Suggestions here: 
[add-rackspace-office-365-archiving_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1704556/add-rackspace-office-365-archiving_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-ba9b19a975/how-to/). :bow:

**Pull request merged**
