### PR TITLE
Remove Control Panel Links

### PR DESCRIPTION
**Pull request by beau-bailey**
Remove control panel links to avoid customer confusion. This article applies to admins who should have some experience with in the cp. Providing links for SA3 and Core accounts can lead to confusion because there is no clear way to explain to the customer which billing system their account may exist in.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4016b9024e/how-to/)

**Comment by DonNateR** [comment]
@beau-bailey: Are you saying that there are essentially two different Cloud Office control panels, or is this just a billed? Even though this article is aimed at admins, I feel that it would be worthwhile to ensure consistency across the board when it comes to the direction, "logging into the Cloud Office control panel." This could mean adding a note giving customers pointers on how to decide where to log in to their control panel.

**Comment by beau-bailey** [comment]
@DonNateR Your thoughts are mine. That is the struggle on how to word it with out leading to customer confusion. I think the verbiage below is a better suited prefab for all control panel articles though. 

> For customers who signed up online you can log in [here] (https://cp.rackspace.com), for others you will need to navigate to the Cloud Office Control Panel through the [MyRackspace Portal] (https://my.rackspace.com).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-a1323ea8a8/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6fbdb2d963/how-to/).

**Comment by DonNateR** [comment]
Reviewed and merged.

**Pull request merged**
