### PR TITLE
Update create-a-rackspace-cdn-service.md

### PR DESCRIPTION
**Pull request by kylelaffoon**
Add closing / to complete link to permalink.

### CODE REVIEW

**Comment by kylelaffoon** [comment]
Relates to #1401

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-cb20eccd9d/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6ef96f1bb5/how-to/)

**Comment by kylelaffoon** [comment]
Reduced the spacing before the links to avoid them being presented as a code sample.

**Pull request merged**
