### PR TITLE
Updated Kernel list

### PR DESCRIPTION
**Pull request by shampadeb**
Hi team,

Just updated the newly released kernels by Crowdstrike

Thanks
Shampa
RMS-PDR

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 708 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4ed7c5bb3/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 808 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4ed7c5bb3/how-to/). valid for 14 days

**Pull request merged**
