### PR TITLE
Create O365 Azure Sign In Logs

### PR DESCRIPTION
**Pull request by wstubbs12**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@cyrichardson this one is also ready :)

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by cyrichardson** [comment]
@WilliamLoy Minor edits complete.

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1602 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1d53a698e/how-to/). valid for 14 days

**Pull request merged**
