### PR TITLE
Add community article on fresh branch to break up large para: INFODEV-3231

### PR DESCRIPTION
**Pull request by RackerKate**
…s https://github.com/rackerlabs/rackspace-how-to/pull/3027/files

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a34f18983a/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-36bfbfe68a/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Some suggested changes here: 
[upgrade-apache-http-server-2.2-to-2.4-in-rhel-and-centos_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2770856/upgrade-apache-http-server-2.2-to-2.4-in-rhel-and-centos_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-dca5c4c7e0/how-to/). :bow:

**Pull request merged**
