### PR TITLE
Update basic security steps for linux

### PR DESCRIPTION
**Pull request by csilva235**
The current version of this article covers the steps to disable root login and an inefficient method of setting up sudo users. This section was removed and a link to the security article for Linux that describes the process in more detail was added. 

Additionally, I don't believe this article should be considered as "basic security". The modifications to the bootloader can cause serious issues if implemented incorrectly and is really more for use if your account is compromised. Alternatively, if the customer just wants an extra layer of security, this can be implemented. 

I know this article was recently provided to customers as part of COVID, however it really should really be changed to indicate that this is advanced security information that is likely not necessary for most customers.As this would affect the permalink, I'm not sure what can be done for that issue. 

 Feel free to reach out with any questions.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1411 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-820dd0ad5/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1432 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-48d953b5c/how-to/). valid for 14 days

**Comment by catlook** [comment]
pair with https://github.com/rackerlabs/nexus-control/pull/1144

**Comment by catlook** [comment]
@csilva235 double check before i push, pls

**Comment by csilva235** [comment]
@catlook Looks good! Thank you!

**Comment by rackernexus** [comment]
Build 1434 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-631c787c3/how-to/). valid for 14 days

**Pull request merged**
