### PR TITLE
transferring-images-between-regions-of-the-rackspace-open-cloud-with-pitchfork

### LINKED ISSUE #1877: ExCon: PR #1873
External contribution: new article by mackmoe. 

Article would normally go to Community. We need to asses whether or not this article belongs in How-To.

### PR DESCRIPTION
**Pull request by mackmoe**
I was answering a ticket and was told that I should share the steps on the community articles - I started this and realized this may not be the channel for community articles but I'm not sure how to do that. I poked around on the new how-to and community portals but figured I had come to far to give up so I should stash it on github and make someone on the KB article team aware of it. 

<3,

Mo Nash
@ESC_monash in our internal IRC channels, if you want to hit me up during the day
I'm @momothehobo in slack - See ya! :D

fixes #1877

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-bec9821615/how-to/)

**Comment by DonNateR** [comment]
@mackmoe: Thanks for your contribution! We all add this to our current sprint.

**Comment by kmsholcomb** [comment]
Hi @stephamon. I took a stab at cleaning up the article. My suggested changes are in the attached Word doc (and PDF copy of it). Use what you can, and edit what you can't! :) Please let me know if you have any questions. (BTW, I followed and verified the steps up to actually exporting the image. I wasn't brave enough to actually do the exporting and importing, so you might want to verify those steps). :)

[Transfer images between regions of the Rackspace open cloud with pitchfork_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/822033/Transfer.images.between.regions.of.the.Rackspace.open.cloud.with.pitchfork_editsKH.pdf)
[Transfer images between regions of the Rackspace open cloud with pitchfork_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/822034/Transfer.images.between.regions.of.the.Rackspace.open.cloud.with.pitchfork_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0f30c9d4d6/how-to/). :bow:

**Pull request merged**
