### PR TITLE
Create O365 Azure AD audit logs

### PR DESCRIPTION
**Pull request by wstubbs12**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@cyrichardson this is ready for an edit :)

**Comment by cyrichardson** [comment]
One in front of you, @WilliamLoy. But yours is in the queue.

**Comment by cyrichardson** [comment]
@WilliamLoy Minor edits complete.

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1601 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3d1fade65/how-to/). valid for 14 days

**Pull request merged**
