### PR TITLE
Community Article - Rackspace Self-Service

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5ce5ae7183/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6ca85efe4f/how-to/).

**Comment by WilliamLoy** [comment]
Closing PR as the article is not to be converted.

**Pull request closed without merging**
