### PR TITLE
Full audit: Permissions for billing services

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1785

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-042cdee84d/how-to/)

**Comment by kmsholcomb** [comment]
Hi, @DonNateR. I _did_ have some edits! :) Mainly, my changes are about making this article more consistent with the other RBAC permissions matrix articles that the team has been updating over the last few months. Please let me know if you have any questions. 

I can't upload the files here for some reason. Sending them in email.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-42434a7bf2/how-to/). :bow:

**Comment by stephamon** [comment]
👍

**Pull request merged**
