### PR TITLE
[WIP]Create common network troubleshooting tools article 

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes issue #1440

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-c0753a914c/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a5b917e5fe/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-66d6bb41e4/how-to/).

**Comment by kmsholcomb** [comment]
Hi, @DonNateR. My suggested edits are in the attached files. Please let me know if you have any questions. Thanks!

[Common network troubleshooting tools_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/527526/Common.network.troubleshooting.tools_editsKH.pdf)
[Common network troubleshooting tools_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/527527/Common.network.troubleshooting.tools_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e219dcf1ee/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d5ff1f1d78/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-8844312365/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-624de3dc1c/how-to/). :bow:

**Comment by stephamon** [comment]
👍

**Pull request merged**
