### PR TITLE
BCP - view-invoice-history-cloud-office-control-panel

### PR DESCRIPTION
**Pull request by catlook**
placeholder PR

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-810b3c2b98/how-to/).

**Comment by catlook** [comment]
@cyrichardson please edit!

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2dc8ac5f54/how-to/)

**Comment by cyrichardson** [comment]
Suggested edits here:
[view-invoice-history-cloud-office-control-panel_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1678417/view-invoice-history-cloud-office-control-panel_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-32f907e083/how-to/)

**Pull request merged**
