### PR TITLE
Audit choosing-the-right-database-with-rackspace-cloud-databases: INFODEV-1366

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-abdb9fee9b/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a88653dfb7/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e271272315/how-to/)

**Comment by RackerKate** [comment]
My apologies. I'll close this PR and make all edits via a new one.

**Pull request closed without merging**
