### PR TITLE
rackconnect audit dates part 3

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 4704

### CODE REVIEW

**Comment by stephamon** [comment]
Hi @cyrichardson I've got some more for you! It can wait until after the meeting though :)

**Comment by cyrichardson** [comment]
@stephamon OK! First thing after the meeting.

**Comment by rackernexus** [comment]
Build 560 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f8c0071f4/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 565 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c95112970/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@stephamon Edits complete... please check and see if you agree with my suggestions.

**Comment by rackernexus** [comment]
Build 567 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-70cff1535/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 569 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7ba512989/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 571 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3dc4a927d/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 573 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7b2e6d8c6/how-to/). valid for 14 days

**Pull request merged**
