### PR TITLE
Community Article - CDN Access-Control-Allow-Origin: INFODEV-3475

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3e12f28c7b/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e517782bad/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-157089936c/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f14f6fceae/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[use-cdn-access-control-to-allow-your-origin_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2853364/use-cdn-access-control-to-allow-your-origin_cyrEdits.docx)

**Comment by RackerKate** [comment]
> @RackerKate Suggestions here:
> [use-cdn-access-control-to-allow-your-origin_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2853364/use-cdn-access-control-to-allow-your-origin_cyrEdits.docx)
> 
> I remember this... a difficult thing to do with the current APIs that makes it hard to explain.

@cyrichardson This was a difficult one. Is everything explained correctly? Are there any edits that should be made from a technical standpoint?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cd8a2c6416/how-to/)

**Comment by cyrichardson** [comment]
@RackerKate Because it was in the Community, I think you can push it as it is. Maybe we'll get more feedback from users with the How-To article.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-11ec099d1f/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9dd26a813f/how-to/). :bow:

**Pull request merged**
