### PR TITLE
Aiops update pre moog 168

### PR DESCRIPTION
**Pull request by mralexjuarez**
Updating the Rackspace AIOps Article.

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1790 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-17abf8766/how-to/). valid for 14 days

**Comment by catlook** [comment]
aiops-alert-monitoring

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1793 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c725178a0/how-to/). valid for 14 days

**Comment by catlook** [comment]
@mralexjuarez check out the preview.  Good to go (except the one <br\> after the table, which I'll fix)?

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1795 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2c7791e38/how-to/). valid for 14 days

**Comment by catlook** [comment]
aiops-alert-monitoring

**Comment by catlook** [comment]
I'll go ahead and merge @mralexjuarez .  let me know if I need to make any corrections.

**Pull request merged**
