### PR TITLE
Community Article - Creating a New User in the Cloud Control Panel

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-47bbe3d656/how-to/).

**Comment by RackerKate** [comment]
Asked Shaun if we can close this out, because it's covered at https://support.rackspace.com/how-to/managing-role-based-access-control-rbac/.

**Comment by RackerKate** [comment]
Closing.

**Pull request closed without merging**
