### PR TITLE
Republish Sitecore portals article to How-To

### PR DESCRIPTION
**Pull request by DonNateR**
- Information about MyRackspace portal changed for technical accuracy.

- Add note about how Sitecore manages billing

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b90058ee2b/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-432298448d/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-5274cad69b/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
