### PR TITLE
Update metadata in Dedicated articles

### PR DESCRIPTION
**Pull request by ReneeRendon**
The "type" metadata should say article instead of product for all of the dedicated articles.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-55b7fd8ab5/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a17d70cd80/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-31da994de3/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7afa2dfbb1/how-to/).

**Comment by ReneeRendon** [comment]
Fixes issue #1928

**Pull request merged**
