### PR TITLE
Info-dev-5487-install-AnyConnect-new article

### PR DESCRIPTION
**Pull request by chri2547**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1361 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e3390af45/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1370 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4a2fed866/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1407 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ee851d3f9/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1413 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-4087c731e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1468 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-855e435bd/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1478 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e116c3bf8/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@chri2547 Please review these changes and see if you agree with them. Thanks!

**Comment by rackernexus** [comment]
Build 1535 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2097a6e13/how-to/). valid for 14 days

**Pull request merged**
