### PR TITLE
[MVP] Rackspace Migration Manager: Add migration best practices article

### LINKED ISSUE #2121: [MVP] Rackspace Migration Manager: Best practices article
Draft a best practices for migration article for Professional Services to use as a starting place.

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #2121

### CODE REVIEW

**Comment by cyrichardson** [comment]
Note: staging area is full. That's why the "All checks have failed" error above. Tools people are working on this.

**Comment by cyrichardson** [comment]
@trentgillaspie Review comments from support SME applied.

**Comment by cyrichardson** [comment]
@amitgandhinz Would you like to take a look at this when you have time? Thanks!

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-04c28e7b1b/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-025a4eda8f/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ffa69e4a43/how-to/)

**Comment by cyrichardson** [comment]
Ready for MVP launch

**Comment by cyrichardson** [comment]
Closing in favor of https://jira.rax.io/browse/INFODEV-424

**Pull request closed without merging**
