### PR TITLE
Community Article - Increase Size of Cloud Boot-from-Volume Server Sy…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…stem Disk: INFODEV-3365

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d791d362ba/how-to/)

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7eb438ac8d/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-97688ba641/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6f12e6db99/how-to/)

**Comment by WilliamLoy** [comment]
Looks good to me!

**Pull request merged**
