### PR TITLE
Initial audit updates

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6d6264a55b/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3686e5230c/how-to/)

**Comment by Indrapal2512** [comment]
+1 looks good to me.

**Comment by catlook** [comment]
Thanks for reviewing it!!

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[rackspace-cloud-backup-system-actions_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2166925/rackspace-cloud-backup-system-actions_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9dcdff9750/how-to/)

**Pull request merged**
