### PR TITLE
Edit Traditional Vs. Managed colocation. Retire old Colocation article.

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9d0da34c1e/how-to/)

**Comment by stephamon** [comment]
Hey @DonNateR here are my suggestions. Let me know if you have any questions!

[Traditional.Colocation.vs.Rackspace.Managed.Colocation_SFedit.docx](https://github.com/rackerlabs/rackspace-how-to/files/1519612/Traditional.Colocation.vs.Rackspace.Managed.Colocation_SFedit.docx)
[Traditional.Colocation.vs.Rackspace.Managed.Colocation_SFedit.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1519613/Traditional.Colocation.vs.Rackspace.Managed.Colocation_SFedit.pdf)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4fb144628f/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
