### PR TITLE
Update create-an-archive-login-message.md - GA Audit

### PR DESCRIPTION
**Pull request by chri2547**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b7137d0507/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9d6ba664cb/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7e76e305ff/how-to/)

**Comment by cyrichardson** [comment]
On it, @chri2547.

**Comment by cyrichardson** [comment]
@chri2547 Only one suggestion: 
[create-an-email-archive-login-message_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2907686/create-an-email-archive-login-message_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-245d58355b/how-to/)

**Pull request merged**
