### PR TITLE
Update CBU Linux instructions for DEB installs.

### PR DESCRIPTION
**Pull request by brett-johnson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-9b986cb802/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-800a65de23/how-to/)

**Comment by catlook** [comment]
jira ticket ID 1006

Should get this in our next sprint - thanks!!

**Comment by catlook** [comment]
replacing this with https://github.com/rackerlabs/rackspace-how-to/pull/2478.  I wanted it in a branch instead of going straight to master, so I checked out locally into a branch and resubmitted.  Once that pr merges, I'll close this one.

**Comment by catlook** [comment]
PR #2478 merged so closing this one

**Pull request closed without merging**
