### PR TITLE
Please Update Article

### PR DESCRIPTION
**Pull request by aldrichcory1**
https://github.com/rackerlabs/rackspace-how-to/edit/master/content/rackspace-email/rackspace-directory-sync-install-and-configure.md is the article link

### CODE REVIEW

**Comment by stephamon** [comment]
Hi @aldrichcory1 thanks! We'll pull this into our next sprint and get it merged. Congrats on your first PR!

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits are attached. I edited this article back in 2015, so it was already in pretty good shape. :) However, I did find some things I missed then, and I had a question involving the new content. Please let me know if _you_ have any questions. Thanks!

[Rackspace Directory Sync install and configure-update_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/987956/Rackspace.Directory.Sync.install.and.configure-update_editsKH.pdf)
[Rackspace Directory Sync install and configure-update_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/987955/Rackspace.Directory.Sync.install.and.configure-update_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7e06aeac6c/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-936d421eb9/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-31cbbc19b5/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
