### PR TITLE
Change terminology from 'www prefix' to 'subdomain'.

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e958db5132/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it shortly. 2 editing tasks in front of this one.

**Comment by cyrichardson** [comment]
@RackerKate I'll have this one ready for you when you get in tomorrow morning.

**Comment by cyrichardson** [comment]
@RackerKate Approved as is.

**Pull request merged**
