### PR TITLE
Create audit-logs.md

### PR DESCRIPTION
**Pull request by hikarutilmitt**
will send images

### CODE REVIEW

**Comment by nimbinatus** [comment]
Opened PR on the patch-15 branch, hikarutilmitt/rackspace-how-to#7 (note: I removed the screenshots to avoid update problems if the UI changes per current how-to style. If you think they really are crucial to understanding where to go, we certainly can put them back in.)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4bcd2f4b2c/how-to/).

**Comment by nimbinatus** [comment]
Opened second PR on the patch-15 branch, hikarutilmitt/rackspace-how-to#11

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6bccf7ff7d/how-to/). :bow:

**Pull request merged**
