### PR TITLE
org changes and minor edits

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 4657

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @cyrichardson can you give this a pass please?

**Comment by cyrichardson** [comment]
On it, @stephamon.

**Comment by rackernexus** [comment]
Build 580 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-289e11a05/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 583 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-60d090cd4/how-to/). valid for 14 days

**Pull request merged**
