### PR TITLE
full audit start a console session

### PR DESCRIPTION
**Pull request by stephamon**
Hey @cyrichardson can you take a pass at this? It looked pretty good to me, but you might see something that I missed.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c1a2cae438/how-to/)

**Comment by cyrichardson** [comment]
Will do, @stephamon.

**Comment by cyrichardson** [comment]
@stephamon - Suggestions in 
[start-a-console-session_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1716827/start-a-console-session_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0479815715/how-to/)

**Pull request merged**
