### PR TITLE
firs draft of support PIN how-to

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@cyrichardson got one ready for ya :)

**Comment by rackernexus** [comment]
Build 191 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ea95bd4e3/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
On it!

**Comment by rackernexus** [comment]
Build 192 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2c9aa6fb7/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 193 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8b62c1d6f/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 195 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2e6e714cb/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson would you mind giving this one more quick look please?

**Comment by rackernexus** [comment]
Build 198 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8fe84d014/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 200 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8f9e506a7/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 202 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e1ada2cca/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 204 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-26d4d8555/how-to/). valid for 14 days

**Pull request merged**
