### PR TITLE
Updates to new version

### PR DESCRIPTION
**Pull request by hikarutilmitt**
Adjusted text for MAriaDB to show 10.1
Clarified a statement about using mysqldump
adjusted text regarding future DFW versions, since that migration has been completed for some time.
Will add screenshots later.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-615cbef713/how-to/). :bow:

**Comment by DonNateR** [comment]
@hikarutilmitt: If you are adding screenshots, do you want me to wait to merge this PR?

**Comment by hikarutilmitt** [comment]
Go ahead and merge now, please.
I noticed that there was a complete scrub of the screenshots that already existed back on June 21. Is this a KC-wide decision to do away with screenshots or were they not committing to the style guide?

**Comment by DonNateR** [comment]
How-To wide decision. We had too many images that required consistent updates, so we came to a decision as a team to cut any images that weren't absolutely necessary to understanding a process. The general rule of thumb is that screenshots should only be used if a process cannot be adequately explained through text.

**Pull request merged**
