### PR TITLE
Cannot connect to email article creation

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3eb3a8348e/how-to/)

**Comment by stephamon** [comment]
@kmsholcomb another for the editing queue. I'm thinking that the numbered steps might work better as h4 sections? Anyway, thanks for looking at it!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-832da48e55/how-to/).

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits are attached. I would leave the steps as numbered, simply because the intention is for users to tackle the steps in the order presented, and the numbering reinforces that idea in a way that headings might not. Anyway, let me know if you have any questions. Thanks!

[Troubleshoot a failed email connection_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1052560/Troubleshoot.a.failed.email.connection_editsKH.pdf)
[Troubleshoot a failed email connection_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1052561/Troubleshoot.a.failed.email.connection_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6f5c5f0a87/how-to/)

**Pull request merged**
