### PR TITLE
Audit legal blurb: INFODEV-2394

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bfa5bd859d/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[legal_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2621110/legal_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-25506ee835/how-to/). :bow:

**Pull request merged**
