### PR TITLE
Added SME feedback

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by viridaria** [comment]
build me

**Comment by viridaria** [comment]
Pending SME approval

**Comment by rackernexus** [comment]
Build 2151 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c10e81ccd/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2153 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f31f842fc/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2168 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a99d8b234/how-to/). valid for 14 days

**Comment by viridaria** [comment]
build me

**Comment by rackernexus** [comment]
Build 2176 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a0c88b9bd/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 2177 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a0c88b9bd/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 2192 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ecc1284fe/how-to/). valid for 14 days

**Comment by catlook** [comment]
Ok, you might want to double-check, @viridaria, but I think it's ready to go.  Here's a tip on when to use ordered (numbered) and unordered (bullet) lists.  If things must be in a specfic sequence (like steps in a process), use an ordered list.  If the items are just a collection and no one is more important than any other, use an unordered list!  If you are good with this, put the *ready to publish - go* label on the PR!

**Pull request merged**
