### PR TITLE
Updated for Apache 2.4 ruleset

### PR DESCRIPTION
**Pull request by hikarutilmitt**
Updated to use Apache 2.4 ruleset, cleaned up some formatting and erroneous information from the old article.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c2855e4754/how-to/).

**Comment by stephamon** [comment]
@kmsholcomb would you mind giving this an editorial review?

**Comment by kmsholcomb** [comment]
Will do, @stephamon

**Comment by kmsholcomb** [comment]
Hi @stephamon. The How-To also has another article about controlling website access by IP address: https://support.rackspace.com/how-to/allow-a-specific-ip-address-to-access-your-cloud-sites-site-by-using-ssl/. The information in that article is also included in this article, now in the "The following information is outdated and for archival purposes only" section. So, before I edit, I have a couple of comments/questions that might affect both articles:

- Is the content in this article under the heading "The following information is outdated and for archival purposes only" actually still relevant for users? If not, there is no need to keep it. If it is still relevant for some users, then we need to redo that heading. 

- If the content under the heading "The following information is outdated and for archival purposes only" is still relevant for users and should be retained, then can we combine that other article (about SSL) with this article, and then delete that article? And if the "outdated" content can actually be deleted, then I think that means we could delete the SSL article. 

If, based on these questions, you revise the article, let me know when it is ready for editing. If you want me to edit it now, let me know. Thanks!

**Comment by stephamon** [comment]
@hikarutilmitt Any input on what Kelly asked ^^ ?

**Comment by hikarutilmitt** [comment]
It should be fine to remove the deprecation notice at the bottom as well as
the other article. I left the old information since we still technically
have a few customers using Apache 2.2, however those will be changing soon.
Taking out the old information is fine and avoids confusion.

**Comment by kmsholcomb** [comment]
Thanks @hikarutilmitt. @stephamon, I'll edit the article and post suggestions first thing in the morning.

**Comment by kmsholcomb** [comment]
Hi @stephamon. My suggested edits are in the attached Word doc and PDF copy of the Word doc.Given the last comment by @hikarutilmitt, I did not edit the "deprecated" content since you'll be removing it (as well as that other article)! Please let me know if you have any questions. Thanks!

[Allow or block specific IP addresses from accessing your Cloud Sites website_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/270619/Allow.or.block.specific.IP.addresses.from.accessing.your.Cloud.Sites.website_editsKH.pdf)
[Allow or block specific IP addresses from accessing your Cloud Sites website_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/270620/Allow.or.block.specific.IP.addresses.from.accessing.your.Cloud.Sites.website_editsKH.docx)

**Pull request merged**
