### PR TITLE
first draft

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dc70008864/how-to/)

**Comment by WilliamLoy** [comment]
@cyrichardson This one is ready for you :)

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by cyrichardson** [comment]
@WilliamLoy Editorial commit made

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-30c701d1d6/how-to/)

**Comment by WilliamLoy** [comment]
Looks good!

**Pull request merged**
