### PR TITLE
DO NOT MERGE: Reorg landing page

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 4139 and 4056

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 145 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cd7077f68/). valid for 14 days

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 146 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cd7077f68/). valid for 14 days

**Comment by rackernexus** [comment]
Build 147 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-19d8c9aba/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 154 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0f6a8cf67/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 155 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0f6a8cf67/how-to/). valid for 14 days

**Pull request closed without merging**
