### PR TITLE
Community Article - Export and Download a Saved Image with Pitchfork/…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…Cyberduck

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0b10124b6b/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6778c6de63/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-221256b5ac/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c51c0a2ea8/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[export-and-download-a-saved-image-with-pitchfork-cyberduck_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2797003/export-and-download-a-saved-image-with-pitchfork-cyberduck_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b164818a6c/how-to/)

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Pull request merged**
