### PR TITLE
Full audit configure mariadb

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 1299

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at this article? It looks like it needs a good amount of tone work.

**Comment by cyrichardson** [comment]
In the queue, @stephamon. Will do!

**Comment by cyrichardson** [comment]
@stephamon, suggested changes are here: 
[configuring-mariadb-server-on-centos_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2028021/configuring-mariadb-server-on-centos_cyrEdits.docx)

**Comment by stephamon** [comment]
Redirect: https://github.com/rackerlabs/nexus-control/pull/877

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6f6051d27d/how-to/).

**Pull request merged**
