### PR TITLE
New page for getting started with the new Rackspace Email Plus product

### PR DESCRIPTION
**Pull request by ddubbindustries**
The CONTRIBUTING file said to:
 1. `Click Propose New Change` but I couldn't find such a button, is this from an older version of the GitHub interface maybe?
 2. Send image files to how-to@rackspace.com, but by the time I got to that instruction, I had already uploaded them to a folder in `_assets` following the example of another article, is that going to work? I can't tell if I got the paths right in the preview mode so you'll have to build it and see. Is there any way I can build it locally and check that? (Maybe that's more involved than you'd like people to be, but it might help increase the quality of what you have to review.)

Anyway, this is really really cool! I'm so excited to make my first submission. Thanks for setting it up to work this way!

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c80be2da55/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2bd167ef13/how-to/).

**Comment by ddubbindustries** [comment]
Great, was able to adjust a few items that seemed ok in Github's preview but looked different in the final. I was expecting the bulleted list to be solid bullets on the first level and hollow on the second, did I format it wrong?

**Comment by nimbinatus** [comment]
@ddubbindustries, thanks for the contribution! We will pull this into our next available slot in our sprints to work on it.

In answer to your other questions:
1. I'll look into that question about the `Propose New Change` button.
2. The only reason, as far as I know, that we ask people to email the images is so that we can ensure no private data is being shared (and to ensure quality). I don't see anything private in there, so I think we are ok.
3. The hollow bullets are correct; our system uses hollow ones :)

Thanks for asking! Someone will pick up this PR soon.

**Comment by nimbinatus** [comment]
@ddubbindustries, since you seem pretty excited to get involved ( 😄 ), I'm going to work off of your pull request (PR) rather than creating my own with changes. Gives you a chance to be involved in the whole process. I'll submit a PR of my own on your fork: https://github.com/ddubbindustries/rackspace-how-to/pull/2. You will need to merge my changes into your fork for the preview link to update here. If you have any questions, feel free to reach out to me directly!

If you would rather I just took over your PR so you don't have to do anything further, please let me know.

**Comment by bhazzard** [comment]
There is one change to your updates I think is important: 

> Quick Start
>  
> There are several ways to access the features of Rackspace Email Plus.

The reason this change is important is that we are actually talking about multiple disparate features, some which are available on certain platforms, and not on others. So I don’t want to give the impression that all features are available on all platforms. For example: “or the native application for your system with Rackspace Email Plus.” I think this implies native mobile applications, which is not a possibility for the drive features.
 
Also, I think this text is there merely to serve as a lead-in to the rest of the article.

**Comment by nimbinatus** [comment]
@bhazzard, good to know; thank you! Yes, the text is a lead-in to the rest of the article. I'll revise and resubmit.

Also, as a note: Our staging server is down, and that's breaking the Strider build test. Don't panic :)

**Comment by bhazzard** [comment]
When can we expect this to be live on the how-to site? We were planning to release a page that links to it today.

**Comment by bhazzard** [comment]
@nimbinatus unfortunately Dave (ddubbindustries) is no longer with Rackspace. Can you make sure this merge process can work without his assistance going forward.

**Comment by nimbinatus** [comment]
I heard; thank you, @bhazzard. I'm going to have to take over this PR by closing it and starting another PR. I'll link you to it.

**Comment by nimbinatus** [comment]
opened new PR

**Pull request closed without merging**
