### PR TITLE
[WIP] Fundamentals

### PR DESCRIPTION
**Pull request by THE-Alan-Hicks**
Work-in-progress. Had to do some shenanigans on some of these and need to test them thoroughly in staging.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-6a90aa1bf9/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a44f8b82e7/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-40538a1b67/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3d27b0e169/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b37b4bc6a3/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f780f8bdef/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1c56b22ed8/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a4ba7cd067/how-to/)

**Comment by stephamon** [comment]
@THE-Alan-Hicks I see you've got your build passing! Let us know if you need anything while you're testing.

**Comment by THE-Alan-Hicks** [comment]
Thanks Stephanie. I was able through trial-and-error to figure out what the root cause of my problems was and address it. I'm just doing final checks on these files now, but we really need to get that white-paper section setup so these can have a permanent home.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-4323d53372/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7b29237383/how-to/).

**Comment by stephamon** [comment]
Hi @THE-Alan-Hicks this all mostly looks very clean! I'm going to be looking a little more closely today, as we're getting very close to the new white paper site launch, but one thing that I did notice right away is your section headers. We use sentence case for titles and headers, so can you go in and change yours to be sentence case?

I'll let you know in a line comment if I spot anything else!

**Comment by stephamon** [comment]
Moved to rackerlabs/rackspace-whitepapers

**Pull request closed without merging**
