### PR TITLE
Full audit of wordpress orchestration article (1576)

### PR DESCRIPTION
**Pull request by catlook**
Closes issue # 1576

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0abb1a3a22/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-42b87e903d/how-to/)

**Comment by catlook** [comment]
this has become a retire instead of audit.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-ab7c76b531/how-to/). :bow:

**Comment by stephamon** [comment]
👍

**Pull request merged**
