### PR TITLE
Update verbiage and remove images

### PR DESCRIPTION
**Pull request by kylelaffoon**
Update text and update or remove images where no longer needed.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e47b3aa4ab/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8ca32599eb/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-870f0ce7eb/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
