### PR TITLE
added audit date and minor edits

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 4703

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 546 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-25ba24987/how-to/). valid for 14 days

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at these articles?

**Comment by cyrichardson** [comment]
On it, @stephamon!

**Comment by cyrichardson** [comment]
@stephamon Merge away!

**Comment by rackernexus** [comment]
Build 558 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-9d60e0be1/how-to/). valid for 14 days

**Pull request merged**
