### PR TITLE
Apply additional cyr edits

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-44840ed439/how-to/)

**Comment by cyrichardson** [comment]
Sent to Marc Nourani via Slack for his approval.

**Comment by cyrichardson** [comment]
@catherine I'm now good with the "parent page"

**Comment by catherine** [comment]
@cyrichardson - I don't think I'm the @catherine you meant to tag ;)

**Pull request merged**
