### PR TITLE
Full Audit: Working with Alarms

### PR DESCRIPTION
**Pull request by DonNateR**
As suggested by Kelly in PR #2186

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b12aec8750/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-57f354b001/how-to/)

**Comment by stephamon** [comment]
@kmsholcomb here are my edits. Let me know when you finish your edits, and I'll come take a look at what you've done differently or added.

[Understand.and.work.with.alarms_editSF.docx](https://github.com/rackerlabs/rackspace-how-to/files/1257677/Understand.and.work.with.alarms_editSF.docx)
[Understand.and.work.with.alarms_editSF.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1257678/Understand.and.work.with.alarms_editSF.pdf)

**Comment by kmsholcomb** [comment]
Hey @stephamon. So, I saved your Word doc, renamed it, and added some comments. I didn't do any inline editing because I think that would have been hard to see. So all of my comments are in, well, comments! I've attached the updated and renamed Word doc, plus a PDF copy of it. Great job, by the way! You caught a few things I missed, and you didn't miss very much at all (from my perspective). :) If you have any questions or want to discuss anything, just let me know.

[Understand.and.work.with.alarms_editSF-KH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1261276/Understand.and.work.with.alarms_editSF-KH.docx)
[Understand.and.work.with.alarms_editSF-KH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1261275/Understand.and.work.with.alarms_editSF-KH.pdf)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-17bf2689e9/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-598187ca74/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
