### PR TITLE
Audit Cloud LBs FAQ: INFODEV-3003

### PR DESCRIPTION
**Pull request by RackerKate**
Will replace link to Community after that post has been converted into a How-To article. Mallory Hernandez in Cloud ESC said they would add it to the list of posts to be converted, but I replied offering to do it today.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c180bda5c6/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3a1ef4ef69/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b8d0ee0fe4/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f8e38cca87/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-63849e510f/how-to/)

**Comment by cyrichardson** [comment]
@RackerKate Some suggestions here: 
[cloud-load-balancers-faq_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2760708/cloud-load-balancers-faq_cyrEdits.docx)

**Pull request merged**
