### PR TITLE
Audit article: INFODEV-2528

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d6a668320f/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[configure-a-load-balancer_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2457273/configure-a-load-balancer_cyrEdits.docx)

**Pull request merged**
