### PR TITLE
Full Audit, issue #1664

### LINKED ISSUE #1664: Full audit: Upgrade to managed operations services level
https://github.com/rackerlabs/rackspace-how-to/blob/master/content/managed-operations/upgrade-to-managed-operations-service-level.md
- [x] SME check: Update any out of date or inaccurate technical content with the help of a SME
- [x] Editor check: Incorporate edits from Kelly Holcomb
- [x] Quality Checklist: Perform a quality audit of the article using the quality checklist
- [x] Update audit_date: Update the audit_date metadata in the article with the date of the full audit's completion

### PR DESCRIPTION
**Pull request by nimbinatus**
minor proofing and adjusted note to important before SME review.

Fixes #1664.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-28426f3fdc/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-6d53bafe3d/how-to/). :bow:

**Comment by nimbinatus** [comment]
@kmsholcomb, can you add this to your editing queue, please? Thanks!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c09bfc2a07/how-to/).

**Comment by nimbinatus** [comment]
@kmsholcomb, there was an unexpected update from a second SME. Just pushed up the latest update.

**Comment by kmsholcomb** [comment]
Hi @nimbinatus. My suggested edits are in the attached Word doc and PDF copy of it. I had some questions about current terminology; I hope they are clear. If you have any questions, please let me know. Thanks!

[Upgrade to Managed Operations service level_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/687969/Upgrade.to.Managed.Operations.service.level_editsKH.pdf)
[Upgrade to Managed Operations service level_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/687968/Upgrade.to.Managed.Operations.service.level_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d478926b5a/how-to/). :bow:

**Comment by nimbinatus** [comment]
@kmsholcomb, how does this one look? Here's the full staging link: https://staging.developer.rackspace.com/support.rackspace.com/build-d478926b5a/how-to/upgrade-to-the-managed-operations-service-level/

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2d425e78f4/how-to/).

**Comment by DonNateR** [comment]
Looks good. Do you have a redirect set up in Nexus Control to reflect the new title?

**Pull request merged**
