### PR TITLE
update articles with audit date

### PR DESCRIPTION
**Pull request by stephamon**
JIRA 5012 & 5013

SME confirmed that the articles are still correct, so I've just done a few edits and added audit dates.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by stephamon** [comment]
Hey @cyrichardson can you double-check both of these articles please?

**Comment by cyrichardson** [comment]
On them, @stephamon.

**Comment by cyrichardson** [comment]
@stephamon Edits complete!

**Comment by WilliamLoy** [comment]
@stephamon test please ignore

**Comment by stephamon** [comment]
build me

**Pull request merged**
