### PR TITLE
Create add-an-additional-rdp-license-to-windows-server-2012r2

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by BadCrumpany** [comment]
Looks good.  Thank you!

**Comment by rackernexus** [comment]
Build 2080 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0cf28d173/how-to/). valid for 14 days

**Pull request merged**
