### PR TITLE
Update Windows server security best practices

### PR DESCRIPTION
**Pull request by csilva235**
Updated recommended password strength to a longer password and added a note about Cloud Backup vs Cloud Server Images as not all servers can be imaged and images should not be considered a full backup solution.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1429 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b0fda562d/how-to/). valid for 14 days

**Comment by catlook** [comment]
need your final thumbs up, @csilva235 !

**Comment by csilva235** [comment]
@catlook Looks great! Thank you!

**Comment by rackernexus** [comment]
Build 1438 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1d41a7e58/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1439 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f26cc025d/how-to/). valid for 14 days

**Pull request merged**
