### PR TITLE
Full audit of article.

### PR DESCRIPTION
**Pull request by catlook**
Closes isse #1574

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-502c2ab3b3/how-to/)

**Comment by kmsholcomb** [comment]
Hey @catlook. My suggested edits are in the attached Word doc (and attached PDF). I followed most of the steps in the control panel as I edited, and some of my edits reflect the steps that I had to (or chose to) take. If they are different from your own experience, then you don't need to make my changes, but just ensure that the steps you do have are clear. If you have any questions, please let me know. Thanks!

[Quick set up with Rackspace Cloud Orchestration_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/581812/Quick.set.up.with.Rackspace.Cloud.Orchestration_editsKH.pdf)
[Quick set up with Rackspace Cloud Orchestration_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/581811/Quick.set.up.with.Rackspace.Cloud.Orchestration_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0ecc037bfa/how-to/).

**Comment by catlook** [comment]
edits applied!

**Pull request merged**
