### PR TITLE
New article: Delete an object group

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c39a4193c2/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ddefcf9541/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cbd954e2de/how-to/).

**Comment by cyrichardson** [comment]
@DonNateR Suggested changes here: 
[delete-an-object-group-with-firewall-manager-v2_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2190693/delete-an-object-group-with-firewall-manager-v2_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-1093c16fef/how-to/). :bow:

**Pull request merged**
