### PR TITLE
Create text-editors-in-linux

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1352 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-fe1a81f6a/how-to/). valid for 14 days

**Comment by stephamon** [comment]
@cyrichardson can you look at this one too please?

**Comment by rackernexus** [comment]
Build 1499 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-974206284/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
On it, @stephamon

**Comment by cyrichardson** [comment]
@stephamon Please review these changes and see if you agree with them. Thanks!

**Pull request merged**
