### PR TITLE
new user workflow

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 224 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-60fdf5531/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 225 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-43ab5423e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 226 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0b8e1ac9e/how-to/). valid for 14 days

**Comment by BryanSD** [comment]
A few thoughts:

- We probably also want to modify the [Viewing and editing user information for your account](https://support-revs.staging.deconst.org/build-0b8e1ac9e/how-to/viewing-and-editing-user-information-for-your-account/) article as it talks about adding a new user in the `User Management page` section.
- In the [New user workflow](https://support-revs.staging.deconst.org/build-0b8e1ac9e/how-to/new-user-workflow/) article, we may want to mention that invitation links automatically expire after a period of time so encourage the newly-invited user to promptly register.
- The `Viewing and editing user information for your account` article mentions RBAC when discussing creating new users. I think we should either link these two articles together, or again call out RBAC in the `New user workflow` article to provide guidance on that portion of creating a new user.

**Comment by rackernexus** [comment]
Build 241 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f53090cef/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 242 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0a9d8b7e6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 243 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e53f16f4d/how-to/). valid for 14 days

**Comment by catlook** [comment]
publish monday 7/29

**Comment by rackernexus** [comment]
Build 247 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-a4c8f25a7/how-to/). valid for 14 days

**Pull request merged**
