### PR TITLE
Update linux-server-security-best-practices

### PR DESCRIPTION
**Pull request by csilva235**
The original article contained some flaws and only provided information for older OS versions. Some of the information could still be used, but there are some significant changes. 

Proposing this replacement(refreshed) article to include steps for modern/supported OS versions.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1410 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cfdfb7f7b/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1430 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5f1ba68bc/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1431 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-cdd678259/how-to/). valid for 14 days

**Comment by catlook** [comment]
@csilva235 double check before i merge, pls

**Comment by csilva235** [comment]
Just added a minor informational sentence. Everything else looks good!

**Comment by rackernexus** [comment]
Build 1435 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-db2560ab7/how-to/). valid for 14 days

**Pull request merged**
