### PR TITLE
INFODEV-3688

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ee551e9d3b/how-to/)

**Comment by cyrichardson** [comment]
@will suggestions here: 
[restarting-a-stalled-driveclient-agent_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2943314/restarting-a-stalled-driveclient-agent_cyrEdits.docx)

**Comment by will** [comment]
thanks, but I don’t know what this is for?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-894bd6cb24/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f7f31a893a/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2a66e8e168/how-to/)

**Pull request merged**
