### PR TITLE
Create compression-tools-in-linux

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1653 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-99103239d/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1654 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-99103239d/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1655 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5f1f18c91/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1656 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-5f1f18c91/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1657 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2cb905ddb/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1658 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-744f0f841/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1659 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-25fcea3bd/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1660 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-513cc9352/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1661 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-513cc9352/how-to/). valid for 14 days

**Pull request merged**
