### PR TITLE
full audit internal IP address

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3e863545b3/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-35ae7b6378/how-to/).

**Comment by cyrichardson** [comment]
@catlook Editorial changes in this commit: https://github.com/rackerlabs/rackspace-how-to/pull/3247/commits/c4a9bd2fb38788d00d6f891540eb6528ac871115

**Comment by catlook** [comment]
Closing this and retiring it instead.  Added public and servicenet sections to the cloud networks FAQ

**Pull request closed without merging**
