### PR TITLE
Add article about managing ACLs in Cloud Big Data clusters

### PR DESCRIPTION
**Pull request by jimbobhickville**
Adds a brief article explaining how to inject iptables rules into
the cluster so the user can open ports up to public access if they
require it.

### CODE REVIEW

**Comment by jimbobhickville** [comment]
This is my first time submitting an article, so feedback is appreciated.  We're gonna try to get more content up for our product.

**Comment by stephamon** [comment]
@kmsholcomb can you give this an edit? 

@jimbobhickville I'm sending this to our editor to look at. Thanks for submitting!

**Comment by kmsholcomb** [comment]
Hi @stephamon: I'll send editorial comments later today.

**Comment by kmsholcomb** [comment]
Hi @stephamon: My suggested edits are in the attached Word doc (and in the PDF copy of it). Please let me know if you have any questions. Thanks! 

[Cluster ACL management with iptables_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/155615/Cluster.ACL.management.with.iptables_editsKH.docx)

**Comment by jimbobhickville** [comment]
Thanks.  I'll update the PR with the suggested edits.  One question: Post-Install Script is how the cloud control panel labels the input, so that's why I used that in the places I mentioned it.  Is it ok to keep that as-is?

**Comment by kmsholcomb** [comment]
@jimbobhickville: Yes. Sometimes people capitalize words randomly, and my habit is to make almost everything lowercase! But we should match the case of the terms shown on the UI, to make things easier for the user. Good question. Thanks!

**Comment by jimbobhickville** [comment]
Edits are made.  I also moved the 2nd example outside of middle of the step-by-step instructions so it flowed better.

**Comment by jimbobhickville** [comment]
@stephamon @kmsholcomb let me know if it needs more edits

**Comment by stephamon** [comment]
Hi @jimbobhickville this looks really good! If you can just update the branch from master, I'll merge it! Thanks so much!

**Comment by jimbobhickville** [comment]
@stephamon Done

**Pull request merged**
