### PR TITLE
Update article to reflect current Control Panel

### PR DESCRIPTION
**Pull request by cyrichardson**
Partially fixes https://github.com/rackerlabs/docs-rackspace/issues/282

Reference ticket:
https://encore.rackspace.com/ticketing/account/10040922/ticket/170313-dfw-0001270
From the encore ticket:
You can view the API key by clicking on your username in the upper right > My Profile & Settings > Scroll down to 'Security Settings', the last line will have 'Rackspace API Key' and click 'Show' to view.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-876dda441d/how-to/)

**Comment by cyrichardson** [comment]
Preview link: https://staging.developer.rackspace.com/support.rackspace.com/build-876dda441d/how-to/view-and-reset-your-api-key/

**Comment by cyrichardson** [comment]
Hi, @kmsholcomb! Please edit when you have time.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-26f28fde31/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-cdcc02347a/how-to/)

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. My suggested edits are in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. Thanks!

[View and reset your API key_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/856580/View.and.reset.your.API.key_editsKH.pdf)
[View and reset your API key_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/856579/View.and.reset.your.API.key_editsKH.docx)

**Comment by cyrichardson** [comment]
@kmsholcomb Thanks!!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c9dbb6d701/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2f19293ece/how-to/)

**Pull request merged**
