### PR TITLE
Jellyfish and grammatical edits: INFODEV-2516

### PR DESCRIPTION
**Pull request by RackerKate**
Will audit with separate PR.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d7035b31b9/how-to/)

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate. Some suggestions here: 
[mysql-connect-to-your-database-remotely_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2435415/mysql-connect-to-your-database-remotely_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-67d4cab1de/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b9449b8a05/how-to/).

**Pull request merged**
