### PR TITLE
Added command to allow servicenet related packets

### PR DESCRIPTION
**Pull request by kruzda**
Without that, you disable ServiceNet completely which is not recommended if you want to some of the Cloud products to communicate

### CODE REVIEW

**Comment by DonNateR** [comment]
@kruzda: Could you update your branch on Github? After you do so, I can go ahead and merge your PR.

**Comment by kruzda** [comment]
I think I did it?

**Comment by DonNateR** [comment]
@kruzda: Sorry to ask you again, but could you to update your branch one more time?

Just so you know, the How-to team has written [contribution guidelines](https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) that describe our preferred method of creating _pull requests_ for this repo. Specifically, we would like contributors to make a  **branch** of this repository, as opposed to making changes in your own fork. By using branches, the How-to team will be able to make changes to your PR without having to ask you to make changes in your fork. Following our contribution guidelines will speed up the review process and allow your requested change to be published faster.

**Comment by kruzda** [comment]
OK, sorry I never seen those guidelines before. Would you rather if I create a branch with this change or if I leave it in this fork/pull request instead?

**Comment by DonNateR** [comment]
@kruzda: I went ahead and made one for you. https://github.com/rackerlabs/rackspace-how-to/pull/619, I'll merge it once the Travis check is complete.

**Pull request closed without merging**
