### PR TITLE
INFODEV-447 TriCore: Convert and add article for Oracle Business Intelligence Enterprise Edition tips

### PR DESCRIPTION
**Pull request by cyrichardson**
converted from TriCore ebook

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-5ed5a581ee/how-to/). :bow:

**Comment by cyrichardson** [comment]
Hi, @stephamon. I guess the first step is for you to check this out and let me know if you think it's too long and should be broken up into smaller articles. If so, please provide your guidance on how to break it up.

**Comment by stephamon** [comment]
Hey @cyrichardson, I'm going to do a full edit for you, but a couple things that I noticed right off the bat. First off, I think the length is okay, but we should add a contents list in the end of the intro. Just the H3 levels.

To format an anchor link, it'll look like this `[Upload the repository in OBIEE 11g and 12c](#upload-the-repository-in-obiee-11g-and-12c)`

Second, the code blocks aren't formatting properly, so try using the indention method (4 spaces to format code. Increase in multiples of 4 when in lists) instead of the back ticks. For example:

Use the following commands to upload the ``.rpd`` file,
``OBIEE12CBusinessIntelligence.rpd``, in Unix and Linux environments:

    [OSuser@LocalHostDetails bin]$ ./data-model-cmd.sh uploadrpd -I
    /temp/OBIEE12CBusinessIntelligence.rpd -SI ssi -U Username -Password -S
    LocalHostDetails.com -N PortNo9502
    RPD Password: <Enter the RPD password>
    Service Instance: <Enter the RPD password - the ssi>
    Operation successful.
    RPD upload completed successfully.
    [OSuser@LocalHostDetails bin]$

I'll post a full edit soon, but I don't know that I'll have any suggestions other than the above. The writing looks really clean!

**Comment by cyrichardson** [comment]
@stephamon Thanks so much! While you are working on the full edit, I will address your suggestions. Much appreciated!

**Comment by stephamon** [comment]
Hi again @cyrichardson, here are my suggested edits. Let me know if you have any questions!

[Oracle.Business.Intelligence.Enterprise.Edition.tips_SF.docx](https://github.com/rackerlabs/rackspace-how-to/files/1359969/Oracle.Business.Intelligence.Enterprise.Edition.tips_SF.docx)
[Oracle.Business.Intelligence.Enterprise.Edition.tips_SF.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1359970/Oracle.Business.Intelligence.Enterprise.Edition.tips_SF.pdf)

**Comment by cyrichardson** [comment]
Thanks a ton, @stephamon!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e06ce4eb33/how-to/). :bow:

**Comment by cyrichardson** [comment]
@stephamon Thanks so much! Much appreciated!

**Comment by cyrichardson** [comment]
Edits applied and draft sent to RAX marketing and TriCore marketing for reveiw on 10/5/2017.

**Comment by cyrichardson** [comment]
Approved by TriCore marketing on 10/16. Merging.

**Pull request merged**
