### PR TITLE
two new how-to articles

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
@stephamon these need some editing magic please :)

**Comment by rackernexus** [comment]
Build 1335 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8e0e0bca6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1336 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0986d580e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1337 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-62df3e0b4/how-to/). valid for 14 days

**Pull request merged**
