### PR TITLE
Create adding-a-user-to-the-local-administrators-group-in-windows-ser…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…ver-2012

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1638 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1918c4768/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1640 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-345d0bbdb/how-to/). valid for 14 days

**Pull request merged**
