### PR TITLE
Updated kernels sep 2019

### PR DESCRIPTION
**Pull request by tofarley**
It's been a while since we updated this list. I previewed it in a markdown editor and it looks good.

Thanks!

### CODE REVIEW

**Comment by cyrichardson** [comment]
@tofarley Waiting for preview to build.

**Comment by rackernexus** [comment]
Build 489 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c41ddf394/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@tofarley Merged. Build process for external publishing will start next.

**Comment by cyrichardson** [comment]
@tofarley Looks like your updates are published externally. Thanks again for docs contribution!

**Pull request merged**
