### PR TITLE
Added gateway build_config option

### PR DESCRIPTION
**Pull request by inflatador**
Don't release this doc update until the gateway config is in production. I will send you more details in an internal email.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-305b41a267/how-to/)

**Comment by catlook** [comment]
Comment from the email: Just a heads-up, I submitted a PR for ServerMill docs (the new gateway build_config option). This PR should not be merged until https://jira.rax.io/browse/RBAN-12448 is finished, which is in turn blocked by https://jira.rax.io/browse/DFOT-2803 . Sorry for the confusion and let me know if you have any questions.  - Brian King

**Comment by catlook** [comment]
no longer blocked.   Brian King [9:22 AM]
oh yes, we can go ahead and publish now. Fortinet let the cat out of the bag so I'm no longer worried about us tipping our hand :wink:

https://docs.fortinet.com/vm/rackspace/fortigate/6.0/rackspace-cookbook/6.0.4/123172/about-fortigate-for-rackspace

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-93b1ac98fa/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d6fd78750b/how-to/). :bow:

**Comment by cyrichardson** [comment]
@catlook Editorial changes commit made.

**Pull request merged**
