### PR TITLE
Change the title of the article as this is not only for servers creat…

### PR DESCRIPTION
**Pull request by rsgeinzer**
…ed before June 3 2013 and removed references to that change in the article.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0912a8dd0f/how-to/). :bow:

**Comment by catlook** [comment]
Hey, I notice you didn't actually change the name of the article.  Do you still need that?

**Comment by rsgeinzer** [comment]
HI Cat:

I thought I had done that. Thanks for catching it.

Becky

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-60936ad310/how-to/)

**Pull request merged**
