### PR TITLE
Update article to include better instructions

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by catlook** [comment]
Do NOT merge yet, please, @stephamon but do review

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-1881da41eb/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ccc4b72cce/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4d2bdd9ca2/how-to/)

**Comment by catlook** [comment]
Will apply Kelly edits, but publication delayed until 9/14

**Comment by kmsholcomb** [comment]
Hi @catlook. Edits are attached. Please let me know if you have any questions. Thanks!

[Use pivot tables with your Cloud billing invoice_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1222707/Use.pivot.tables.with.your.Cloud.billing.invoice_editsKH.docx)
[Use pivot tables with your Cloud billing invoice_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1222708/Use.pivot.tables.with.your.Cloud.billing.invoice_editsKH.pdf)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-46801d33b8/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-cd76a0fea7/how-to/)

**Comment by catlook** [comment]
Ok this is ready for publish on 9/14.  blocked until then.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2e11cd8c24/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-11a5c17332/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-add9b64e0e/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e15d07716f/how-to/). :bow:

**Pull request merged**
