### PR TITLE
Create installing-php-modules

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1814 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7812e7609/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1815 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7812e7609/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1816 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-045d866f0/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1817 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-045d866f0/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1818 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-045d866f0/how-to/). valid for 14 days

**Pull request merged**
