### PR TITLE
Wl renamed email windows

### PR DESCRIPTION
**Pull request by stephamon**
takes over #2223

### CODE REVIEW

**Comment by stephamon** [comment]
Hi @kmsholcomb I've got one more for you! Like the Android article, I applied the common edits from the iPhone article.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6462a5c90b/how-to/)

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits attached. 

[Configure a renamed email address on Windows mobile phone_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1294069/Configure.a.renamed.email.address.on.Windows.mobile.phone_editsKH.docx)
[Configure a renamed email address on Windows mobile phone_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1294070/Configure.a.renamed.email.address.on.Windows.mobile.phone_editsKH.pdf)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-92d2e6294c/how-to/)

**Pull request merged**
