### PR TITLE
Add Community Article - Retrieving CDN Access Logs on Per Customer/Per Container Basis: INFODEV-3421

### PR DESCRIPTION
**Pull request by RackerKate**
I believe this will replace #3123.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c9c45bc4f6/how-to/)

**Comment by RackerKate** [comment]
This is on waiting on SME clarification.

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 72 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-41f9c6c37/docs/). valid for 14 days

**Comment by rackernexus** [comment]
Build 73 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-41f9c6c37/docs/). valid for 14 days

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3cff5c59bf/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
Build 82 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-db14f7006/docs/). valid for 14 days

**Comment by rackernexus** [comment]
Build 83 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-db14f7006/docs/). valid for 14 days

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[retrieve-cdn-access-logs-on-per-customer-per-container-basis_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2865564/retrieve-cdn-access-logs-on-per-customer-per-container-basis_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dc27d46e03/how-to/)

**Comment by rackernexus** [comment]
Build 84 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d6c3ca0fb/docs/). valid for 14 days

**Pull request merged**
