### PR TITLE
Correct the author

### LINKED ISSUE #1276: On boarding doc suggestion - Troubleshoot SSL error
Relates to #1264 
SME: Yesenia C.

Customer is getting “An SSL error has occurred and a secure connection to the server cannot be made.”
Could we get something on how customers can troubleshoot this error?

### PR DESCRIPTION
**Pull request by etoews**
Fixes #1276

### CODE REVIEW

**Comment by etoews** [comment]
Please dance with me @wolfdancer

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a11ec1a4da/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3ecbca075e/how-to/). :bow:

**Comment by DonNateR** [comment]
@etoews: This is clearly a very important pull request. Let me know when you need me to merge.

**Comment by everett-toews** [comment]
Haha. Oops! Meant to close this before walking away from the demo.

**Pull request closed without merging**
