### PR TITLE
added fortigate section

### PR DESCRIPTION
**Pull request by inflatador**
Product is already at soft-launch, will be announced via blog post and portal within the next month

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 159 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-aab7cc333/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 160 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2af5c943e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 161 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3543e88c7/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@inflatador Merged

**Pull request merged**
