### PR TITLE
BCP-update-faq-role-based-access-control-rbac: INFODEV-909

### PR DESCRIPTION
**Pull request by RackerKate**
Initial commit to create PR. PLACEHOLDER ONLY. Please do not merge.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a729132b82/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d030fba531/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8a574da8c5/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ece4fb0e57/how-to/)

**Comment by cyrichardson** [comment]
@RackerKate I did a review of the full article. My suggestions are here: 
[faq-role-based-access-control-rbac_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1720557/faq-role-based-access-control-rbac_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b3f54bb7fb/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1032ed627c/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Revised. Please see preview at https://staging.developer.rackspace.com/support.rackspace.com/build-1032ed627c/how-to/faq-role-based-access-control-rbac/.

**Comment by cyrichardson** [comment]
@RackerKate LGTM! Thanks! Ready for request to review/merge in the how-to slack channel.

**Comment by stephamon** [comment]
👍

**Pull request merged**
