### PR TITLE
add mycloud info

### PR DESCRIPTION
**Pull request by Sterling463**
Replace pitchfork information with mycloud portal info

### CODE REVIEW

**Comment by Sterling463** [comment]
Build me

**Comment by rackernexus** [comment]
Build 924 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-541f4eecf/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 925 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1c15963c3/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 926 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8b7f407d6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 927 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c7cd5dd50/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
Build me

**Comment by rackernexus** [comment]
Build 929 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c44decbb8/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 932 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f812a9635/how-to/). valid for 14 days

**Comment by Sterling463** [comment]
@stephamon would you mind reviewing this article for me?

**Comment by rackernexus** [comment]
Build 935 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-ce38894a7/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 938 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3d4e62cff/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 973 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-846199b11/how-to/). valid for 14 days

**Pull request merged**
