### PR TITLE
Wl self migration tool

### PR DESCRIPTION
**Pull request by stephamon**
takes over #2141

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @kmsholcomb can you edit this one?

**Comment by kmsholcomb** [comment]
Yep!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-461d63e2bb/how-to/)

**Comment by kmsholcomb** [comment]
Hi @stephamon. Edits are attached. A few links were broken, so be sure to check them all (I indicated the ones that did not work for me). If you have any questions, please let me know. Thanks!

[Migrate your email by using the Self Service Migration Tool_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1154105/Migrate.your.email.by.using.the.Self.Service.Migration.Tool_editsKH.pdf)
[Migrate your email by using the Self Service Migration Tool_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1154106/Migrate.your.email.by.using.the.Self.Service.Migration.Tool_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-4a2ee60d3e/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-7eb1f12ff2/how-to/). :bow:

**Pull request merged**
