### PR TITLE
[WIP] Update to detach/delete block storage volumes article

### LINKED ISSUE #1746: Edit/Correction Request for CBS article
Hello How-To Team,

A user came into the Community and posted this thread regarding one of the articles published in the How-To:

Community Thread: https://community.rackspace.com/feedback/f/68/t/8037
Article: https://support.rackspace.com/how-to/detach-and-delete-cloud-block-storage-volumes/

Can you please have the article changed to correct the steps?

Thanks,
Stu

### PR DESCRIPTION
**Pull request by nimbinatus**
Ref request from community in attached issue.

Fixes #1746

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e8a7874d76/how-to/)

**Comment by nimbinatus** [comment]
review request sent to SME

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-ad9a2e087f/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-342e3f628c/how-to/). :bow:

**Comment by nimbinatus** [comment]
@kmsholcomb, can you add the last section of this one to your editing queue? It's new. I'm hoping to post it for merge tomorrow assuming the SME gives the final rewrite his +1 (the new section is essentially his; I just adjusted it to match how-to style). Thanks!

**Comment by kmsholcomb** [comment]
Hi @nimbinatus. You probably won't be surprised that I edited the whole article! :) See the attached Word doc (and PDF copy of it) for my markup, comments, and questions. If you want to update the current article with just the new content first, and then circle back to the other edits, I'm OK with that. Please let me know if you have any questions. Thanks!

[Detach and delete Cloud Block Storage volumes_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/736057/Detach.and.delete.Cloud.Block.Storage.volumes_editsKH.pdf)
[Detach and delete Cloud Block Storage volumes_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/736056/Detach.and.delete.Cloud.Block.Storage.volumes_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-609e98f352/how-to/). :bow:

**Comment by cyrichardson** [comment]
LGTM. Merged.

**Pull request merged**
