### PR TITLE
New Article: Firewall manager v2: object-groups

### PR DESCRIPTION
**Pull request by trevorbecker**
establishing new PR for new article

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-808462ee9e/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-aa8e55bf52/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d6a88e87aa/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b9d4a6b786/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-14b7d88ed3/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-1c52113d75/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-73935500bc/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f182d25e9a/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f6b8d78568/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-52ac6aec36/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d96c90804f/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dff3d9eb8b/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-81ac120c5d/how-to/).

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits are attached. Main changes are around terms and formatting. Specifically, let's not capitalize or hyphenate the term *object group*, except where style warrants it (see the edits for specific changes). Also, ensure that all user steps are formatted as steps, to make them easier to follow. If you have any questions, please let me know.

@stephamon, because this article and the port groups article are so alike, I would suggest that you apply these edits, as appropriate, to that article as well. I can look it over after you have done that. Thanks!

[Firewall Manager v2 object groups_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/862461/Firewall.Manager.v2.object.groups_editsKH.pdf)
[Firewall Manager v2 object groups_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/862462/Firewall.Manager.v2.object.groups_editsKH.docx)

**Comment by trevorbecker** [comment]
@kmsholcomb @DonNateR 
First of all, thank you for taking the time to edit this. I am still reading through your review.

First comment is that the term "object-group" refers to a Cisco term that is no longer technically accurate if it does not have the dash. In Cisco, an "object group" and "object-group" mean different things.

I am requesting that we keep "object-group" and "port-group" to keep this article technically accurate.

**Comment by kmsholcomb** [comment]
Hi @trevorbecker. Thanks for the info! I had looked on the Rackspace UI for the name, and not seeing it, I decided it didn't need the hyphen. :) I will be certain to refer to the Cisco docs in any future editing that I do for these articles. Please let me know if I made any other suggestions that change the meaning (which is certainly not my intention).

**Comment by trevorbecker** [comment]
@kmsholcomb @DonNateR 
I found one more

"access-list" is a technical term referring to Cisco syntax that requires the dash to remain accurate.


@kmsholcomb Thank you for your understanding. I know your review is with good intentions and I appreciate your grammar assistance! (I sure do need it, haha) Thank you again!!

**Comment by kmsholcomb** [comment]
Thanks, @trevorbecker. Will add *access-list* to my list.

**Comment by DonNateR** [comment]
Closing this PR to add images in PR #1931

**Pull request closed without merging**
