### PR TITLE
initial edits

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1409 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-65386168a/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1433 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-df77d6d63/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
On it, @Sterling463.

**Comment by rackernexus** [comment]
Build 1518 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-81c7eb12d/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1520 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-281e5b6fc/how-to/). valid for 14 days

**Pull request merged**
