### PR TITLE
New article: Deploy to Sitecore using FTP

### PR DESCRIPTION
**Pull request by DonNateR**
Fixes issue #1985

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a1640bd75c/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b5a30e20d8/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c8d5005c5f/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits are attached, nothing earth-shattering! :) But let me know if you have any questions. Thanks!

[Deploy to Sitecore Cloud using FTP_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/976669/Deploy.to.Sitecore.Cloud.using.FTP_editsKH.pdf)
[Deploy to Sitecore Cloud using FTP_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/976668/Deploy.to.Sitecore.Cloud.using.FTP_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-56367fa3ae/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-390f5c0ef8/how-to/). :bow:

**Comment by catlook** [comment]
LGTM!

**Pull request merged**
