### PR TITLE
Create Linux - Device Not Showing Correct Disk Space After Resize

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1259 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7356f11b6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1372 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f716da51f/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
On it, @catlook.

**Comment by rackernexus** [comment]
Build 1374 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e3d909ab1/how-to/). valid for 14 days

**Pull request merged**
