### PR TITLE
Kylel 160629 1

### PR DESCRIPTION
**Pull request by kylelaffoon**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-529275828d/how-to/). :bow:

**Comment by DonNateR** [comment]
@kylelaffoon: Add milestone and yourself as an Assignee and than I will merge. 👍

**Comment by kylelaffoon** [comment]
@DonNateR Done. Thanks!

**Comment by kylelaffoon** [comment]
- Fixes #1086

**Pull request merged**
