### PR TITLE
Wl renamed email apple

### PR DESCRIPTION
**Pull request by stephamon**
takes over #2219

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-f628bc0b15/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-8870d18e12/how-to/). :bow:

**Comment by stephamon** [comment]
Hey @kmsholcomb can you take a look at this one? Thanks!

**Comment by kmsholcomb** [comment]
Hi, @stephamon. See attached edits. Thanks!

[Configure a renamed email address in Apple Mail_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1300240/Configure.a.renamed.email.address.in.Apple.Mail_editsKH.docx)
[Configure a renamed email address in Apple Mail_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1300241/Configure.a.renamed.email.address.in.Apple.Mail_editsKH.pdf)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-87672cbc65/how-to/)

**Pull request merged**
