### PR TITLE
BCP - view-and-pay-unpaid-invoices-cloud-office-control-panel

### PR DESCRIPTION
**Pull request by catlook**
Placeholder PR

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0b76129f41/how-to/).

**Comment by cyrichardson** [comment]
Just a few suggestions: 
[view-and-pay-unpaid-invoices-cloud-office-control-panel_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1678673/view-and-pay-unpaid-invoices-cloud-office-control-panel_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7b5052bd72/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e54ede6abd/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
