### PR TITLE
Update to cloud server reboot article per #1733

### LINKED ISSUE #1733: Update instructions in Reboot your server
Can this article be edited, specifically this part Windows
Issue a restart request by clicking Start > Shut down.
If we can add >select restart from the dropdown,  to the end of that then it would be more clear. I have had 3 customers in the last week say they followed the article and the server never came back up. 
 
https://support.rackspace.com/how-to/reboot-your-server/

### PR DESCRIPTION
**Pull request by nimbinatus**
minor update to text per SME.

Fixes #1733

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-70ce8105ee/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-28c718468a/how-to/)

**Comment by nimbinatus** [comment]
rec'd +1 from SME (see issue #1733 for redacted email chain)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-1d4da88fab/how-to/). :bow:

**Pull request merged**
