### PR TITLE
Create managing-safe-and-blacklists.md

### PR DESCRIPTION
**Pull request by hikarutilmitt**

### CODE REVIEW

**Comment by nimbinatus** [comment]
Opened PR on the patch-20 branch, hikarutilmitt/rackspace-how-to#2

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-d5c9003519/how-to/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5aaa3c4a56/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d7d8d97362/how-to/).

**Pull request merged**
