### PR TITLE
sending limit article full audit

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 229 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-29ef350f7/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson this one is ready for an edit :)

**Comment by cyrichardson** [comment]
OK @WilliamLoy   On it!

**Comment by rackernexus** [comment]
Build 230 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-028048834/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
Looks good to me!

**Pull request merged**
