### PR TITLE
registered trademarks appropriately designated

### PR DESCRIPTION
**Pull request by brett-johnson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1071 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-255313d43/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1072 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c963a1ec8/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1073 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-74d966a16/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1074 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-049119812/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1075 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-eec639351/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1076 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c46e697b1/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1077 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1d8975757/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1078 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-37818933a/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1079 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d65fe9c68/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1080 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-89ad93bbf/how-to/). valid for 14 days

**Comment by cyrichardson** [comment]
@brett-johnson Please review these changes and see if you agree with them. Then I can merge.

**Comment by rackernexus** [comment]
Build 1081 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c08b419f6/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1082 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-58b73a743/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1083 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-11bac873e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1084 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-733302457/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1085 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-2081b199e/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1086 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-00ab954c1/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1087 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-abb0a389b/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1088 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-59cfaf1f7/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1089 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0c1f9b348/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1090 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-27cc70c73/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1091 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-e7d5a6bd4/how-to/). valid for 14 days

**Pull request merged**
