### PR TITLE
Add upgrade Cloud Databases to MySQL 5.7 or MariaDB/Percona (2 articles): INFODEV-3095 and INFODEV-3080

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5431a13509/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2f52e1c5f2/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5624fa7ff5/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-ab3b165750/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-4e911438d4/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-63f3e2ea35/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-318a271638/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ebc339601d/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b30368f24b/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2a5a3da95a/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ea58436e1c/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review. Replacing outdated article with 2 new articles.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Upgrade a Cloud Databases instance from MySQL 5.6 to MySQL 5.7 LGTM - no suggested changes. Moving on to Upgrade a Cloud Databases instance from MySQL 5.6 to a newer version of MariaDB or Percona Database.

**Comment by RackerKate** [comment]
@cyrichardson I don't see your comment in that document.

**Comment by cyrichardson** [comment]
@RackerKate Sorry, I'm not sure why they aren't here. Try this file: 
[upgrade-a-cloud-databases-instance-from-mysql-56-to-newer-mariadb-or-percona_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2738787/upgrade-a-cloud-databases-instance-from-mysql-56-to-newer-mariadb-or-percona_cyrEdits.docx)

**Comment by RackerKate** [comment]
@cyrichardson NP - thank you!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-97599a2fa6/how-to/).

**Pull request merged**
