### PR TITLE
Add draft of wiki-converted experiment article on troubleshooting low disk space…

### PR DESCRIPTION
**Pull request by RackerKate**
… on Linux: INFODEV-2268. Still needs SME review.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0ade430678/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4ee5fd0142/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-6d2ab9cc93/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review please.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[linux-cloud-server-low-disk-troubleshooting_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2308074/linux-cloud-server-low-disk-troubleshooting_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0f6c37cb0c/how-to/). :bow:

**Pull request merged**
