### PR TITLE
New article: View an object group

### PR DESCRIPTION
**Pull request by DonNateR**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-03f8d89167/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-96028b06c5/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-919664e658/how-to/).

**Comment by cyrichardson** [comment]
@DonNateR Tiny suggestions here: 
[view-an-object-group-with-firewall-manager-v2_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2190176/view-an-object-group-with-firewall-manager-v2_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-723acb7dc2/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-77345d8977/how-to/)

**Pull request merged**
