### PR TITLE
Outlook for windows rename config

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-57fc3f21cd/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5a655ed1e5/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c19f1b38d2/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-b739511155/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b66afe9e67/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-859f022b64/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-13ddafccbc/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ede33b4174/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-3f029f857d/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-960bbaefb7/how-to/)

**Comment by catlook** [comment]
Kelly, please edit.  Hopefully, I've caught most of the usual changes...

**Comment by kmsholcomb** [comment]
Hi @catlook. My edits are attached. Please let me know if you have any questions. Thanks!

[Configure a renamed email address on Outlook for Windows_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1301140/Configure.a.renamed.email.address.on.Outlook.for.Windows_editsKH.pdf)
[Configure a renamed email address on Outlook for Windows_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1301141/Configure.a.renamed.email.address.on.Outlook.for.Windows_editsKH.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8bab3f5687/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-bec2d72201/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
