### PR TITLE
Servers edit 8

### PR DESCRIPTION
**Pull request by stephamon**
Part of #705

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-235c1e4d80/how-to/). :bow:

**Comment by kylelaffoon** [comment]
@stephamon 2 small changes:

In content/cloud-servers/installing-php-on-windows-server-2012.md - 
 Fix added line " +2. Open the file with text editor and perform any necessarymodifications." to "" +2. Open the file with text editor and perform any necessary modifications."
  
In content/cloud-servers/installing-python-novaclient-on-windows.md - 
 modify "After ActiveState Python is installed you can use the python package installer "pip" to"
 to "After ActiveState Python is installed you can use the python package installer `pip` to" to present as a command.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3165a30e2d/how-to/)

**Comment by stephamon** [comment]
@kylelaffoon got it! Thanks!

**Pull request merged**
