### PR TITLE
Full audit and rename

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ab69740161/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4f2fb43684/how-to/)

**Comment by catlook** [comment]
waiting on final determination to publish or retire.

**Comment by catlook** [comment]
steph edit please?

**Comment by stephamon** [comment]
👍

**Pull request merged**
