### PR TITLE
Audit article: INFODEV-2612

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-93b6d1b579/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b37b2da184/how-to/)

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[migrating-exchange-to-exchange-via-outlook_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2496344/migrating-exchange-to-exchange-via-outlook_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-34dc19ad01/how-to/)

**Pull request merged**
