### PR TITLE
Add a private label webmail site

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f859a4a6c4/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f859a4a6c4/how-to/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-f1d2e55d29/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-aae7e406be/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0f7d868789/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9d9d3d5a62/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-11c53ca088/how-to/)

**Comment by cyrichardson** [comment]
@catlook Suggestions here: 
[create-a-private-label-webmail-site_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1782360/create-a-private-label-webmail-site_cyrEdits.docx)

It's mostly just using intital caps for Webmail.... not as much change as it first appears to be.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-af8998a31e/how-to/)

**Comment by RackerKate** [comment]
@WilliamLoy Please adjust numbering.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8f23a7e040/how-to/)

**Pull request merged**
