### PR TITLE
BCP-update-rackspace-account-invoice: INFODEV-910

### PR DESCRIPTION
**Pull request by RackerKate**
Initial commit to create PR. PLACEHOLDER ONLY. Please do not merge.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-27ca2115c4/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4806a77a84/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-08b6522dc3/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e5ddaaeba6/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7f17341622/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson For your review. Thanks.

**Comment by cyrichardson** [comment]
@RackerKate On it!

**Comment by cyrichardson** [comment]
@RackerKate Suggestions here: 
[rackspace-account-invoice+_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/1831402/rackspace-account-invoice._cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-2290dc5789/how-to/). :bow:

**Pull request merged**
