### PR TITLE
Update Cloud Backup article to include new info for agents v2

### LINKED ISSUE #1207: Update Cloud Backup article for agent v2.0
From: Brett Johnson <brett.johnson@RACKSPACE.COM>
Date: Thursday, July 7, 2016 at 1:53 PM
To: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>
Cc: Cloud Backup <CloudBackup@rackspace.com>
Subject: Support Page Update

Hey, Catherine!

The instructions on this page need to be updated to reflect the features of the 2.0 agent (which is currently in production) when you get some time:

https://support.rackspace.com/how-to/rackspace-cloud-backup-install-the-agent-on-windows/ 

#1
In the section titled, “Uninstall Cloud Backup agent on Windows,” the following sentence should be changed:

To uninstall the Cloud Backup agent, the preferred method is to uninstall using the Windows Control Panel. However, you can also use msiexec from the command line.

It should read:

To uninstall the Cloud Backup agent, the preferred method is to use Add/Remove Programs in the Windows Control Panel; however, there are cases where the Rackspace Cloud Backup entry may not exist there. In those cases, you can use the command line to uninstall.

#2
In the same section, the following example code should be changed:

msiexec
 /x driveclient-1.18.007148-en-us.msi /qn /l*v %tmp%\uninstall-1.18.007148.log

It should read:

msiexec /x driveclient-latest.msi /qb /l*v %tmp%\uninstall.log

#3
In the same section, the following line should be removed:

Run %programfiles%\driveclient\uninst.exe

#4
In the same section, after the msiexec example code, this line should be inserted:

NOTE: If the agent installed on your server is not the latest agent, you will have to download the old MSI installer file in order to use it to uninstall the old agent. Your current agent version is displayed as “Agent Version:” on the Backups System Details page. You can find and download the MSI for this version here: http://agentrepo.drivesrvr.com/win64/old_msi/

#5
In the same section, the following line and its companion sample folder directory should be deleted:

“The path %programfiles%\driveclient contains a single file: install.log

#6
In the same section, the following line and its companion sample folder directory should be replaced:

The %programdata%\driveclient path does not exist.

It should read:

The %programdata%\driveclient path contains files and folders that may be used to reinstall the agent without re-registering, if desired. If you are sure that you will not reinstall the agent, these files and folders may be deleted.

C:\>dir %programdata%\driveclient
 Volume in drive C is System
 Volume Serial Number is 9A20-F50E

 Directory of C:\ProgramData\driveclient

06/17/2016  04:00 PM    <DIR>          .
06/17/2016  04:00 PM    <DIR>          ..
05/27/2016  02:16 PM                 0 backup-running.lock
06/17/2016  03:54 PM             3,720 bootstrap.json
04/01/2016  07:25 PM             3,801 bootstrap.json.20160426102748
04/01/2016  07:25 PM    <DIR>          log
06/17/2016  03:58 PM               827 log4cxx.xml
05/27/2016  02:16 PM    <DIR>          MossoCloudFS_ede95edd-78f8-4097-82de-5dfa7941b7c7
06/17/2016  03:54 PM               451 public-key.pem
05/27/2016  02:19 PM               305 rse-client-state.json
05/27/2016  02:16 PM    <DIR>          vss
              10 File(s)         23,984 bytes
               5 Dir(s)   6,035,111,936 bytes free

#7
In the same section, the following line should be deleted:

There should be no scheduled tasks to “check for driveclient update.”

#8
In the same section, the following line should be changed:

C:>sc query driveclientsvc [SC] EnumQueryServicesStatus:OpenService FAILED 1060: The specified service does not exist as an installed service.

It should read:

C:\>sc query driveclient
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.

#9
In the section named “Uninstall the agent from older versions of Windows,” there should be no changes at this time.

More updates may be forthcoming later, but this is all for the time being.

Thanks so much!

### PR DESCRIPTION
**Pull request by cyrichardson**
Fixes #1207

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-86d4a4225a/how-to/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-dc8b98a909/how-to/).

**Comment by cyrichardson** [comment]
@brett-johnson Please review the changes you requested here and let e know if they are ready to merge: https://staging.developer.rackspace.com/support.rackspace.com/build-86d4a4225a/how-to/rackspace-cloud-backup-install-the-agent-on-windows/

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7ddba02ede/how-to/)

**Comment by cyrichardson** [comment]
This PR is for #1207. Reopened #1210.

**Pull request merged**
