### PR TITLE
Audit article about Windows patches for managed ops: INFODEV-2370

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d9a3c0862f/how-to/)

**Comment by rackernexus** [comment]
Build 75 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a917fe486/docs/). valid for 14 days

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-95e1c37609/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-35ed2c139e/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by rackernexus** [comment]
Build 76 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-60bad4d4d/docs/). valid for 14 days

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
Build 77 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d7e32e19b/docs/). valid for 14 days

**Comment by cyrichardson** [comment]
@RackerKate Just nits: 
[windows-patches-for-cloud-servers-with-a-managed-operations-service-level_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2846683/windows-patches-for-cloud-servers-with-a-managed-operations-service-level_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-6687184708/how-to/)

**Comment by rackernexus** [comment]
Build 78 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f6e31e9b8/docs/). valid for 14 days

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-521e08a1f2/how-to/)

**Comment by rackernexus** [comment]
Build 79 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-27926b127/docs/). valid for 14 days

**Pull request merged**
