### PR TITLE
Format update for images RBAC matrix

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-385c9725b2/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-84d4037115/how-to/)

**Comment by catlook** [comment]
@kmsholcomb Please review.  I'd love to get this in before sprint closes this morning!!

**Comment by stephamon** [comment]
👍

**Pull request merged**
