### PR TITLE
Create managing-cloud-databases-ha-groups-in-the-cloud-control-panel.md

### LINKED ISSUE #662: Cloud databases - process new article
@RackerSCroce submitted new article: #660 
- [x] Upload images 
- [x] Add link path to images to article
- [ ] Editorial review

### PR DESCRIPTION
**Pull request by RackerSCroce**
Adding a new article on managing HA groups from the control panel

fixes #662

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-69f0c9b1ed/how-to/)

**Comment by stephamon** [comment]
Okay, I've got the images in. @kmsholcomb will you take a look?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-b56f825286/how-to/)

**Comment by kmsholcomb** [comment]
Will do, @stephamon.

**Comment by kmsholcomb** [comment]
Hi @stephamon: Edits are in the attached Word doc (and PDF copy of the Word doc). Please let me know if you have any questions. Thanks!

[Managing Cloud Databases High Availability Instance groups in the Cloud Control Panel_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/189780/Managing.Cloud.Databases.High.Availability.Instance.groups.in.the.Cloud.Control.Panel_editsKH.pdf)
[Managing Cloud Databases High Availability Instance groups in the Cloud Control Panel_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/189781/Managing.Cloud.Databases.High.Availability.Instance.groups.in.the.Cloud.Control.Panel_editsKH.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-a66e096d78/how-to/)

**Pull request merged**
