### PR TITLE
Enable DKIM in Cloud Office Control Panel

### PR DESCRIPTION
**Pull request by bes6323**
We have recently released the DKIM feature in the Cloud Office Control Panel. The two new how-to pages are for the Rackspace Email and Hosted Exchange products. The articles are the same, just duplicated for each product. I have emailed the associated screen shot images.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7c82132f3f/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c461a437ad/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2d64fb4aab/how-to/)

**Comment by DonNateR** [comment]
@bes6323: The content in this article looks very similar to an already published article: https://support.rackspace.com/how-to/create-a-dkim-txt-record/ .

That being said, your instructions are more detailed. Is there big a difference between "Enabling" DKIM, and creating a DKIM TXT record?

**Comment by bes6323** [comment]
That how-to is for the Cloud Control Panel. It's a different product, and has nothing to do with the DKIM feature we've added to the Hosted Email platform.

**Comment by DonNateR** [comment]
@bes6323: I see that now! Sorry about that. I'll work on getting this up ASAP.

**Comment by bes6323** [comment]
No sweat, I did the same thing when I was putting this together. I appreciate the help.

**Comment by DonNateR** [comment]
Images for the article are sent through email

**Comment by DonNateR** [comment]
Edits on PR #2032. Closing this PR and moving to that one.

**Pull request closed without merging**
