### PR TITLE
Add federation docs for cloud: INFODEV-2837

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-8341326a8c/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review. This is similar to the earlier one, but for cloud.

**Comment by cyrichardson** [comment]
Thanks, @RackerKate. On it.

**Comment by cyrichardson** [comment]
@RackerKate One small thing noted: 
[id-federation-map-policies-permissions-cloud_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2589794/id-federation-map-policies-permissions-cloud_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-1e8d73d435/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-e530619e9c/how-to/)

**Pull request merged**
