### PR TITLE
Addcputoserv

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by Sterling463** [comment]
@stephamon

**Comment by Sterling463** [comment]
Build me

**Comment by rackernexus** [comment]
Build 944 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-8a0e633cd/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 950 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-0ae18d70b/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 952 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c423a2846/how-to/). valid for 14 days

**Pull request merged**
