### PR TITLE
Convert Community article: Checking Windows Server Uptime

### PR DESCRIPTION
**Pull request by BadCrumpany**
Migrating article from the community as it will be shutting down soon.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7a444ac648/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-091d033a3d/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-9fccb0e45a/how-to/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d0cfba8f32/how-to/).

**Comment by cyrichardson** [comment]
@RackerKate On it.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3bd1db15fc/how-to/)

**Pull request merged**
