### PR TITLE
Audit article mapping aws to rackspace: INFODEV-2686

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-673404f67b/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c6920ea684/how-to/)

**Comment by RackerKate** [comment]
@cyrichardson Please review. Apologies if this is a duplicate; I had problems with Git and had to finish an article by the end of the day last Friday, so I ended up deleting and re-cloning my repo.

**Comment by cyrichardson** [comment]
No problem, @RackerKate. This is in the queue right after you other article.

**Comment by cyrichardson** [comment]
@RackerKate Just a couple of suggestions here: 
[mapping-of-amazon-web-services-resources-to-rackspace-resources_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2554401/mapping-of-amazon-web-services-resources-to-rackspace-resources_cyrEdits.docx)

**Pull request merged**
