### PR TITLE
new article: Combined invoices

### LINKED ISSUE #1901: New article: Billing invoice consolidation
This article does not need to be published until the feature is live in June 2017. I've gotten a lot of information from the development team that I'll use to pull together one or more articles.

### PR DESCRIPTION
**Pull request by stephamon**
Fixes #1901 

Takes over #2198 because I accidentally deleted that local branch

### CODE REVIEW

**Comment by stephamon** [comment]
Launch date 09/18

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-69ecf0ce11/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3c04a3c60c/how-to/). :bow:

**Comment by stephamon** [comment]
Hey @kmsholcomb can you take a look at this article?

**Comment by kmsholcomb** [comment]
Hi @stephamon. My suggested edits are attached. Please let me know if you have any questions. 

[Combine invoices for Rackspace Managed and Cloud accounts_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1264362/Combine.invoices.for.Rackspace.Managed.and.Cloud.accounts_editsKH.docx)
[Combine invoices for Rackspace Managed and Cloud accounts_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1264361/Combine.invoices.for.Rackspace.Managed.and.Cloud.accounts_editsKH.pdf)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-a211535f41/how-to/). :bow:

**Pull request merged**
