### PR TITLE
edits applied

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1635 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-554b9d545/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1636 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-554b9d545/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 1637 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-89b23b9d6/how-to/). valid for 14 days

**Pull request merged**
