### PR TITLE
Community Article - Creating and Editing Users in MySQL

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-82b40993f3/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2e524ef892/how-to/)

**Comment by RackerKate** [comment]
Close due to build issue. Replaced by #3139 .

**Pull request closed without merging**
