### PR TITLE
Create create-copy-move-delete-files

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1639 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-11f398703/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1641 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6532b7b62/how-to/). valid for 14 days

**Pull request merged**
