### PR TITLE
add dedicated folder, index, and faq pages

### PR DESCRIPTION
**Pull request by stephamon**
This PR adds the dedicated-hosting folder, along with the index page and faq.

NOT READY TO MERGE.

I'm still waiting on an initial article from the Dedicated team.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-4a454e7221/how-to/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-580717c3d8/how-to/)

**Comment by stephamon** [comment]
@kmsholcomb could you take a look at these initial Dedicated files?

**Comment by kmsholcomb** [comment]
Will do, @stephamon. I'll post edits tomorrow morning.

**Comment by kmsholcomb** [comment]
Hi @stephamon. The attached Word doc (and PDF) have my suggested edits for the three articles with text. I suggested quite a few changes in the Red Hat/CentOS article, so please let me know if you have any questions for that one, or the other two. Thanks!

[Dedicated Hosting_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/581643/Dedicated.Hosting_editsKH.pdf)
[Dedicated Hosting_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/581644/Dedicated.Hosting_editsKH.docx)

**Comment by stephamon** [comment]
Awesome! This is good to merge as soon as the Dedicated section goes live!

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-e1fac12d90/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-634965dc4b/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-0bd9e0d923/how-to/)

**Pull request merged**
