### PR TITLE
Change rackspace email mailbox password

### PR DESCRIPTION
**Pull request by WilliamLoy**
rsechangepasswordsc1
rsechangepasswordsc2
rsepasswordresetcpc1
rsepasswordresetcpsc2
rsepasswordresetcpsc3

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-95bce21826/how-to/)

**Comment by nimbinatus** [comment]
@WilliamLoy, thanks for the PR! We'll pull it into the next available slot for our sprint. FYI: Our build server is having a small hiccup, so don't panic about the failed check from Strider and the lack of a staging preview for your latest commits.

**Comment by WilliamLoy** [comment]
@nimbinatus  thanks for the update! Nate filled me in on the situation.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-d871d54ff5/how-to/)

**Pull request merged**
