### PR TITLE
Fixes #1245 with updates from Brett Johnson

### LINKED ISSUE #1245: Update Cloud Backup best practices article
From: Brett Johnson <brett.johnson@RACKSPACE.COM>
Date: Friday, July 15, 2016 at 2:30 PM
To: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>
Cc: Cloud Backup <CloudBackup@rackspace.com>
Subject: Best practices for Cloud Backup

Updates for this page: https://support.rackspace.com/how-to/best-practices-for-cloud-backup/

#1
Under Key concepts, this bullet point:
Backup: a spare copy of data to be used in the event of a failure or loss of the original.

should read:
Backup: a copy of data to be used for restoring that data, in the event of corruption or loss of the original.

The bullet point:
Backup Configuration: instructions to the backup agent that indicate 1) what you want to backup and 2) how often you’d like to save that information.

should read:
Backup Configuration: instructions to the backup agent that indicate 1) what you want to backup, 2) how often you’d like to save that information, and 3) how long you would like to keep that information.

The bullet point:
Cloud Backup Agent: a program installed on your server that knows how to perform backups and restores.

should read:
Cloud Backup Agent: a program installed on your server that helps to perform backups and restores.

The bullet point:
The Vault: disk space that contains information about every block of data that you’ve ever stored. It is shared between all of your backup configurations.

should read:
The Vault: disk space that contains information about every block of data that you currently have stored. It is shared between all of your backup configurations for that server.

#2
Under Choosing what to back up, in the sentence:
Our best guidance is not what to back up, but what not to back up:

the first occurrence of “what” should also be italicized.

The bullet point:
Do not back up root - to save all data and the server, make an image of the server instead.

should be:
Do not back up root. In order to save all data and the server, make an image of the server instead.

In the note, this sentence:
Deduplication stores only the updated data, and saves you storage space and money during the backup process.

should be:
Deduplication works across all files in all snapshots and stores only the new data. This almost always saves you more storage space and money during the backup process than simple compression.

#3
New section outlined below. Title:
Conserving resources with Cloud Backup

Some elements of Cloud Backup take up a non-trivial amount of space on a server’s system drive. When running Cloud Backup on servers with limited resources, such as small system drives, there are some things that can help reduce its footprint significantly.

Other than the relatively small files necessary to make Cloud Backup work, such as the agent and tool executables, and configuration files, there are some files that have the capacity to grow very large. They are agent log files and local agent backup database files. The log files by default are configured to have a maximum size, but even though these files typically grow very slowly, that size can eventually become very large over time. The local agent backup database files, on the other hand, can grow indefinitely and very quickly, depending on the configuration of your backups.

There are ways to keep these files smaller. For log files, you can set the maximum file size and the maximum rollover files to small values, and you can set the normal logging mode to be less verbose. For database files, you can set the expiration of backed-up files to something other than “infinite,” and you can back up fewer and smaller files, and back up less frequently.

But the best way to reduce the size of backup files your system drive is to move most of them off of the system drive onto another drive. In order to do this on both Linux and Windows, if you do not already have another drive to move these files to, you must first create the second drive and attach it to your system.

The procedure to move the two biggest types of Cloud Backup files off a Linux system drive is simple. Create a symlink or mount point on the path of the logs or the database files. For information on where these paths are, see [Locations of Cloud Backup agent files][https://support.rackspace.com/how-to/cloud-backup-agent-logging-basics/].

The procedure to move these files off the system drive of a Windows system is also simple, if you use the AgentConfig.exe tool located in the C:\Program Files\Driveclient folder. Double-click the tool to open the UI, and choose the second tab, named, “Cache.”

The current location for the cache, which holds both both the log files and the local agent backup database files, is in the “Cache Source Location.”

Change the location by clicking the folder button next to “Cache Target Location” and selecting a folder on a different drive.

To move the cache location, click the green arrow. The progress is displayed in the “Move Log” window. 

Please note that, depending on the size of the cache files, this process may take a while. Also, please note that in order to move these cache files, the Cloud Backup agent service must be shut down briefly.

If you wish, you can move just the agent backup local database by using the “Database” tab.

#4
New section outlined below. Title:
Other optimizations with AgentConfig.exe

The AgentConfig.exe tool is capable of doing a number of other optimizations, in addition to moving the agent cache location.

Please note that multiple of these settings can be changed at one time, when you click the blue Save button.

Disabling VSS backups

By default, VSS is use used to make backups more reliable; however, there may be times when VSS gets in the way. For instance, it may take up disk space on a volume that is already running low. In order to turn off VSS shadowing for backups, check the “VSS Disable” checkbox and click the blue Save button.

Turning off auto-update

Auto-update is a service that continually keeps the Cloud Backup agent updated. In rare cases, you might want to turn this service off. To do that, check the “Auto Update Disable” checkbox and click the blue Save button.

Debugging auto-update

There also may be times when you might need to debug auto-update. This setting not only debugs the auto-updater service (in the Event Logger), but it also debugs the installer and MSI, as well. To turn on debugging for auto-update, check the “Auto Update Debub” checkbox and click the blue Save button.

Repair the Add/Remove Programs listing

Older versions of the agent were sometimes installed without adding an entry in the Add/Remove Programs uninstall console. This can be repaired by checking the “Repair Add/Remove Programs Listing” checkbox and clicking the blue Save button.

Log controls

The logs level is controlled by the Cloud Backup Control Panel; however, these settings can be altered locally either by editing the log4cxx.xml config file directly, or by using the AgentConfig.exe tool. You can exercise far greater control over the log configuration by editing this config file by hand, but not everyone has the time or expertise to do this. To make this easier, the three most commonly changed settings are controlled by the AgentConfig.exe tool.

The maximum log size may be set by changing the value in the spinner named “Max Log Size (MB)” and clicking the blue Save button.
The maximum rollover logs may be set by changing the value in the spinner named “Max Rollover Logs” and clicking the blue Save button.
The log level can be temporarily changed by selecting the setting  you want via the drop-down box on the “General” settings tab and clicking the blue Save button. Please note that the log level will be changed every time the Cloud Backup API sends a config change/update to the agent. In order to keep logging at the desired level, you will want to set your log level in the Control Panel, as well. The advantage of setting the log level locally is that it will change the level prior to receiving a config change/update. This is useful for things like debugging agent startup.

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by cyrichardson** [comment]
@kmsholcomb A new section has been added. If you have time, I would appreciate your review.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-eb41bee352/how-to/)

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. I'll look at it today!

**Comment by cyrichardson** [comment]
@kmsholcomb Thank you!

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. I edited the whole file; see the attached Word and PDF documents for my markup (markup is the same in both). Please let me know if you have any questions. Thanks!

[Best practices for Cloud Backup_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/374295/Best.practices.for.Cloud.Backup_editsKH.pdf)
[Best practices for Cloud Backup_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/374296/Best.practices.for.Cloud.Backup_editsKH.docx)

**Comment by cyrichardson** [comment]
@kmsholcomb Thanks so much!!!

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-eabcc2a359/how-to/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f0b67fea6b/how-to/)

**Pull request merged**
