### PR TITLE
Create new article for allowing web traffic in UFW

### PR DESCRIPTION
**Pull request by csilva235**
Creating a new article to help customers allow web traffic in UFW software firewalls

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1328 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3b9c2ec9f/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1329 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d1a9a5e08/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1330 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-d1a9a5e08/how-to/). valid for 14 days

**Comment by csilva235** [comment]
Found issues with formatting and content. Closing and resubmitting to clean up commits.

**Comment by rackernexus** [comment]
Build 1332 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-259fee7fb/how-to/). valid for 14 days

**Pull request closed without merging**
