### PR TITLE
New Article: Firewall manager v2 access-list rules

### PR DESCRIPTION
**Pull request by trevorbecker**
creating PR for 6th and final article of the week.
Need to see how staging formats this.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-0d5966b1fd/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-84194f75f5/how-to/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-1cc8528560/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-5c6d371519/how-to/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-4c6d32ba4d/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-af819d8899/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-1480864191/how-to/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9cc8154f08/how-to/)

**Comment by kmsholcomb** [comment]
Hi @DonNateR. My suggested edits are attached. I added in the screenshots that Trevor sent via email, where I thought they should go. :) Please let me know if you have any questions or feedback. Thanks!

[Firewall Manager v2 access-list rules_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/873654/Firewall.Manager.v2.access-list.rules_editsKH.pdf)
[Firewall Manager v2 access-list rules_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/873655/Firewall.Manager.v2.access-list.rules_editsKH.docx)

**Comment by trevorbecker** [comment]
I agree with the entirety of the review. this is so much better. Thank you for the improvements @kmsholcomb ! (Especially with the renumbering of the add access-list section) huge help!

**Comment by kmsholcomb** [comment]
You are welcome, @trevorbecker. I still love digging into a good procedure. :) Glad it helps!

**Comment by DonNateR** [comment]
Moved to PR #1943

**Pull request closed without merging**
