### PR TITLE
removed line about rebooting

### PR DESCRIPTION
**Pull request by davisaaronj**
Needing to reboot to install the agent is incorrect I have updated the article to reflect this.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-56fadac6ea/how-to/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-3d414414bf/how-to/). :bow:

**Comment by kmsholcomb** [comment]
Hi @DonNateR. Edits are attached. I edited the article three years ago, so of course I found more to mark up this time. :) Please let me know if you have any questions, or have any feedback on any of my questions/comments. Thanks!

[Install or update the Cloud Backup agent on Linux_editsKH.pdf](https://github.com/rackerlabs/rackspace-how-to/files/1058762/Install.or.update.the.Cloud.Backup.agent.on.Linux_editsKH.pdf)
[Install or update the Cloud Backup agent on Linux_editsKH.docx](https://github.com/rackerlabs/rackspace-how-to/files/1058763/Install.or.update.the.Cloud.Backup.agent.on.Linux_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c7358c5b37/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-7ca21744c4/how-to/)

**Comment by stephamon** [comment]
👍

**Pull request merged**
