### PR TITLE
Create active-directory-creating-managing-and-deleting-users-and-groups

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1956 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b2b03e9a7/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1958 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b2b03e9a7/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 1959 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-1caf5a9b5/how-to/). valid for 14 days

**Pull request merged**
