### PR TITLE
Network Fundamentals

### PR DESCRIPTION
**Pull request by THE-Alan-Hicks**
This is a port of the "award winning" one-wiki article <refer to email thread for article>

I've converted everything into Markdown and sanity checked it all to ensure there's no private Rackspace information shared in this article. Some Rackspace IP addresses are mentioned, but anyone could determine that they belong to Rackspace with a simple public PTR record lookup on the addresses.

Additionally this includes a brand new image courtesy of David Chandler which replaces the ugliest ASCII-art diagram in history.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-2251550275/how-to/)

**Comment by THE-Alan-Hicks** [comment]
Hmm.... Now that I'm able to preview this on the staging site, there's a number of small problems that are cropping up. Notably, all of my code blocks which require multiple lines are being output as single-line statements. Any ideas on how to fix this would be greatly appreciated.

**Comment by stephamon** [comment]
Hey @THE-Alan-Hicks sometimes it can be a little picky about the triple back tick method for code blocks. 

Try pulling out the back ticks indenting each line of code by 4 spaces instead. I know it's kind of a pain, but that usually does the trick.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9d65f28adc/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-e859947919/how-to/). :bow:

**Comment by THE-Alan-Hicks** [comment]
Fixing the issues I've discovered here and closing this request. I'll generate a new one momentarily.

**Pull request closed without merging**
