### PR TITLE
Audit preparing-an-image-for-import-into-the-rackspace-opencloud.md: INFODEV-1282

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5c1d90024e/how-to/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-f39197f61a/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-c19ed6a861/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-fa313d3b76/how-to/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson For your review. I'm not sure why the last 2 links in the article (to the blog) aren't working. Maybe it's because they're not part of the how-to site, and therefore the URLs don't work with the build.

**Comment by cyrichardson** [comment]
Thanks, @RackerKate. In the review queue... will check on the 2 links you mention.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-81a7239ed5/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-ec030900e7/how-to/)

**Pull request merged**
