### PR TITLE
Add new diagrams to Cloud Reference Architecture

### PR DESCRIPTION
**Pull request by DonNateR**
- Fixes issue #1217

### CODE REVIEW

**Comment by DonNateR** [comment]
I still have two more diagrams left to complete.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-5658c39894/how-to/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-0e0206f040/how-to/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-72e5425693/how-to/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-618e9a36bb/how-to/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/support.rackspace.com/build-9fa9a7c4ab/how-to/)

**Comment by catlook** [comment]
👍

**Pull request merged**
