### PR TITLE
Audit Choosing the right size cloud server: INFODEV-2640

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-3c37babe39/how-to/).

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate!

**Comment by cyrichardson** [comment]
@RackerKate Just a few suggestions here: 
[rackspace-cloud-essentials-choosing-the-right-size-cloud-server_cyrEdits.docx](https://github.com/rackerlabs/rackspace-how-to/files/2531665/rackspace-cloud-essentials-choosing-the-right-size-cloud-server_cyrEdits.docx)

**Pull request merged**
