### PR TITLE
Create troubleshoot-sql-server-backup-failures

### PR DESCRIPTION
**Pull request by BadCrumpany**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 1419 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-7b6efb172/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1594 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-776e88df2/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1595 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c5bf39219/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1596 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-f58731c4b/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1597 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-c0b657662/how-to/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1598 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-6eb84828a/how-to/). valid for 14 days

**Pull request merged**
