### PR TITLE
Servers edit 3

### PR DESCRIPTION
**Pull request by stephamon**
Part of #705

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-68e96e638c/how-to/).

**Comment by kylelaffoon** [comment]
@stephamon These look good except we need to omit the word "button" from the following areas: cloud-servers/create-a-csr-in-the-cloud-control-panel.md
change step 1 to omit "button"

creating-an-image-backup-cloning.md
step 3

create-a-cloud-server.md
Step 2

**Comment by stephamon** [comment]
@kylelaffoon Done and done! Good catch!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-ff6fe6cbbf/how-to/). :bow:

**Pull request merged**
