### PR TITLE
Delete alias for username before restoring deleted mailbox

### PR DESCRIPTION
**Pull request by stevepiercy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 190 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-3e21dbf79/how-to/). valid for 14 days

**Comment by WilliamLoy** [comment]
@stevepiercy Thank you for the submission! I will be reviewing this shortly and will tag you once the changes are merged.

**Comment by WilliamLoy** [comment]
@cyrichardson a short one for you to look at please :)

**Comment by cyrichardson** [comment]
On it, @WilliamLoy

**Comment by rackernexus** [comment]
Build 215 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b6dc46795/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 216 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-b6dc46795/how-to/). valid for 14 days

**Comment by rackernexus** [comment]
Build 217 was successful. Staging content [Preview!](https://support-revs.staging.deconst.org/build-84aa125af/how-to/). valid for 14 days

**Pull request merged**
