### PR TITLE
Create set-up-mobile-sync.md

### PR DESCRIPTION
**Pull request by intertial-nullifier**
This article has been creating to replace https://support.rackspace.com/how-to/set-up-mobile-sync-for-webmail-on-ios-devices/ at the request of Brian Hazzard.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/support.rackspace.com/build-657e965377/how-to/).

**Comment by stephamon** [comment]
fixes #1944

**Comment by stephamon** [comment]
Hi @intertial-nullifier is there any more information we can include here other than just pointing to the help tool? The old version that this will replace is one of our most viewed articles, so I want to make sure that this one is equivalent. 

With other Cloud Office articles, we've pointed to the help tool but then also included a tutorial of how to complete the task.

**Comment by intertial-nullifier** [comment]
Funny you should ask, I was thinking the same thing!  I just sent an email to you, Brian, and Ashley on that exact topic.  I would be happy to include similar setup instructions in the article itself, I just wasn't sure if that was what Brian had envisioned.


I'm going to be meeting with Brian today around 1 so we can hash it out then.


Jesse Miller
Customer Service Technician II - Cloud Office
________________________________

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-c751147160/how-to/). :bow:

**Comment by nimbinatus** [comment]
Strider hung on this one; I'm redelivering the package now. You should see a preview link soon.

**Pull request merged**
